function mapping = build_stage_f_rolling_element_linearization_mapping(source,varargin)
%BUILD_STAGE_F_ROLLING_ELEMENT_LINEARIZATION_MAPPING Formal Stage F contact map.

if nargin == 1
    mapping = mapping_from_fixture(source);
elseif nargin == 3
    mapping = mapping_from_canonical(source,varargin{1},varargin{2});
else
    mapping_not_available('Stage F mapping requires a fixture or canonical results, temperature, and bearing.');
end
mapping = finish_mapping(mapping);
end

function mapping = mapping_from_fixture(fixture)
required = {'bearing_label','contact_kind','element_count','slice_count', ...
    'delta_static_slice','Q_static_slice','k_static_slice', ...
    'loaded_mask_static_slice','formal_contact_jacobian_snapshot', ...
    'formal_force_assembly_snapshot','bearing_interface_transform_5dof', ...
    'K_b_local','contact_stiffness_source','formal_contact_law', ...
    'formal_geometry','mapping_provenance'};
if ~isstruct(fixture) || ~all(isfield(fixture,required)) || ...
        ~formal_provenance_valid(fixture.mapping_provenance)
    mapping_not_available('The formal five-DOF mapping provenance is incomplete.');
end
mapping = struct('bearing_label',char(fixture.bearing_label), ...
    'contact_kind',char(fixture.contact_kind), ...
    'element_count',fixture.element_count,'slice_count',fixture.slice_count, ...
    'delta_static_slice',fixture.delta_static_slice, ...
    'Q_static_slice',fixture.Q_static_slice, ...
    'k_static_slice',fixture.k_static_slice, ...
    'loaded_mask_static_slice',logical(fixture.loaded_mask_static_slice), ...
    'contact_jacobian_local',fixture.formal_contact_jacobian_snapshot, ...
    'force_assembly_local',fixture.formal_force_assembly_snapshot, ...
    'interface_transform',fixture.bearing_interface_transform_5dof, ...
    'K_b_local',fixture.K_b_local, ...
    'contact_stiffness_source',char(fixture.contact_stiffness_source), ...
    'formal_contact_law',fixture.formal_contact_law, ...
    'formal_geometry',fixture.formal_geometry, ...
    'mapping_provenance',fixture.mapping_provenance);
validate_static_contact_state(mapping,true);
end

function mapping = mapping_from_canonical(results,temperature,bearing)
accepted_stage_d = '23a975c2c762504dc4ae62f07379737582fd783f';
accepted_stage_e = '0cab3dc49dfffc4192066402cb70302f084cb45d';
if ~(isstruct(results) && isnumeric(temperature) && isscalar(temperature) && ...
        any(temperature == [20 50 80 100]) && ...
        (ischar(bearing) || (isstring(bearing) && isscalar(bearing))))
    mapping_not_available('Canonical Stage F mapping inputs are invalid.');
end
bearing = char(bearing);
if ~any(strcmp(bearing,{'front','rear'})) || ~isfield(results,'meta') || ...
        ~all(isfield(results.meta,{'stage_d_source_commit','stage_e_source_commit'})) || ...
        ~strcmp(results.meta.stage_d_source_commit,accepted_stage_d) || ...
        ~strcmp(results.meta.stage_e_source_commit,accepted_stage_e) || ...
        ~isfield(results,'static') || ~isfield(results.static,'T20') || ...
        ~isfield(results.static.T20,'bearing_mapping')
    mapping_not_available('Accepted Stage D/E canonical provenance is unavailable.');
end
tf = sprintf('T%d',temperature);
state_field = ['bearing_state_' bearing];
if ~isfield(results.static,tf) || ~isfield(results.static.(tf),state_field)
    static_inconsistent('The formal canonical contact state is missing.');
end
static_state = results.static.(tf);
contact = static_state.(state_field);
[Q,delta,loaded,k,source] = canonical_contact_state(static_state,contact,tf,bearing,temperature);
transform_field = [bearing '_B'];
if ~isfield(results.static.T20.bearing_mapping,transform_field)
    mapping_not_available('The accepted bearing interface transform is missing.');
end
interface_transform = results.static.T20.bearing_mapping.(transform_field);
if temperature == 20
    stiffness_field = ['bearing_stiffness_' bearing];
    if ~isfield(static_state,stiffness_field) || ...
            ~isfield(static_state.(stiffness_field),'K_local')
        mapping_not_available('The accepted T20 bearing tangent is missing.');
    end
    K_b_local = static_state.(stiffness_field).K_local;
else
    stiffness_field = ['K_b_' bearing];
    if ~isfield(static_state,stiffness_field)
        mapping_not_available('The accepted Stage D bearing tangent is missing.');
    end
    K_b_local = static_state.(stiffness_field);
end
[J,A,geometry,kind,element_count,slice_count] = canonical_contact_geometry(contact,bearing);
provenance = struct( ...
    'schema','STAGE_F_FORMAL_5DOF_MAPPING_PROVENANCE_V1', ...
    'accepted_stage_d_commit',accepted_stage_d, ...
    'accepted_stage_e_commit',accepted_stage_e, ...
    'stage_d_source_commit',results.meta.stage_d_source_commit, ...
    'stage_e_source_commit',results.meta.stage_e_source_commit, ...
    'canonical_sha256','3f0e6e3b379cda670ef173682c58d17a19fc6b30f761ed59a00f3c203793abfd', ...
    'contact_state_path',source.contact_state_path, ...
    'contact_state_source_path',source.contact_state_path, ...
    'contact_state_source_mode',source.contact_state_mode, ...
    'loaded_mask_source_path',source.loaded_mask_path, ...
    'loaded_mask_source_mode',source.loaded_mask_mode, ...
    'contact_stiffness_source_path',source.contact_stiffness_path, ...
    'contact_stiffness_source_mode',source.contact_stiffness_mode, ...
    'interface_transform_path',['results.static.T20.bearing_mapping.' transform_field], ...
    'contact_kernel_file','nonlinear_bearing_force.m', ...
    'contact_kernel_function','nonlinear_bearing_force', ...
    'contact_kernel_sha256','d82ae8cc92a1f1fb55d9d0c14da3efa196e9f085ce22abc5cdd2b345f93af5c8', ...
    'static_extractor_file','extract_stage_d_static_state.m', ...
    'static_extractor_sha256','94ca056ad4b7f867851f7698f1241e9f85d55a011d904ba2620fa30395387661', ...
    'interface_mapping_file','build_stage_e_observation_mapping.m', ...
    'interface_mapping_sha256','c74a92064886aa66e46a9a7b97ece787e4e4603ea198ab2814ad1450c7461b5b', ...
    'verified',true);
exponent = 3/2;
if strcmp(bearing,'rear'), exponent = 10/9; end
coefficient = loaded_law_coefficient(Q,delta,loaded,exponent);
mapping = struct('bearing_label',bearing,'contact_kind',kind, ...
    'element_count',element_count,'slice_count',slice_count, ...
    'delta_static_slice',delta,'Q_static_slice',Q, ...
    'k_static_slice',k,'loaded_mask_static_slice',logical(loaded), ...
    'contact_jacobian_local',J,'force_assembly_local',A, ...
    'interface_transform',interface_transform,'K_b_local',K_b_local, ...
    'contact_stiffness_source',source.contact_stiffness_mode, ...
    'formal_contact_law',struct('coefficient',coefficient,'exponent',exponent), ...
    'formal_geometry',geometry,'mapping_provenance',provenance);
validate_static_contact_state(mapping,false);
end

function [Q,delta,loaded,k,source] = canonical_contact_state(static_state,contact,tf,bearing,temperature)
contact_path = ['results.static.' tf '.bearing_state_' bearing];
required = {'Q','delta','delta_raw','theta','contact_angle','film','raw_contact','r'};
if ~isstruct(contact) || ~all(isfield(contact,required)) || ...
        ~isstruct(contact.film) || ~isfield(contact.film,'loaded_mask') || ...
        ~isstruct(contact.raw_contact) || ...
        ~all(isfield(contact.raw_contact,{'loaded','Q','delta','delta_raw'}))
    static_inconsistent('Formal film/raw contact fields are incomplete.');
end
Q = contact.Q; delta = contact.delta;
loaded = logical(contact.film.loaded_mask);
if ~isequaln(contact.film.loaded_mask,contact.raw_contact.loaded) || ...
        ~isequaln(Q,contact.raw_contact.Q) || ...
        ~isequaln(delta,contact.raw_contact.delta) || ...
        ~isequaln(contact.delta_raw,contact.raw_contact.delta_raw) || ...
        ~isequal(size(Q),size(delta),size(loaded))
    static_inconsistent('Formal film and raw contact states disagree.');
end
exponent = 3/2;
if strcmp(bearing,'rear'), exponent = 10/9; end
if temperature == 20
    k = zeros(size(delta));
    k(loaded) = exponent*Q(loaded)./delta(loaded);
    source = struct('contact_state_path',contact_path, ...
        'contact_state_mode','T20_DIRECT_CANONICAL_BEARING_STATE', ...
        'loaded_mask_path',[contact_path '.film.loaded_mask + ' contact_path '.raw_contact.loaded'], ...
        'loaded_mask_mode','T20_FORMAL_FILM_AND_RAW_CONTACT_AGREEMENT', ...
        'contact_stiffness_path',[contact_path '.Q/.delta + ' contact_path '.raw_contact.Q/.delta'], ...
        'contact_stiffness_mode','FORMAL_DERIVATIVE_IDENTITY_K_EQUALS_P_Q_OVER_DELTA');
else
    mask_field = ['loaded_mask_' bearing];
    k_field = ['contact_stiffness_' bearing];
    if ~isfield(static_state,mask_field) || ~isfield(static_state,k_field)
        static_inconsistent('Saved Stage D contact mask or stiffness is missing.');
    end
    saved_roller_mask = logical(static_state.(mask_field));
    if strcmp(bearing,'rear'), roller_mask = any(loaded,2);
    else, roller_mask = loaded; end
    if ~isequaln(reshape(saved_roller_mask,[],1),reshape(roller_mask,[],1))
        static_inconsistent('Saved roller active set disagrees with the formal slice active set.');
    end
    k = static_state.(k_field);
    expected_k = zeros(size(delta));
    if any(loaded(:)), expected_k(loaded) = exponent*Q(loaded)./delta(loaded); end
    if ~same_numeric(k,expected_k,1e-10)
        static_inconsistent('Saved Stage D contact stiffness violates the formal Q/delta identity.');
    end
    source = struct('contact_state_path',contact_path, ...
        'contact_state_mode','STAGE_D_EXTRACTED_STATIC_CONTACT_LINEARIZATION', ...
        'loaded_mask_path',[contact_path '.film.loaded_mask + ' contact_path '.raw_contact.loaded'], ...
        'loaded_mask_mode','STAGE_D_FORMAL_FILM_AND_RAW_CONTACT_SLICE_AGREEMENT', ...
        'contact_stiffness_path',['results.static.' tf '.' k_field], ...
        'contact_stiffness_mode','STAGE_D_EXTRACTED_CONTACT_STIFFNESS');
end
if strcmp(bearing,'front')
    Q = Q(:);
    delta = delta(:);
    loaded = loaded(:);
    k = k(:);
end
end

function [J,A,geometry,kind,element_count,slice_count] = canonical_contact_geometry(contact,bearing)
theta = contact.theta(:);
if strcmp(bearing,'front')
    kind = 'ball'; element_count = numel(theta); slice_count = 1;
    if ~isequal(numel(contact.Q),element_count) || numel(contact.r) ~= 5
        mapping_not_available('Front formal contact geometry has invalid dimensions.');
    end
    r = contact.r(:); raw = contact.delta_raw(:);
    variation = r(5)*cos(theta)-r(4)*sin(theta);
    target = raw-r(1)*cos(theta)-r(2)*sin(theta);
    design = [ones(element_count,1) variation];
    if rank(design) < 2
        mapping_not_available('Front axial lever cannot be recovered from the formal contact identity.');
    end
    coefficients = design\target; lever = coefficients(2);
    identity_error = norm(design*coefficients-target)/max(norm(target),eps);
    if ~isfinite(lever) || lever <= 0 || identity_error > 1e-10
        mapping_not_available('Front formal contact identity failed geometry recovery.');
    end
    J = [cos(theta) sin(theta) zeros(element_count,1) ...
        -lever*sin(theta) lever*cos(theta)];
    A = cos(contact.contact_angle)*J.';
    geometry = struct('theta_rad',theta,'slice_z_m',0, ...
        'contact_angle_rad',contact.contact_angle,'axial_lever_m',lever, ...
        'local_dof_order',{{'ux','uy','uz','theta_x','theta_y'}}, ...
        'geometry_identity_relative_error',identity_error, ...
        'source','FORMAL_NONLINEAR_BEARING_FORCE_CONTACT_IDENTITY');
else
    kind = 'roller'; element_count = numel(theta); slice_count = size(contact.Q,2);
    if element_count ~= 30 || slice_count ~= 9 || ...
            ~isequal(size(contact.Q),[element_count slice_count]) || ...
            ~isfield(contact,'slice_z') || numel(contact.slice_z) ~= slice_count
        mapping_not_available('Rear formal 30-by-9 slice geometry is unavailable.');
    end
    slice_z = reshape(contact.slice_z,1,[]); J = zeros(numel(contact.Q),5);
    for slice_index = 1:slice_count
        rows = (1:element_count)+(slice_index-1)*element_count;
        z = slice_z(slice_index);
        J(rows,:) = [cos(theta) sin(theta) zeros(element_count,1) ...
            -z*sin(theta) z*cos(theta)];
    end
    A = J.';
    geometry = struct('theta_rad',theta,'slice_z_m',slice_z, ...
        'contact_angle_rad',0,'axial_lever_m',0, ...
        'local_dof_order',{{'ux','uy','uz','theta_x','theta_y'}}, ...
        'source','FORMAL_NONLINEAR_BEARING_FORCE_SLICE_GEOMETRY');
end
end

function mapping = finish_mapping(mapping)
n = mapping.element_count*mapping.slice_count;
if ~isscalar(mapping.element_count) || ~isscalar(mapping.slice_count) || ...
        mapping.element_count < 1 || mapping.slice_count < 1 || ...
        size(mapping.interface_transform,1) ~= 5 || ...
        ~isequal(size(mapping.contact_jacobian_local),[n 5]) || ...
        ~isequal(size(mapping.force_assembly_local),[5 n]) || ...
        ~isequal(size(mapping.K_b_local),[5 5]) || ...
        any(~isfinite(mapping.interface_transform),'all') || ...
        any(~isfinite(mapping.contact_jacobian_local),'all') || ...
        any(~isfinite(mapping.force_assembly_local),'all') || ...
        any(~isfinite(mapping.K_b_local),'all')
    mapping_not_available('The formal five-DOF map has invalid dimensions or values.');
end
mapping.local_dof_order = {'ux','uy','uz','theta_x','theta_y'};
if mapping.slice_count == 1
    mapping.loaded_mask_static_roller = reshape(mapping.loaded_mask_static_slice,[],1);
else
    mapping.loaded_mask_static_roller = any(mapping.loaded_mask_static_slice,2);
end
mapping.K_b_local_analytic = mapping.force_assembly_local* ...
    diag(mapping.k_static_slice(:))*mapping.contact_jacobian_local;
error_value = relative_error(mapping.K_b_local_analytic,mapping.K_b_local);
mapping.tangent_audit = struct( ...
    'analytic_vs_saved_relative_error',error_value, ...
    'analytic_vs_saved_threshold',1e-8, ...
    'status','ANALYTIC_VS_FD_TANGENT_AUDIT_PASSED', ...
    'analytic_definition','A_TIMES_DIAG_K_TIMES_J', ...
    'saved_tangent_source','ACCEPTED_STAGE_D_FINITE_DIFFERENCE_SYMMETRIC_K_LOCAL');
if ~isfinite(error_value) || error_value > 1e-8
    error('StageF:AnalyticVsFDTangentAuditFailed', ...
        'ANALYTIC_VS_FD_TANGENT_AUDIT_FAILED: analytic and saved local tangents disagree.');
end
end

function validate_static_contact_state(mapping,require_law)
Q = mapping.Q_static_slice; delta = mapping.delta_static_slice;
k = mapping.k_static_slice; loaded = logical(mapping.loaded_mask_static_slice);
expected_size = [mapping.element_count mapping.slice_count];
if mapping.slice_count == 1, expected_size = [mapping.element_count 1]; end
if ~isequal(size(Q),expected_size) || ...
        ~isequal(size(Q),size(delta),size(k),size(loaded)) || ...
        any(~isfinite(Q),'all') || any(~isfinite(delta),'all') || ...
        any(~isfinite(k),'all') || any(Q(:) < 0) || any(delta(:) < 0) || any(k(:) < 0) || ...
        any(Q(loaded) <= 0) || any(delta(loaded) <= 0) || any(k(loaded) <= 0) || ...
        any(Q(~loaded) ~= 0) || any(delta(~loaded) ~= 0) || any(k(~loaded) ~= 0)
    static_inconsistent('Static Q, delta, k, or active-set values are inconsistent.');
end
exponent = mapping.formal_contact_law.exponent;
expected_k = zeros(size(k));
expected_k(loaded) = exponent*Q(loaded)./delta(loaded);
if ~same_numeric(k,expected_k,1e-10)
    static_inconsistent('The formal contact derivative identity is inconsistent.');
end
if require_law
    coefficient = mapping.formal_contact_law.coefficient;
    expected_Q = zeros(size(Q)); expected_Q(loaded) = coefficient*delta(loaded).^exponent;
    if ~same_numeric(Q,expected_Q,1e-10)
        static_inconsistent('The stored static contact load violates its formal contact law.');
    end
end
end

function pass = formal_provenance_valid(p)
required = {'schema','accepted_stage_d_commit','accepted_stage_e_commit', ...
    'contact_state_path','interface_transform_path','contact_kernel_file', ...
    'contact_kernel_sha256','static_extractor_file','static_extractor_sha256', ...
    'interface_mapping_file','interface_mapping_sha256','verified'};
pass = isstruct(p) && all(isfield(p,required)) && ...
    strcmp(p.schema,'STAGE_F_FORMAL_5DOF_MAPPING_PROVENANCE_V1') && ...
    strcmp(p.accepted_stage_d_commit,'23a975c2c762504dc4ae62f07379737582fd783f') && ...
    strcmp(p.accepted_stage_e_commit,'0cab3dc49dfffc4192066402cb70302f084cb45d') && ...
    strcmp(p.contact_kernel_sha256,'d82ae8cc92a1f1fb55d9d0c14da3efa196e9f085ce22abc5cdd2b345f93af5c8') && ...
    strcmp(p.static_extractor_sha256,'94ca056ad4b7f867851f7698f1241e9f85d55a011d904ba2620fa30395387661') && ...
    strcmp(p.interface_mapping_sha256,'c74a92064886aa66e46a9a7b97ece787e4e4603ea198ab2814ad1450c7461b5b') && ...
    isequal(p.verified,true);
end

function coefficient = loaded_law_coefficient(Q,delta,loaded,exponent)
values = Q(loaded)./delta(loaded).^exponent;
if isempty(values), coefficient = NaN; else, coefficient = mean(values); end
end

function pass = same_numeric(actual,expected,threshold)
pass = isnumeric(actual) && isnumeric(expected) && ...
    isequal(size(actual),size(expected)) && all(isfinite(actual),'all') && ...
    all(isfinite(expected),'all') && relative_error(actual,expected) <= threshold;
end

function value = relative_error(actual,expected)
value = norm(actual(:)-expected(:))/max(norm(expected(:)),eps);
end

function mapping_not_available(detail)
error('StageF:RollingElementLinearizationMappingNotAvailable', ...
    'ROLLING_ELEMENT_LINEARIZATION_MAPPING_NOT_AVAILABLE: %s',detail);
end

function static_inconsistent(detail)
error('StageF:StaticContactLinearizationStateInconsistent', ...
    'STATIC_CONTACT_LINEARIZATION_STATE_INCONSISTENT: %s',detail);
end
