function mapping = build_stage_e_observation_mapping(static_T20,configuration,force_dofs)
%BUILD_STAGE_E_OBSERVATION_MAPPING Validate formal Stage E response mappings.

if ~isstruct(static_T20) || ~all(isfield(static_T20, ...
        {'observation_mapping','bearing_mapping','dof_mapping'})) || ...
        ~isstruct(configuration)
    error('StageE:ObservationMapping','The accepted T20 mapping is incomplete.');
end
n = static_T20.dof_mapping.model_dof_count;
observation = static_T20.observation_mapping;
bearings = static_T20.bearing_mapping;
if ~isscalar(n) || n ~= 192 || ~isfield(observation,'validated') || ...
        ~isequal(observation.validated,true) || ...
        ~isfield(observation,'dof_indices') || ...
        ~isequal(size(observation.dof_indices(:)),[8 1]) || ...
        ~isfield(bearings,'validated') || ~isequal(bearings.validated,true) || ...
        ~all(isfield(bearings,{'front_B','rear_B'})) || ...
        ~isequal(size(bearings.front_B),[5 n]) || ...
        ~isequal(size(bearings.rear_B),[5 n])
    error('StageE:ObservationMapping','The accepted Stage C mapping failed validation.');
end
indices = reshape(observation.dof_indices,1,[]);
force_dofs = reshape(force_dofs,1,[]);
if numel(force_dofs) ~= 2
    error('StageE:ObservationMapping','The formal force must support two radial DOFs.');
end
actual_node = (force_dofs(1)+5)/6;
if any(indices ~= floor(indices)) || any(indices < 1 | indices > n) || ...
        numel(unique(indices)) ~= 8 || ...
        any(force_dofs ~= floor(force_dofs)) || ...
        any(force_dofs < 1 | force_dofs > n) || ...
        numel(unique(force_dofs)) ~= 2 || actual_node ~= floor(actual_node) || ...
        ~isequal(force_dofs,6*actual_node+[-5 -4]) || actual_node ~= 16 || ...
        ~isfield(configuration,'unbalance') || ...
        ~isfield(configuration.unbalance,'rotor_node') || ...
        configuration.unbalance.rotor_node ~= actual_node
    error('StageE:ObservationMapping','Observation or force DOFs are invalid.');
end

mapping = struct();
mapping.rotor = struct('R2',indices(1:2),'R10',indices(3:4), ...
    'R16',force_dofs);
mapping.casing = struct('C2',indices(5:6),'C8',indices(7:8));
mapping.front_relative_transform = full(bearings.front_B(1:2,:));
mapping.rear_relative_transform = full(bearings.rear_B(1:2,:));
mapping.force_nonzero_dofs = force_dofs;
mapping.model_dof_count = n;
mapping.frequency_1X_Hz = configuration.frequency_1X_Hz;
mapping.requested_label = sprintf('R%d',configuration.unbalance.rotor_node);
mapping.actual_node = actual_node;
mapping.actual_global_dofs = force_dofs;
mapping.mapping_validation_required = true;
mapping.validated = transforms_match_points(mapping,n);
mapping.mapping_source = 'ACCEPTED_STAGE_C_MAPPING_AND_ACTUAL_UNBALANCE_FORCE_SUPPORT';
mapping.source = mapping.mapping_source;
if ~mapping.validated
    error('StageE:ObservationMapping','Bearing transforms do not match mapped points.');
end
end

function pass = transforms_match_points(mapping,n)
front_expected = sparse(1:2,mapping.rotor.R2,1,2,n) - ...
    sparse(1:2,mapping.casing.C2,1,2,n);
rear_expected = sparse(1:2,mapping.rotor.R10,1,2,n) - ...
    sparse(1:2,mapping.casing.C8,1,2,n);
pass = isequal(mapping.front_relative_transform,full(front_expected)) && ...
    isequal(mapping.rear_relative_transform,full(rear_expected));
end
