function harmonics = compute_stage_f_bearing_force_harmonics(force_history,phase_values_rad)
%COMPUTE_STAGE_F_BEARING_FORCE_HARMONICS Audit bearing-force 1X--3X terms.

if ~isnumeric(force_history) || isempty(force_history) || ...
        ~isnumeric(phase_values_rad) || ~isvector(phase_values_rad) || ...
        size(force_history,2) ~= numel(phase_values_rad) || ...
        any(~isfinite(force_history),'all') || any(~isfinite(phase_values_rad))
    error('StageF:HarmonicInput','STAGE_F_COMPUTATION_FAILED: invalid harmonic input.');
end
theta = reshape(phase_values_rad,1,[]); N = numel(theta);
if N ~= 32 || max(abs(theta-2*pi*(0:31)/32)) > 100*eps(2*pi)
    error('StageF:HarmonicPhaseGrid', ...
        'STAGE_F_COMPUTATION_FAILED: Stage F harmonic projection requires the formal 32-phase grid.');
end
F1 = project(force_history,theta,1,N);
F2 = project(force_history,theta,2,N);
F3 = project(force_history,theta,3,N);
norm1 = norm(F1,2); norm2 = norm(F2,2); norm3 = norm(F3,2);
harmonics = struct('F1_complex',F1,'F2_complex',F2,'F3_complex',F3, ...
    'F1_norm',norm1,'F2_norm',norm2,'F3_norm',norm3, ...
    'F1_phase_rad',angle(F1),'F2_phase_rad',angle(F2), ...
    'F3_phase_rad',angle(F3), ...
    'F1_force_semantics','FORCE_ON_ROTOR_MINUS_AQ', ...
    'F2_force_semantics','FORCE_ON_ROTOR_MINUS_AQ', ...
    'F3_force_semantics','FORCE_ON_ROTOR_MINUS_AQ', ...
    'H2_H1',norm2/max(norm1,eps),'H3_H1',norm3/max(norm1,eps), ...
    'diagnostic_label','BEARING_NONLINEAR_FORCE_HARMONIC_DIAGNOSTICS');
end

function coefficient = project(history,theta,order,N)
coefficient = (2/N)*history*exp(-1i*order*theta).';
end
