function record = empty_thermal_case_record(cfg)
%EMPTY_THERMAL_CASE_RECORD Fixed schema for one formal thermal operating case.

if nargin ~= 1 || ~isstruct(cfg), error('Stage9A:CaseSchemaConfig', 'empty_thermal_case_record requires the Stage9A configuration.'); end
thermal_bearing = struct('T_final_C', NaN, 'T_film_C', NaN, 'T_inner_C', NaN, 'T_outer_C', NaN, ...
    'T_element_C', NaN, 'viscosity_Pa_s', NaN, 'pressure_viscosity_Pa_inv', NaN, 'working_clearance_m', NaN, ...
    'clearance_change_m', NaN, 'thermal_preload', NaN, 'friction_power_W', NaN, 'minimum_loaded_film_m', NaN);
bearing_schema = struct('K_local', nan(5), 'C_ehl_local', nan(5), 'active_dof_indices', zeros(1,5), ...
    'stiffness_eigenvalues', nan(1,5), 'damping_eigenvalues', nan(1,5), 'radial_Kxx_N_m', NaN, ...
    'radial_Kyy_N_m', NaN, 'radial_Cxx_Ns_m', NaN, 'radial_Cyy_Ns_m', NaN, 'stiffness_anisotropy', NaN, ...
    'damping_anisotropy', NaN, 'stiffness_pass', false, 'damping_pass', false);
record = struct();
record.meta = struct('case_index', NaN, 'T_oil_C', NaN, 'status', "pending", 'started_at', NaT, ...
    'completed_at', NaT, 'elapsed_s', NaN, 'source_commit', "", 'config_signature', "");
record.initialization = struct('continuation_used', false, 'continued_from_temperature_C', NaN, ...
    'cold_start_fallback_used', false, 'q0_source', "", 'thermal_state_source', "", 'modal_full_fallback_used', false);
record.convergence = struct('outer_iterations', 0, 'temperature_residual_C', NaN, 'power_residual_W', NaN, ...
    'mechanical_residual', NaN, 'axial_constraint_error_m', NaN, 'relative_Q_change', NaN, 'relative_film_change', NaN, ...
    'final_consistency_recompute_count', 0, 'pass', false, 'iteration_index', zeros(0,1), ...
    'ball_temperature_C', zeros(0,1), 'roller_temperature_C', zeros(0,1), ...
    'temperature_residual_history_C', zeros(0,1), 'power_residual_history_W', zeros(0,1), 'mechanical_residual_history', zeros(0,1));
record.thermal = struct('ball', thermal_bearing, 'roller', thermal_bearing);
record.contact = struct('ball', contact_schema(22), 'roller', contact_schema(30));
record.bearing = struct('ball', bearing_schema, 'roller', bearing_schema);
record.linearization = struct('requested_amplitude_m', NaN, 'used_amplitude_m', NaN, 'fallback_used', false, ...
    'ball_error_plus', NaN, 'ball_error_minus', NaN, 'roller_error_plus', NaN, 'roller_error_minus', NaN, ...
    'ball_loaded_set_stable', false, 'roller_loaded_set_stable', false, 'pass', false);
record.modal = struct('strategy_used', "", 'full_modal_fallback_used', false, 'reference_subspace_count', 0, ...
    'retained_mode_count', 0, 'tracked_mode_count', cfg.modal.tracked_mode_count, 'reference_frequency_Hz', nan(1,6), ...
    'tracked_frequency_Hz', nan(1,6), 'frequency_shift_percent', nan(1,6), 'MAC_diagonal', nan(1,6), ...
    'minimum_MAC', NaN, 'cluster_tracking_used', false, 'effective_mass_x', NaN, 'effective_mass_y', NaN, ...
    'mass_orthogonality_error', NaN, 'stiffness_diagonalization_error', NaN, 'frequency_consistency_error', NaN, ...
    'frequency_consistency_tolerance', NaN, 'maximum_ritz_backward_error', NaN, 'maximum_state_real_part', NaN, ...
    'tracking_pass', false, 'pass', false);
record.dynamics = struct('used_amplitude_m', NaN, 'dt_s', NaN, 'internal_step_count', 0, 'output_stride', 0, ...
    'saved_step_count', 0, 'end_time_s', NaN, 'maximum_state_real_part', NaN, 'maximum_energy_growth_ratio', NaN, ...
    'initial_energy_J', NaN, 'final_energy_J', NaN, 'factorization_count', 0, 'pass', false);
record.response = struct('time_s', zeros(0,1), 'saved_internal_step_index', zeros(0,1), 'uniform_sample_dt_s', NaN, ...
    'node_labels', cfg.output.node_labels, 'component_labels', cfg.output.component_labels, 'displacement_m', zeros(0,10), ...
    'velocity_m_s', zeros(0,10), 'acceleration_m_s2', zeros(0,10), 'fft_valid_sample_count', 0);
record.paper_metrics = paper_metrics_schema();
record.runtime = struct('thermal_outer_loop_s', NaN, 'bearing_stiffness_s', NaN, 'ehl_damping_s', NaN, ...
    'linearization_s', NaN, 'modal_reduction_s', NaN, 'free_decay_s', NaN, 'postprocess_s', NaN, ...
    'checkpoint_s', NaN, 'total_case_s', NaN);
record.audit = struct('bearing_force_call_count', 0, 'thermal_update_count', 0, 'stiffness_difference_call_count', 0, ...
    'newmark_force_call_count', 0, 'newmark_thermal_update_count', 0, 'newmark_factorization_count', 0, ...
    'full_modal_solve_count', 0, 'checkpoint_write_count', 0);
record.resume_state = struct('valid', false, 'q_static', zeros(0,1), 'ball_T_final_C', NaN, 'roller_T_final_C', NaN, ...
    'ball_Q', zeros(0,0), 'roller_Q', zeros(0,0), 'ball_film', zeros(0,0), 'roller_film', zeros(0,0), ...
    'ball_loaded_mask', false(0,0), 'roller_loaded_mask', false(0,0));
record.warnings = strings(0,1);
record.error = struct('identifier', "", 'message', "", 'function_name', "", 'temperature_C', NaN, ...
    'outer_iteration', NaN, 'mechanical_load_step', NaN, 'newton_iteration', NaN);
end

function contact = contact_schema(body_count)
contact = struct('body_load_N', zeros(1,body_count), 'loaded_mask', false(1,body_count), 'loaded_contact_count', 0, ...
    'total_contact_load_N', 0, 'maximum_contact_load_N', 0, 'load_nonuniformity', NaN, 'maximum_load_body_index', NaN);
end

function metrics = paper_metrics_schema()
metrics = struct('peak_displacement_m', nan(5,2), 'peak_to_peak_displacement_m', nan(5,2), ...
    'rms_displacement_m', nan(5,2), 'peak_velocity_m_s', nan(5,2), 'rms_velocity_m_s', nan(5,2), ...
    'peak_acceleration_m_s2', nan(5,2), 'rms_acceleration_m_s2', nan(5,2), 'dominant_frequency_Hz', nan(5,2), ...
    'logarithmic_decrement', nan(5,2), 'identified_damping_ratio', nan(5,2), ...
    'front_casing_rotor_peak_ratio', NaN, 'rear_casing_rotor_peak_ratio', NaN, ...
    'front_casing_rotor_rms_ratio', NaN, 'rear_casing_rotor_rms_ratio', NaN);
end
