function result = evaluate_stage_f_representative_nonlinear_case(request,evaluator)
%EVALUATE_STAGE_F_REPRESENTATIVE_NONLINEAR_CASE Frozen 32-phase bearing case.

required = {'scenario','phase_count','q_static','qhat_full', ...
    'linear_force_hat','loaded_mask_static','force_semantics'};
if ~isstruct(request) || ~all(isfield(request,required)) || ...
        ~strcmp(request.scenario,'NOMINAL') || request.phase_count ~= 32 || ...
        ~isa(evaluator,'function_handle') || ...
        ~strcmp(request.force_semantics,'FORCE_ON_ROTOR_MINUS_AQ')
    error('StageFRepresentative:InvalidRequest', ...
        'REPRESENTATIVE_NONLINEAR_VALIDATION_FAILED: invalid frozen request.');
end
q_static = request.q_static(:); qhat = request.qhat_full(:);
linear_force_hat = request.linear_force_hat(:);
loaded_static = logical(request.loaded_mask_static(:));
if numel(q_static) ~= numel(qhat) || ...
        any(~isfinite(q_static)) || any(~isfinite(real(qhat))) || ...
        any(~isfinite(imag(qhat))) || ...
        any(~isfinite(real(linear_force_hat))) || ...
        any(~isfinite(imag(linear_force_hat)))
    error('StageFRepresentative:InvalidRequest', ...
        'REPRESENTATIVE_NONLINEAR_VALIDATION_FAILED: invalid frozen vectors.');
end

[static_force,static_loaded,static_Q] = evaluator(q_static);
static_force = static_force(:); static_loaded = logical(static_loaded(:));
static_Q = static_Q(:);
if numel(static_force) ~= numel(linear_force_hat) || ...
        numel(static_loaded) ~= numel(loaded_static) || ...
        numel(static_Q) ~= numel(loaded_static) || ...
        ~isequal(static_loaded,loaded_static) || ...
        any(~isfinite(static_force)) || any(~isfinite(static_Q))
    error('StageFRepresentative:StaticReferenceMismatch', ...
        'REPRESENTATIVE_NONLINEAR_VALIDATION_FAILED: static reference mismatch.');
end

theta = 2*pi*(0:31)/32;
force_count = numel(static_force); contact_count = numel(loaded_static);
F_exact = zeros(force_count,32); loaded_history = false(contact_count,32);
Q_history = zeros(contact_count,32);
for phase_index = 1:32
    q_phase = q_static+real(qhat*exp(1i*theta(phase_index)));
    [force,loaded,Q] = evaluator(q_phase);
    force = force(:); loaded = logical(loaded(:)); Q = Q(:);
    if numel(force) ~= force_count || numel(loaded) ~= contact_count || ...
            numel(Q) ~= contact_count || any(~isfinite(force)) || ...
            any(~isfinite(Q))
        error('StageFRepresentative:EvaluationFailed', ...
            'REPRESENTATIVE_NONLINEAR_VALIDATION_FAILED: invalid phase result.');
    end
    F_exact(:,phase_index) = force;
    loaded_history(:,phase_index) = loaded;
    Q_history(:,phase_index) = Q;
end

linear_dynamic = real(linear_force_hat*exp(1i*theta));
F_linear = static_force+linear_dynamic;
exact_dynamic = F_exact-static_force;
numerator = history_rms_norm(exact_dynamic-linear_dynamic);
denominator = history_rms_norm(exact_dynamic);
if numerator == 0 && denominator == 0
    epsilon_NL = 0;
else
    epsilon_NL = numerator/max(denominator,eps);
end
Q_min = min(Q_history,[],2);
active_changed = any(loaded_history ~= loaded_static,'all');
contact_loss = any(loaded_static & Q_min <= 0);
harmonics = compute_harmonics(exact_dynamic,theta);

result = struct('phase_count',32,'phase_values_rad',theta, ...
    'F_exact',F_exact,'F_linear',F_linear, ...
    'static_force_reference',static_force, ...
    'linear_force_hat',linear_force_hat, ...
    'force_semantics','FORCE_ON_ROTOR_MINUS_AQ', ...
    'epsilon_NL',epsilon_NL, ...
    'loaded_mask_static',loaded_static, ...
    'loaded_mask_history',loaded_history, ...
    'active_set_changed',active_changed, ...
    'Q_min',Q_min,'minimum_loaded_Q',minimum_loaded(Q_min,loaded_static), ...
    'contact_loss_detected',contact_loss, ...
    'force_history_sha256',serialized_sha256(F_exact), ...
    'active_history_sha256',serialized_sha256(loaded_history), ...
    'Q_min_sha256',serialized_sha256(Q_min), ...
    'F1_complex',harmonics.F1_complex, ...
    'F2_complex',harmonics.F2_complex, ...
    'F3_complex',harmonics.F3_complex, ...
    'H2_H1',harmonics.H2_H1,'H3_H1',harmonics.H3_H1);
end

function harmonics = compute_harmonics(history,theta)
n = numel(theta);
F1 = (2/n)*history*exp(-1i*theta).';
F2 = (2/n)*history*exp(-2i*theta).';
F3 = (2/n)*history*exp(-3i*theta).';
norm1 = norm(F1,2);
harmonics = struct('F1_complex',F1,'F2_complex',F2,'F3_complex',F3, ...
    'H2_H1',norm(F2,2)/max(norm1,eps), ...
    'H3_H1',norm(F3,2)/max(norm1,eps));
end

function value = history_rms_norm(history)
value = sqrt(mean(sum(abs(history).^2,1)));
end

function value = minimum_loaded(Q_min,loaded)
values = Q_min(loaded);
if isempty(values), value = NaN; else, value = min(values); end
end


function hash = serialized_sha256(value)
bytes = getByteStreamFromArray(value);
engine = java.security.MessageDigest.getInstance('SHA-256');
engine.update(typecast(uint8(bytes),'int8'));
digest = typecast(engine.digest(),'uint8');
hash = lower(reshape(dec2hex(digest,2).',1,[]));
end
