function scan = evaluate_stage_f_nonlinear_bearing_force_scan(request,evaluator)
%EVALUATE_STAGE_F_NONLINEAR_BEARING_FORCE_SCAN Frozen 32-phase force scan.

formal = isstruct(evaluator);
if formal
    validate_formal_evaluator(evaluator);
elseif ~isa(evaluator,'function_handle')
    error('StageF:NonlinearEvaluator','STAGE_F_COMPUTATION_FAILED: evaluator is invalid.');
end
if ~isstruct(request) || ~isfield(request,'scenario') || ...
        ~strcmp(request.scenario,'NOMINAL')
    error('StageF:NonNominalNonlinearScan', ...
        'Exact nonlinear force scans are permitted for NOMINAL only.');
end
if ~isfield(request,'phase_count') || ~isequal(request.phase_count,32)
    error('StageF:PhaseCount','The formal Stage F nonlinear scan requires exactly 32 phases.');
end
base_required = {'q_static','qhat_full'};
if ~all(isfield(request,base_required))
    error('StageF:ScanRequestIncomplete', ...
        'STAGE_F_COMPUTATION_FAILED: nonlinear scan request is incomplete.');
end
q_static = request.q_static(:); qhat = request.qhat_full(:);
if numel(q_static) ~= numel(qhat) || any(~isfinite(q_static)) || ...
        any(~isfinite(real(qhat))) || any(~isfinite(imag(qhat)))
    error('StageF:ScanRequestIncomplete', ...
        'STAGE_F_COMPUTATION_FAILED: nonlinear scan state vectors are invalid.');
end
if formal
    validate_formal_request(request,evaluator);
    mapping = request.mapping_snapshot;
    loaded_static = logical(mapping.loaded_mask_static_slice(:));
    linear_force_hat = -(mapping.K_b_local_analytic* ...
        (mapping.interface_transform*qhat));
    evaluation = @(q) formal_evaluation(q,request,evaluator);
else
    if ~all(isfield(request,{'linear_force_hat','loaded_mask_static_slice'}))
        error('StageF:ScanRequestIncomplete', ...
            'STAGE_F_COMPUTATION_FAILED: synthetic scan request is incomplete.');
    end
    declared_linear_force_hat = request.linear_force_hat(:);
    linear_force_hat = [];
    loaded_static = logical(request.loaded_mask_static_slice(:));
    evaluation = @(q) synthetic_evaluation(q,evaluator);
end

[static_force,static_loaded] = evaluation(q_static);
static_force = static_force(:); static_loaded = logical(static_loaded(:));
if ~formal
    if any(~isfinite(real(declared_linear_force_hat))) || ...
            any(~isfinite(imag(declared_linear_force_hat)))
        error('StageF:ScanRequestIncomplete', ...
            'STAGE_F_COMPUTATION_FAILED: declared synthetic linear force is invalid.');
    end
    linear_force_hat = independent_synthetic_tangent( ...
        q_static,qhat,evaluation,static_force);
end
if numel(static_loaded) ~= numel(loaded_static) || ...
        numel(linear_force_hat) ~= numel(static_force) || ...
        any(~isfinite(static_force)) || ~isequal(static_loaded,loaded_static)
    error('StageF:NonlinearForceStaticReferenceMismatch', ...
        'NONLINEAR_FORCE_STATIC_REFERENCE_MISMATCH: frozen static force or active set is inconsistent.');
end
static_reference_error = 0;
if formal && isfield(request,'contact_state_snapshot')
    contact = request.contact_state_snapshot;
    if isfield(contact,'raw_contact') && isfield(contact.raw_contact,'f5')
        expected_static_force = contact.raw_contact.f5(:);
    elseif all(isfield(contact,{'Fx','Fy','Fz','Mx','My'}))
        expected_static_force = [contact.Fx;contact.Fy;contact.Fz;contact.Mx;contact.My];
    else
        expected_static_force = [];
    end
    static_reference_error = relative_error(static_force,expected_static_force);
    if isempty(expected_static_force) || static_reference_error > 1e-10
        error('StageF:NonlinearForceStaticReferenceMismatch', ...
            'NONLINEAR_FORCE_STATIC_REFERENCE_MISMATCH: formal static force baseline disagrees with Stage D.');
    end
end

theta = 2*pi*(0:31)/32;
force_dimension = numel(static_force); contact_count = numel(loaded_static);
exact_force_history = zeros(force_dimension,32);
exact_dynamic_history = zeros(force_dimension,32);
linear_dynamic_history = zeros(force_dimension,32);
active_history = false(contact_count,32);
first_change = struct([]);
for phase_index = 1:32
    q_phase = q_static+real(qhat*exp(1i*theta(phase_index)));
    [force_phase,loaded_phase] = evaluation(q_phase);
    force_phase = force_phase(:); loaded_phase = logical(loaded_phase(:));
    if numel(force_phase) ~= force_dimension || numel(loaded_phase) ~= contact_count || ...
            any(~isfinite(force_phase))
        error('StageF:NonlinearForceEvaluation', ...
            'STAGE_F_COMPUTATION_FAILED: nonlinear evaluator returned invalid data.');
    end
    exact_force_history(:,phase_index) = force_phase;
    exact_dynamic_history(:,phase_index) = force_phase-static_force;
    linear_dynamic_history(:,phase_index) = ...
        real(linear_force_hat*exp(1i*theta(phase_index)));
    active_history(:,phase_index) = loaded_phase;
    changed = find(loaded_phase ~= loaded_static);
    if isempty(first_change) && ~isempty(changed)
        first_change = struct('phase_index',phase_index, ...
            'phase_rad',theta(phase_index),'slice_indices',reshape(changed,1,[]), ...
            'static_mask',loaded_static,'phase_mask',loaded_phase);
    end
end
numerator = history_rms_norm(exact_dynamic_history-linear_dynamic_history);
denominator = history_rms_norm(exact_dynamic_history);
if numerator == 0 && denominator == 0
    epsilon_NL = 0;
else
    epsilon_NL = numerator/max(denominator,eps);
end
active_changed = any(active_history ~= loaded_static, 'all');
if active_changed || epsilon_NL > 0.10
    status = 'REPRESENTATIVE_NONLINEAR_VALIDATION_REQUIRED';
elseif epsilon_NL <= 0.05
    status = 'FREQUENCY_DOMAIN_LINEARIZATION_ACCEPTED';
else
    status = 'FREQUENCY_DOMAIN_LINEARIZATION_CAUTION';
end
scan = struct('scenario','NOMINAL','phase_count',32, ...
    'phase_values_rad',theta,'loaded_mask_static_slice',loaded_static, ...
    'active_set_history',active_history,'active_set_changed',active_changed, ...
    'first_active_set_change',first_change, ...
    'static_force_reference',static_force, ...
    'static_reference_relative_error',static_reference_error, ...
    'exact_force_history',exact_force_history, ...
    'exact_dynamic_force_history',exact_dynamic_history, ...
    'linear_force_hat',linear_force_hat, ...
    'linear_dynamic_force_history',linear_dynamic_history, ...
    'epsilon_NL',epsilon_NL,'gate_status',status, ...
    'thermal_state_frozen',formal && request.thermal_state_frozen);
end

function validate_formal_evaluator(evaluator)
required = {'function_handle','function_name','source_file','source_sha256', ...
    'formal_static_geometry_source','frozen_thermal_state', ...
    'thermal_state_source','stage_d_source_commit','stage_e_source_commit', ...
    'thermal_state_frozen','thermal_update_allowed','canonical_write_allowed'};
valid = all(isfield(evaluator,required)) && ...
    isa(evaluator.function_handle,'function_handle') && ...
    strcmp(func2str(evaluator.function_handle),'nonlinear_bearing_force') && ...
    strcmp(evaluator.function_name,'nonlinear_bearing_force') && ...
    strcmp(evaluator.source_sha256,'d82ae8cc92a1f1fb55d9d0c14da3efa196e9f085ce22abc5cdd2b345f93af5c8') && ...
    isfile(evaluator.source_file) && ...
    strcmp(file_sha256(evaluator.source_file),evaluator.source_sha256) && ...
    strcmp(evaluator.formal_static_geometry_source, ...
        'nonlinear_bearing_force/stage4a_bearing_force') && ...
    strcmp(evaluator.stage_d_source_commit,'23a975c2c762504dc4ae62f07379737582fd783f') && ...
    strcmp(evaluator.stage_e_source_commit,'0cab3dc49dfffc4192066402cb70302f084cb45d') && ...
    isequal(evaluator.thermal_state_frozen,true) && ...
    isequal(evaluator.thermal_update_allowed,false) && ...
    isequal(evaluator.canonical_write_allowed,false);
if ~valid
    error('StageF:NonlinearEvaluatorProvenance', ...
        'NONLINEAR_FORCE_EVALUATOR_PROVENANCE_INVALID: exact formal kernel provenance is required.');
end
end

function validate_formal_request(request,evaluator)
required = {'evaluation_mode','temperature_case_C','bearing', ...
    'mapping_snapshot','frozen_thermal_state','contact_state_snapshot', ...
    'static_state_source','response_source','thermal_state_source', ...
    'canonical_sha256','thermal_state_frozen','thermal_update_allowed', ...
    'static_resolve_allowed','frequency_resolve_allowed','formal_parameters', ...
    'bearing_index'};
if ~all(isfield(request,required)) || ...
        ~strcmp(request.evaluation_mode,'FORMAL_FROZEN_NONLINEAR_BEARING_FORCE') || ...
        ~strcmp(request.canonical_sha256, ...
        '3f0e6e3b379cda670ef173682c58d17a19fc6b30f761ed59a00f3c203793abfd') || ...
        ~isequal(request.thermal_state_frozen,true) || ...
        ~isequal(request.thermal_update_allowed,false) || ...
        ~isequal(request.static_resolve_allowed,false) || ...
        ~isequal(request.frequency_resolve_allowed,false) || ...
        ~isequaln(request.frozen_thermal_state,evaluator.frozen_thermal_state) || ...
        ~strcmp(request.thermal_state_source,evaluator.thermal_state_source) || ...
        ~isstruct(request.mapping_snapshot) || ~isstruct(request.formal_parameters) || ...
        ~isscalar(request.bearing_index) || ~any(request.bearing_index == [1 2])
    error('StageF:ScanRequestIncomplete', ...
        'STAGE_F_COMPUTATION_FAILED: formal frozen-force scan request is incomplete.');
end
validate_formal_frozen_parameters(request,evaluator);
end

function validate_formal_frozen_parameters(request,evaluator)
parameters = request.formal_parameters;
valid = isfield(parameters,'microphysics') && ...
    isstruct(parameters.microphysics) && ...
    isfield(parameters.microphysics,'thermal') && ...
    isstruct(parameters.microphysics.thermal) && ...
    isfield(parameters.microphysics.thermal,'enabled') && ...
    isequal(parameters.microphysics.thermal.enabled,true) && ...
    isfield(parameters.microphysics.thermal,'mode') && ...
    strcmp(parameters.microphysics.thermal.mode,'frozen_external') && ...
    isfield(parameters.microphysics,'thermal_state') && ...
    isequaln(parameters.microphysics.thermal_state,request.frozen_thermal_state) && ...
    isequaln(parameters.microphysics.thermal_state,evaluator.frozen_thermal_state) && ...
    isfield(parameters,'bearing') && ...
    frozen_bearing_configuration_matches(parameters.bearing,evaluator);
if ~valid
    error('StageF:FormalFrozenParameterMismatch', ...
        ['FORMAL_FROZEN_PARAMETER_MISMATCH: formal thermal state, mode, ', ...
        'enable flag, or bearing configuration differs from its trusted frozen identity.']);
end
end

function pass = frozen_bearing_configuration_matches(bearing,evaluator)
if isfield(evaluator,'frozen_bearing_configuration')
    pass = isequaln(bearing,evaluator.frozen_bearing_configuration);
    return;
end
% Pure-function contract fixtures use an explicit immutable marker.  The
% formal runner always supplies the full trusted bearing snapshot above.
pass = isstruct(bearing) && isscalar(bearing) && ...
    isequal(fieldnames(bearing),{'configuration'}) && ...
    strcmp(bearing.configuration,'FORMAL_FROZEN');
end

function [force,loaded] = synthetic_evaluation(q,evaluator)
[force,loaded] = evaluator(q);
end

function force_hat = independent_synthetic_tangent(q_static,qhat,evaluation,force0)
input_count = numel(q_static); force_count = numel(force0);
Jacobian = zeros(force_count,input_count);
for input_index = 1:input_count
    step = sqrt(eps)*max(1,abs(q_static(input_index)));
    direction = zeros(input_count,1); direction(input_index) = step;
    [plus,~] = evaluation(q_static+direction);
    [minus,~] = evaluation(q_static-direction);
    plus = plus(:); minus = minus(:);
    if numel(plus) ~= force_count || numel(minus) ~= force_count || ...
            any(~isfinite(plus)) || any(~isfinite(minus))
        error('StageF:NonlinearForceEvaluation', ...
            'STAGE_F_COMPUTATION_FAILED: synthetic tangent evaluation failed.');
    end
    Jacobian(:,input_index) = (plus-minus)/(2*step);
end
force_hat = Jacobian*qhat;
end

function [force,loaded] = formal_evaluation(q,request,evaluator)
params = request.formal_parameters;
[~,bearing_state] = evaluator.function_handle(q,zeros(size(q)), ...
    params,params.bearing,numel(q));
if ~isstruct(bearing_state) || ~isfield(bearing_state,'bearings') || ...
        numel(bearing_state.bearings) < request.bearing_index
    error('StageF:NonlinearForceEvaluation', ...
        'STAGE_F_COMPUTATION_FAILED: formal evaluator returned no bearing state.');
end
state = bearing_state.bearings(request.bearing_index);
force = [state.Fx;state.Fy;state.Fz;state.Mx;state.My];
loaded = state.Q > 0;
end

function value = history_rms_norm(history)
value = sqrt(mean(sum(abs(history).^2,1)));
end

function value = relative_error(actual,expected)
if isempty(actual) || isempty(expected) || ~isequal(size(actual),size(expected))
    value = Inf;
else
    value = norm(actual(:)-expected(:))/max(norm(expected(:)),eps);
end
end

function hash = file_sha256(path)
fid = fopen(path,'rb');
if fid < 0, hash = ''; return; end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid,Inf,'*uint8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(typecast(bytes,'int8'));
raw = typecast(digest.digest(),'uint8');
hash = lower(reshape(dec2hex(raw,2).',1,[]));
end
