function [output,summary_text] = export_stage_h_summary(varargin)
%EXPORT_STAGE_H_SUMMARY Build or finalize the frozen mainline report.

if nargin == 0
    [output,summary_text] = finalize_reviewed_report();
elseif nargin == 1 && isstruct(varargin{1})
    [output,summary_text] = build_report(varargin{1});
elseif nargin == 1 && strcmp(varargin{1},'prepare_summary')
    [output,summary_text] = prepare_committable_summary();
else
    error('StageH:InvalidInput','Stage H expects results, prepare_summary, or no input.');
end
end

function [report,text] = build_report(results)
require_stage_h_ready(results);
input_hash_before = protected_input_hash(results);
static_rows = build_static_rows(results);
system_stiffness_rows = build_system_stiffness_rows(results);
dynamic_rows = build_dynamic_rows(results);
load_rows = build_bearing_load_rows(results);
stage_completion = stage_completion_state(results);
trend = results.trend_robustness;
metric_names = unique({trend.temperature_normalization.records.metric_name},'stable');
sensitive = trend.damping_envelope.sensitive_metrics;
if numel(metric_names) ~= 55 || numel(sensitive) ~= 4 || ...
        any(~[trend.damping_envelope.records.valid])
    error('StageH:TrendSummaryMismatch','STAGE_H_INPUT_NOT_READY');
end
old_ehl_excluded = results.damping.old_ehl_excluded && ...
    ~results.meta.old_ehl_used_in_formal_response;
newmark_used = results.meta.newmark_used || response_flag_used(results,'newmark_used');
dynamic_ehl_used = results.meta.dynamic_ehl_used;
input_hash_after = protected_input_hash(results);
report = struct('schema_version','stage-h-final-report-v1', ...
    'source_commit','', ...
    'stage_h_input_hash_before',input_hash_before, ...
    'stage_h_input_hash_after',input_hash_after, ...
    'input_hash_match',strcmp(input_hash_before,input_hash_after), ...
    'research_model_boundary',struct( ...
    'included',{{'closed_loop_thermal_effect', ...
    'quasi_static_EHL_contact','fixed_equivalent_damping', ...
    'full_order_1X_frequency_response'}}, ...
    'dynamic_EHL_damping_model',false), ...
    'old_ehl_excluded',logical(old_ehl_excluded), ...
    'old_ehl_used_in_formal_response', ...
    logical(results.meta.old_ehl_used_in_formal_response), ...
    'newmark_used',logical(newmark_used), ...
    'dynamic_ehl_used',logical(dynamic_ehl_used), ...
    'stage_completion',stage_completion, ...
    'static_results',static_rows, ...
    'system_stiffness_results',system_stiffness_rows, ...
    'dynamic_results',dynamic_rows, ...
    'bearing_dynamic_loads',load_rows, ...
    'nonlinear_gate',trend.stage_f_interpretation, ...
    'damping_robustness',struct('metric_count',numel(metric_names), ...
    'robust_metric_count',numel(metric_names)-numel(sensitive), ...
    'sensitive_metric_count',numel(sensitive), ...
    'sensitive_metrics',{sensitive}, ...
    'sensitive_is_failure',false), ...
    'credibility',struct('high_confidence',{{'thermal_state', ...
    'film_thickness','clearance','static_load','contact_stiffness'}}, ...
    'damping_envelope',{{'vibration_amplitude','velocity', ...
    'acceleration','transmissibility','orbit'}}, ...
    'reporting_rule','NOMINAL + LOW/HIGH range', ...
    'not_studied',{{'dynamic_EHL_damping', ...
    'exact_nonlinear_periodic_response','system_2X_response', ...
    'system_3X_response'}}), ...
    'decision',struct('status', ...
    'THERMAL_FREQUENCY_DOMAIN_MAINLINE_COMPLETED', ...
    'physical_results_modified',false,'new_computation_performed',false));
if ~report.input_hash_match || ~old_ehl_excluded || newmark_used || ...
        dynamic_ehl_used || ~all(struct2array(stage_completion))
    error('StageH:InputNotReady','STAGE_H_INPUT_NOT_READY');
end
text = render_summary(report);
report.summary_file = 'thermal_4T_frequency_domain_summary.txt';
report.summary_text_sha256 = utf8_sha256(text);
end

function require_stage_h_ready(results)
ready = isstruct(results) && ~isfield(results,'final_report') && ...
    all(isfield(results,{'static','damping','frequency_response', ...
    'bearing_contact','nonlinear_validation','trend_robustness', ...
    'progress','meta'})) && ...
    isfield(results.trend_robustness,'decision') && ...
    strcmp(results.trend_robustness.decision.status, ...
    'THERMAL_TREND_ROBUSTNESS_ASSESSED');
if ~ready, error('StageH:InputNotReady','STAGE_H_INPUT_NOT_READY'); end
end

function hash = protected_input_hash(results)
projection = struct('static',results.static,'damping',results.damping, ...
    'frequency_response',results.frequency_response, ...
    'bearing_contact',results.bearing_contact, ...
    'nonlinear_validation',results.nonlinear_validation, ...
    'trend_robustness',results.trend_robustness);
hash = serialized_sha256(projection);
end

function rows = build_static_rows(results)
empty = struct('temperature_case_C',NaN,'bearing','', ...
    'bearing_temperature_C',NaN,'viscosity_Pa_s',NaN, ...
    'film_thickness_m',NaN,'clearance_m',NaN,'loaded_count',NaN, ...
    'Qmax_static_N',NaN,'Qmean_static_N',NaN,'CV_Q_static',NaN, ...
    'contact_stiffness_fro_norm',NaN);
rows = repmat(empty,1,8); row_index = 0;
for temperature = [20 50 80 100]
    for bearing = {'front','rear'}
        name = bearing{1}; row_index = row_index+1;
        rows(row_index) = struct('temperature_case_C',temperature, ...
            'bearing',name, ...
            'bearing_temperature_C',trend_value(results, ...
            ['thermal.' name '.temperature_C'],temperature), ...
            'viscosity_Pa_s',trend_value(results, ...
            ['thermal.' name '.viscosity_Pa_s'],temperature), ...
            'film_thickness_m',trend_value(results, ...
            ['thermal.' name '.film_thickness_m'],temperature), ...
            'clearance_m',trend_value(results, ...
            ['thermal.' name '.clearance_m'],temperature), ...
            'loaded_count',trend_value(results, ...
            ['bearing.contact.' name '.loaded_count'],temperature), ...
            'Qmax_static_N',trend_value(results, ...
            ['bearing.contact.' name '.Qmax_static_N'],temperature), ...
            'Qmean_static_N',trend_value(results, ...
            ['bearing.contact.' name '.Qmean_static_N'],temperature), ...
            'CV_Q_static',trend_value(results, ...
            ['bearing.contact.' name '.CV_Q_static'],temperature), ...
            'contact_stiffness_fro_norm',trend_value(results, ...
            ['stiffness.K_b_' name '_fro_norm_N_m'],temperature));
    end
end
end

function rows = build_system_stiffness_rows(results)
rows = repmat(struct('temperature_case_C',NaN, ...
    'global_K_t_fro_norm',NaN),1,4);
temperatures = [20 50 80 100];
for index = 1:4
    temperature = temperatures(index);
    rows(index) = struct('temperature_case_C',temperature, ...
        'global_K_t_fro_norm',trend_value(results, ...
        'stiffness.K_t_fro_norm_N_m',temperature));
end
end

function rows = build_dynamic_rows(results)
metric_names = required_dynamic_metric_names();
records = results.trend_robustness.damping_envelope.records;
empty = struct('metric_name','','unit','','temperature_C',NaN, ...
    'LOW',NaN,'NOMINAL',NaN,'HIGH',NaN,'classification','');
rows = repmat(empty,1,numel(metric_names)*4); row_index = 0;
for metric_index = 1:numel(metric_names)
    metric_name = metric_names{metric_index};
    for temperature = [20 50 80 100]
        mask = strcmp({records.metric_name},metric_name) & ...
            [records.temperature_C] == temperature;
        if nnz(mask) ~= 1 || ~records(mask).valid
            error('StageH:MissingDynamicMetric','STAGE_H_INPUT_NOT_READY');
        end
        source = records(mask); row_index = row_index+1;
        rows(row_index) = struct('metric_name',metric_name, ...
            'unit',source.unit,'temperature_C',temperature, ...
            'LOW',source.LOW,'NOMINAL',source.NOMINAL,'HIGH',source.HIGH, ...
            'classification',source.classification);
    end
end
end

function names = required_dynamic_metric_names
names = {'bearing.front_relative.displacement_rms_m', ...
    'bearing.front_relative.velocity_rms_m_s', ...
    'bearing.front_relative.acceleration_rms_m_s2', ...
    'bearing.rear_relative.displacement_rms_m', ...
    'bearing.rear_relative.velocity_rms_m_s', ...
    'bearing.rear_relative.acceleration_rms_m_s2', ...
    'rotor.R2.displacement_rms_m','rotor.R2.velocity_rms_m_s', ...
    'rotor.R2.acceleration_rms_m_s2','rotor.R2.orbit_semi_major_m', ...
    'rotor.R2.orbit_semi_minor_m','rotor.R2.orbit_axis_ratio', ...
    'rotor.R10.displacement_rms_m','rotor.R10.velocity_rms_m_s', ...
    'rotor.R10.acceleration_rms_m_s2','rotor.R10.orbit_semi_major_m', ...
    'rotor.R10.orbit_semi_minor_m','rotor.R10.orbit_axis_ratio', ...
    'casing.C2.displacement_rms_m','casing.C2.velocity_rms_m_s', ...
    'casing.C2.acceleration_rms_m_s2','casing.C8.displacement_rms_m', ...
    'casing.C8.velocity_rms_m_s','casing.C8.acceleration_rms_m_s2', ...
    'transmissibility.front.displacement','transmissibility.front.velocity', ...
    'transmissibility.front.acceleration','transmissibility.rear.displacement', ...
    'transmissibility.rear.velocity','transmissibility.rear.acceleration'};
end

function rows = build_bearing_load_rows(results)
empty = struct('temperature_case_C',NaN,'scenario','','bearing','', ...
    'Qhat_max_magnitude_N',NaN,'Qmax_linear_max_N',NaN, ...
    'Qmin_linear_min_N',NaN,'dynamic_force_peak_N',NaN, ...
    'dynamic_force_rms_N',NaN,'force_semantics','');
rows = repmat(empty,1,24); row_index = 0;
for temperature = [20 50 80 100]
    tf = sprintf('T%d',temperature);
    for scenario = {'LOW','NOMINAL','HIGH'}
        scenario_name = scenario{1};
        for bearing = {'front','rear'}
            name = bearing{1}; row_index = row_index+1;
            record = results.bearing_contact.(tf).(scenario_name).(name);
            roller = record.roller_level;
            loaded = logical(roller.loaded_mask_static_roller(:));
            force = record.bearing_force_on_rotor;
            if ~any(loaded) || ~strcmp(force.force_semantics, ...
                    'FORCE_ON_ROTOR_MINUS_AQ')
                error('StageH:MissingBearingLoad','STAGE_H_INPUT_NOT_READY');
            end
            rows(row_index) = struct('temperature_case_C',temperature, ...
                'scenario',scenario_name,'bearing',name, ...
                'Qhat_max_magnitude_N',max(abs(roller.Qhat_roller(loaded))), ...
                'Qmax_linear_max_N',max(roller.Qmax_linear_roller(loaded)), ...
                'Qmin_linear_min_N',min(roller.Qmin_linear_roller(loaded)), ...
                'dynamic_force_peak_N',force.radial_force_peak, ...
                'dynamic_force_rms_N',force.radial_force_rms, ...
                'force_semantics',force.force_semantics);
        end
    end
end
end

function value = trend_value(results,metric_name,temperature)
records = results.trend_robustness.temperature_normalization.records;
mask = strcmp({records.metric_name},metric_name) & ...
    [records.temperature_C] == temperature & strcmp({records.scenario},'NOMINAL');
if nnz(mask) ~= 1 || ~records(mask).valid
    error('StageH:MissingStaticMetric','STAGE_H_INPUT_NOT_READY');
end
value = records(mask).value;
end

function state = stage_completion_state(results)
state = struct('stage_a',logical(results.progress.stage_a_complete), ...
    'stage_b',logical(results.progress.stage_b_complete), ...
    'stage_c',logical(results.progress.stage_c_damping_envelope_complete), ...
    'stage_d',logical(results.progress.stage_d_complete), ...
    'stage_e',logical(results.progress.stage_e_complete), ...
    'stage_f',logical(results.progress.stage_f_complete), ...
    'stage_g',strcmp(results.trend_robustness.decision.status, ...
    'THERMAL_TREND_ROBUSTNESS_ASSESSED'));
end

function used = response_flag_used(results,field)
used = false;
for temperature = [20 50 80 100]
    tf = sprintf('T%d',temperature);
    for scenario = {'LOW','NOMINAL','HIGH'}
        record = results.frequency_response.(tf).(scenario{1});
        used = used || ~isfield(record,field) || logical(record.(field));
    end
end
end

function text = render_summary(report)
header = {'THERMAL FREQUENCY-DOMAIN MAINLINE FINAL SUMMARY', ...
    '', '1. 研究模型边界', ...
    '闭环热效应 + 准静态EHL接触 + 固定等效阻尼 + 全阶1X频域响应', ...
    '本研究不是动态EHL阻尼模型。', ...
    '', '2. 旧EHL处理', ...
    'old_ehl_excluded=true', ...
    '旧a^4/h^3阻尼未进入正式响应。', ...
    '', '3. 四温度静态结果', ...
    'T_C | bearing | bearing_T_C | viscosity_Pa_s | film_m | clearance_m | loaded_count | Qmax_N | Qmean_N | CV_Q | Kb_fro'};
static_lines = cell(1,numel(report.static_results));
for index = 1:numel(report.static_results)
    row = report.static_results(index);
    static_lines{index} = sprintf('%d | %s | %.9e | %.9e | %.9e | %.9e | %.0f | %.9e | %.9e | %.9e | %.9e', ...
        row.temperature_case_C,row.bearing,row.bearing_temperature_C, ...
        row.viscosity_Pa_s,row.film_thickness_m,row.clearance_m, ...
        row.loaded_count,row.Qmax_static_N,row.Qmean_static_N, ...
        row.CV_Q_static,row.contact_stiffness_fro_norm);
end
stiffness_lines = cell(1,numel(report.system_stiffness_results));
for index = 1:numel(report.system_stiffness_results)
    row = report.system_stiffness_results(index);
    stiffness_lines{index} = sprintf('%d | global_K_t_fro_norm | %.9e', ...
        row.temperature_case_C,row.global_K_t_fro_norm);
end
dynamic_header = {'','4. 动力学结果（NOMINAL + LOW/HIGH范围）', ...
    'metric | T_C | LOW | NOMINAL | HIGH | trend'};
dynamic_lines = cell(1,numel(report.dynamic_results));
for index = 1:numel(report.dynamic_results)
    row = report.dynamic_results(index);
    dynamic_lines{index} = sprintf('%s | %d | %.9e | %.9e | %.9e | %s', ...
        row.metric_name,row.temperature_C,row.LOW,row.NOMINAL,row.HIGH, ...
        row.classification);
end
load_header = {'','5. 轴承动态载荷', ...
    'T_C | scenario | bearing | Qhat_max_N | Qmax_N | Qmin_N | force_peak_N | force_rms_N | semantics'};
load_lines = cell(1,numel(report.bearing_dynamic_loads));
for index = 1:numel(report.bearing_dynamic_loads)
    row = report.bearing_dynamic_loads(index);
    load_lines{index} = sprintf('%d | %s | %s | %.9e | %.9e | %.9e | %.9e | %.9e | %s', ...
        row.temperature_case_C,row.scenario,row.bearing, ...
        row.Qhat_max_magnitude_N,row.Qmax_linear_max_N, ...
        row.Qmin_linear_min_N,row.dynamic_force_peak_N, ...
        row.dynamic_force_rms_N,row.force_semantics);
end
footer = {'','6. 非线性Gate', ...
    'epsilon_NL约0.25；H2/H1约5e-5；H3/H1约1e-9。', ...
    '无接触丢失；无主动集变化。', ...
    '结论：WORKPOINT_LINEARIZATION_LOCAL_DEVIATION_EXPLAINED', ...
    '', '7. 阻尼稳健性', ...
    '55项指标：51项稳健，4项阻尼敏感。', ...
    '阻尼敏感：C8 displacement RMS', ...
    '阻尼敏感：C8 velocity RMS', ...
    '阻尼敏感：C8 acceleration RMS', ...
    '阻尼敏感：front bearing Qhat', ...
    '', '8. 论文可信等级', ...
    '高可信：热状态、膜厚、游隙、静态载荷、刚度。', ...
    '阻尼包络：振动幅值、速度、加速度、传递率、轨迹；报告采用NOMINAL + LOW/HIGH范围。', ...
    '未研究：动态EHL阻尼、精确非线性周期响应、系统2X/3X响应。', ...
    '', '状态：THERMAL_FREQUENCY_DOMAIN_MAINLINE_COMPLETED'};
lines = [header static_lines stiffness_lines dynamic_header dynamic_lines ...
    load_header load_lines footer];
text = [strjoin(lines,newline) newline];
end

function [report,text] = prepare_committable_summary
root = fileparts(mfilename('fullpath')); canonical = canonical_path(root);
require_exact_canonical(canonical);
artifact = load(canonical); [report,text] = build_report(artifact.results);
summary_path = fullfile(fileparts(canonical), ...
    'thermal_4T_frequency_domain_summary.txt');
write_summary_atomic(summary_path,text);
end

function [results,text] = finalize_reviewed_report
root = fileparts(mfilename('fullpath')); identity = require_reviewed_source(root);
canonical = canonical_path(root); require_exact_canonical(canonical);
artifact = load(canonical); baseline = artifact.results;
[report,text] = build_report(baseline); report.source_commit = identity.source_commit;
summary_path = fullfile(fileparts(canonical),report.summary_file);
if ~isfile(summary_path) || ~strcmp(fileread(summary_path),text)
    error('StageH:SummaryMismatch','STAGE_H_SUMMARY_MISMATCH');
end
candidate = baseline; candidate.final_report = report;
validation = validate_stage_h_final_results(candidate,baseline,text,true);
if ~validation.passed
    error('StageH:ValidationFailed','STAGE_H_VALIDATION_FAILED: %s', ...
        strjoin(validation.diagnostics,','));
end
candidate.final_report.validation = validation;
if ~validate_stage_h_final_results(candidate,baseline,text,true).passed
    error('StageH:ValidationFailed','STAGE_H_VALIDATION_FAILED: saved validation mismatch.');
end
atomic_append(canonical,candidate,baseline, ...
    'f09c66bd83ad5d416970b70e0b5dfad09b0ccb62b7432180b0f8b40aca0e1852', ...
    text,summary_path,report.summary_text_sha256);
results = candidate;
fprintf('THERMAL_FREQUENCY_DOMAIN_MAINLINE_COMPLETED\n');
end

function path = canonical_path(root)
path = fullfile(root,'results','thermal_equivalent_damping_frequency_domain', ...
    'thermal_4T_frequency_domain_results.mat');
end

function require_exact_canonical(canonical)
expected = 'f09c66bd83ad5d416970b70e0b5dfad09b0ccb62b7432180b0f8b40aca0e1852';
if ~isfile(canonical) || ~strcmp(file_sha256(canonical),expected)
    error('StageH:BaselineMismatch','STAGE_H_INPUT_NOT_READY');
end
end

function write_summary_atomic(path,text)
temporary = [path '.stage_h_prepare.tmp'];
if isfile(temporary), error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT'); end
cleanup = onCleanup(@() delete_if_present(temporary));
fid = fopen(temporary,'w','n','UTF-8');
if fid < 0, error('StageH:SummaryWriteFailed','STAGE_H_SUMMARY_WRITE_FAILED'); end
file_cleanup = onCleanup(@() fclose(fid)); fprintf(fid,'%s',text); clear file_cleanup;
source = java.nio.file.Paths.get(temporary,javaArray('java.lang.String',0));
target = java.nio.file.Paths.get(path,javaArray('java.lang.String',0));
options = javaArray('java.nio.file.CopyOption',2);
options(1) = java.nio.file.StandardCopyOption.ATOMIC_MOVE;
options(2) = java.nio.file.StandardCopyOption.REPLACE_EXISTING;
java.nio.file.Files.move(source,target,options);
end

function atomic_append(canonical,results,baseline,expected_sha256,text, ...
        summary_path,expected_summary_sha256)
temporary = [canonical '.stage_h_transaction.mat'];
if isfile(temporary), error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT'); end
temporary_cleanup = onCleanup(@() delete_if_present(temporary));
[channel,file_lock] = acquire_lock(canonical);
lock_cleanup = onCleanup(@() release_lock(file_lock,channel));
[summary_channel,summary_lock] = acquire_lock(summary_path);
summary_lock_cleanup = onCleanup(@() release_lock(summary_lock,summary_channel));
if ~strcmp(file_sha256(canonical),expected_sha256)
    error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT');
end
if ~strcmp(file_sha256(summary_path),expected_summary_sha256) || ...
        ~strcmp(fileread(summary_path),text)
    error('StageH:SummaryMismatch','STAGE_H_SUMMARY_MISMATCH');
end
current = load(canonical);
if ~isequaln(current.results,baseline)
    error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT');
end
save(temporary,'results'); reloaded = load(temporary);
if ~validate_stage_h_final_results(reloaded.results,baseline,text,false).passed
    error('StageH:ValidationFailed','STAGE_H_VALIDATION_FAILED: transaction reload failed.');
end
force_file(temporary);
if ~strcmp(file_sha256(canonical),expected_sha256)
    error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT');
end
current = load(canonical);
if ~isequaln(current.results,baseline)
    error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT');
end
if ~strcmp(file_sha256(summary_path),expected_summary_sha256) || ...
        ~strcmp(fileread(summary_path),text)
    error('StageH:SummaryMismatch','STAGE_H_SUMMARY_MISMATCH');
end
source = java.nio.file.Paths.get(temporary,javaArray('java.lang.String',0));
target = java.nio.file.Paths.get(canonical,javaArray('java.lang.String',0));
options = javaArray('java.nio.file.CopyOption',2);
options(1) = java.nio.file.StandardCopyOption.ATOMIC_MOVE;
options(2) = java.nio.file.StandardCopyOption.REPLACE_EXISTING;
java.nio.file.Files.move(source,target,options);
end

function [channel,file_lock] = acquire_lock(path)
source = java.nio.file.Paths.get(path,javaArray('java.lang.String',0));
options = javaArray('java.nio.file.OpenOption',1);
options(1) = java.nio.file.StandardOpenOption.WRITE;
channel = java.nio.channels.FileChannel.open(source,options);
try
    file_lock = channel.tryLock();
catch
    channel.close(); error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT');
end
if isempty(file_lock)
    channel.close(); error('StageH:TransactionConflict','STAGE_H_TRANSACTION_CONFLICT');
end
end

function release_lock(file_lock,channel)
if ~isempty(file_lock) && file_lock.isValid(), file_lock.release(); end
if ~isempty(channel) && channel.isOpen(), channel.close(); end
end

function force_file(path)
source = java.nio.file.Paths.get(path,javaArray('java.lang.String',0));
options = javaArray('java.nio.file.OpenOption',1);
options(1) = java.nio.file.StandardOpenOption.WRITE;
channel = java.nio.channels.FileChannel.open(source,options);
cleanup = onCleanup(@() channel.close()); channel.force(true);
end

function identity = require_reviewed_source(root)
old = pwd; cleanup = onCleanup(@() cd(old)); cd(root);
expected_files = {'export_stage_h_summary.m','validate_stage_h_final_results.m', ...
    'test_stage_h_final_reload.m', ...
    'results/thermal_equivalent_damping_frequency_domain/thermal_4T_frequency_domain_summary.txt'};
parent = '5eaf6e83da4376b83f9713664176f242ce6c8744';
subject = 'feat: export validated thermal frequency-domain mainline results';
[s1,status] = system('git status --porcelain=v1');
[s2,parent_observed] = system('git log -1 --format=%P HEAD');
[s3,subject_observed] = system('git log -1 --format=%s HEAD');
[s4,changed_output] = system(['git diff --name-only ' parent '..HEAD']);
[s5,commit] = system('git rev-parse HEAD');
changed = strsplit(strtrim(changed_output),newline);
valid = all([s1 s2 s3 s4 s5] == 0) && isempty(strtrim(status)) && ...
    strcmp(strtrim(parent_observed),parent) && ...
    strcmp(strtrim(subject_observed),subject) && ...
    isequal(sort(changed),sort(expected_files));
if ~valid, error('StageH:SourceMismatch','STAGE_H_SOURCE_GATE_FAILED'); end
identity = struct('source_commit',strtrim(commit));
end

function delete_if_present(path)
if isfile(path), delete(path); end
end

function hash = serialized_sha256(value)
bytes = getByteStreamFromArray(value);
engine = java.security.MessageDigest.getInstance('SHA-256');
engine.update(typecast(uint8(bytes),'int8'));
digest = typecast(engine.digest(),'uint8');
hash = lower(reshape(dec2hex(digest,2).',1,[]));
end

function hash = utf8_sha256(text)
bytes = unicode2native(text,'UTF-8');
engine = java.security.MessageDigest.getInstance('SHA-256');
engine.update(typecast(uint8(bytes),'int8'));
digest = typecast(engine.digest(),'uint8');
hash = lower(reshape(dec2hex(digest,2).',1,[]));
end

function hash = file_sha256(path)
fid = fopen(path,'rb'); cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid,Inf,'*uint8');
engine = java.security.MessageDigest.getInstance('SHA-256');
engine.update(typecast(bytes,'int8')); digest = typecast(engine.digest(),'uint8');
hash = lower(reshape(dec2hex(digest,2).',1,[]));
end
