function state = extract_stage_d_static_state(requested_temperature_C, ...
    source_temperature_C,thermal,stiffness,params,model,source_commit)
%EXTRACT_STAGE_D_STATIC_STATE Extract one accepted formal static workpoint.

front = thermal.contact_state.bearings(1);
rear = thermal.contact_state.bearings(2);
K_tangent = model.K_structure + ...
    model.B_front.'*stiffness(1).K_local*model.B_front + ...
    model.B_rear.'*stiffness(2).K_local*model.B_rear;
front_statistics = compute_stage_d_bearing_statistics(front.Q,front.theta);
rear_statistics = compute_stage_d_bearing_statistics(rear.Q,rear.theta);
front_contact_stiffness = formal_contact_stiffness( ...
    front.delta,params.bearing(1));
rear_contact_stiffness = formal_contact_stiffness( ...
    rear.delta,params.bearing(2));

state = struct();
state.requested_case_temperature_C = requested_temperature_C;
state.initial_guess_source_temperature_C = source_temperature_C;
state.initial_guess_only = true;
state.initial_guess_fields_used = {'q_static'};
state.thermal_seed_strategy = 'FORMAL_SOLVER_CURRENT_OIL_TEMPERATURE_SEED';
state.q_static = thermal.q_static;
state.thermal_state = thermal.thermal_state;
state.lubricant_state = struct( ...
    'front',lubricant_entry(thermal.thermal_state.ball), ...
    'rear',lubricant_entry(thermal.thermal_state.roller));
state.film_thickness = struct('front',film_entry(front), ...
    'rear',film_entry(rear));
state.clearance_state = struct( ...
    'front',clearance_entry(thermal.thermal_state.ball,params.bearing(1)), ...
    'rear',clearance_entry(thermal.thermal_state.roller,params.bearing(2)));
state.bearing_state_front = front;
state.bearing_state_rear = rear;
state.rolling_element_loads_front = front_statistics.rolling_element_loads_N;
state.rolling_element_loads_rear = rear_statistics.rolling_element_loads_N;
state.loaded_mask_front = front_statistics.loaded_mask;
state.loaded_mask_rear = rear_statistics.loaded_mask;
state.contact_deflection_front = front.delta;
state.contact_deflection_rear = rear.delta;
state.contact_stiffness_front = front_contact_stiffness;
state.contact_stiffness_rear = rear_contact_stiffness;
state.contact_stiffness_source_front = 'FORMAL_BALL_HERTZ_DERIVATIVE';
state.contact_stiffness_source_rear = 'FORMAL_ROLLER_SLICE_LAW_DERIVATIVE';
state.contact_stiffness_summary = struct( ...
    'front',stiffness_summary(front_contact_stiffness,front.Q), ...
    'rear',stiffness_summary(rear_contact_stiffness,rear.Q));
front_resultant = [front.Fx;front.Fy;front.Fz;front.Mx;front.My];
rear_resultant = [rear.Fx;rear.Fy;rear.Fz;rear.Mx;rear.My];
front_difference = max(abs(front_resultant-stiffness(1).force_at_workpoint));
rear_difference = max(abs(rear_resultant-stiffness(2).force_at_workpoint));
front_ir = 6*params.bearing(1).rotor_node+(-5:-1);
front_ic = model.modelInfo.num_rotor_dof + 6*params.bearing(1).case_node+(-5:-1);
rear_ir = 6*params.bearing(2).rotor_node+(-5:-1);
rear_ic = model.modelInfo.num_rotor_dof + 6*params.bearing(2).case_node+(-5:-1);
assembled_force = thermal.static_result.bearing_force;
front_global_difference = max(abs(front_resultant-assembled_force(front_ir)));
rear_global_difference = max(abs(rear_resultant-assembled_force(rear_ir)));
front_action_reaction = norm(assembled_force(front_ir)+assembled_force(front_ic));
rear_action_reaction = norm(assembled_force(rear_ir)+assembled_force(rear_ic));
state.bearing_resultant_consistency = struct( ...
    'front_linearization_repeatability_error',front_difference, ...
    'rear_linearization_repeatability_error',rear_difference, ...
    'front_global_assembly_error',front_global_difference, ...
    'rear_global_assembly_error',rear_global_difference, ...
    'front_action_reaction_error',front_action_reaction, ...
    'rear_action_reaction_error',rear_action_reaction, ...
    'formal_static_action_reaction_error',thermal.static_result.action_reaction_error, ...
    'passed',front_difference <= 1e-10 && rear_difference <= 1e-10 && ...
    front_global_difference <= 1e-10 && rear_global_difference <= 1e-10 && ...
    front_action_reaction <= 1e-10 && rear_action_reaction <= 1e-10 && ...
    thermal.static_result.action_reaction_error <= 1e-10, ...
    'units','MIXED_LOCAL_GENERALIZED_FORCE_VECTOR', ...
    'source','FORMAL_STATIC_ASSEMBLY_AND_WORKPOINT_LINEARIZATION');
state.K_b_front = stiffness(1).K_local;
state.K_b_rear = stiffness(2).K_local;
state.K_tangent = K_tangent;
state.acceptance = thermal.stage_d_acceptance;
state.statistics = struct('front',front_statistics,'rear',rear_statistics);
state.final_front_bearing_temperature_C = thermal.thermal_state.ball.T_final;
state.final_rear_bearing_temperature_C = thermal.thermal_state.roller.T_final;
state.invariant_references = struct( ...
    'M','results.static.T20.M','G','results.static.T20.G', ...
    'dof_mapping','results.static.T20.dof_mapping', ...
    'M_max_abs_difference',max(abs(model.M-model.M_reference),[],'all'), ...
    'G_max_abs_difference',max(abs(model.G-model.G_reference),[],'all'), ...
    'consistent',isequaln(model.M,model.M_reference) && ...
    isequaln(model.G,model.G_reference));
state.source_commit = source_commit;
state.validation = validate_stage_d_static_temperature_case( ...
    state,size(model.M,1));
end

function entry = lubricant_entry(thermal)
entry = struct('viscosity_Pa_s',thermal.eta, ...
    'pressure_viscosity_Pa_inv',thermal.alpha_p, ...
    'film_temperature_C',thermal.T_film, ...
    'source','FORMAL_FROZEN_THERMAL_STATE');
end

function entry = film_entry(contact)
loaded = contact.film.loaded_mask;
central_loaded = contact.film.h_m(loaded);
entry = struct('central_by_contact_m',contact.film.h_m, ...
    'central_loaded_m',reshape(central_loaded,1,[]), ...
    'central_min_loaded_m',min(central_loaded), ...
    'minimum_m',contact.film.hmin_m,'unit','m', ...
    'source','FORMAL_CONTACT_FILM_STATE','floor_active',false, ...
    'floor_status','NO_FLOOR_FLAG_EXPOSED_BY_FORMAL_FILM_SOLVER', ...
    'unloaded_values_not_applicable',true);
end

function entry = clearance_entry(thermal,bearing)
cold = bearing.assembly.radial_clearance;
entry = struct('cold_clearance_m',cold, ...
    'thermal_expansion_correction_m',thermal.working_clearance-cold, ...
    'film_or_contact_correction_m',0, ...
    'working_clearance_m',thermal.working_clearance, ...
    'film_or_contact_correction_available',false, ...
    'source','FORMAL_DIFFERENTIAL_THERMAL_CLEARANCE', ...
    'thermal_preload',thermal.thermal_preload);
end

function stiffness = formal_contact_stiffness(delta,bearing)
stiffness = zeros(size(delta)); loaded = delta > 0;
if strcmpi(bearing.type,'ball')
    stiffness(loaded) = 1.5*bearing.K_point*sqrt(delta(loaded));
elseif strcmpi(bearing.type,'roller')
    coefficient = bearing.K_line/bearing.stage4A_slice_count;
    stiffness(loaded) = (10/9)*coefficient*delta(loaded).^(1/9);
else
    error('StageD:BearingType','Unsupported bearing type.');
end
end

function summary = stiffness_summary(stiffness,Q)
loaded = Q > 0; values = stiffness(loaded);
if isempty(values), maximum = 0; mean_loaded = 0; total = 0;
else, maximum = max(values); mean_loaded = mean(values); total = sum(values); end
summary = struct('maximum_N_per_m',maximum, ...
    'mean_loaded_N_per_m',mean_loaded,'sum_N_per_m',total, ...
    'loaded_contact_count',nnz(loaded));
end
