function cfg = microphysics_config(overrides)
%MICROPHYSICS_CONFIG Default local microphysics switches and settings.

cfg.thermal = struct('enabled', false, 'mode', 'closed_loop_equilibrium', ...
    'H_W_per_K', 120, 'relaxation', 0.2, 'temperature_tolerance_C', 1e-3, ...
    'max_iterations', 80, 'fail_on_nonconvergence', true, ...
    'oil_temperature_C', 20, 'film_temperature_weight', 0.5, ...
    'viscosity_reference_cSt', 27.6, 'viscosity_reference_temperature_C', 40, ...
    'viscosity_temperature_coefficient', 0.02815, 'oil_density_kg_m3', 1003.5, ...
    'pressure_viscosity_reference_Pa_inv', 1.28e-8, ...
    'pressure_viscosity_reference_temperature_C', 20, ...
    'pressure_viscosity_temperature_coefficient', 0.010, ...
    'clearance_temperature_coefficient_m_per_C', 1.5e-6, ...
    'ball_film_exponent', 0.68, 'roller_film_exponent', 0.70);
cfg.roughness = struct('enabled', false);
cfg.impurity = struct('enabled', false);
if nargin < 1 || isempty(overrides)
    return;
end
names = {'thermal', 'roughness', 'impurity'};
for k = 1:numel(names)
    name = names{k};
    if isfield(overrides, name) && isstruct(overrides.(name))
        fields = fieldnames(overrides.(name));
        for j = 1:numel(fields)
            cfg.(name).(fields{j}) = overrides.(name).(fields{j});
        end
    end
end
end
