function recovered = recover_stage_f_rolling_element_1X_loads(mapping,qhat_full)
%RECOVER_STAGE_F_ROLLING_ELEMENT_1X_LOADS Recover slice and roller 1X loads.

required = {'element_count','slice_count','delta_static_slice', ...
    'Q_static_slice','k_static_slice','loaded_mask_static_slice', ...
    'loaded_mask_static_roller','contact_jacobian_local', ...
    'force_assembly_local','interface_transform','K_b_local', ...
    'K_b_local_analytic','tangent_audit','mapping_provenance'};
if ~isstruct(mapping) || ~all(isfield(mapping,required)) || ...
        ~isnumeric(qhat_full) || ~isvector(qhat_full) || ...
        numel(qhat_full) ~= size(mapping.interface_transform,2) || ...
        any(~isfinite(real(qhat_full))) || any(~isfinite(imag(qhat_full)))
    error('StageF:LoadRecoveryInput','STAGE_F_COMPUTATION_FAILED: invalid load-recovery input.');
end
qhat_full = qhat_full(:);
u_relative = mapping.interface_transform*qhat_full;
delta_hat_vector = mapping.contact_jacobian_local*u_relative;
Qhat_vector = mapping.k_static_slice(:).*delta_hat_vector;
shape = size(mapping.k_static_slice);
delta_hat = reshape(delta_hat_vector,shape);
Qhat = reshape(Qhat_vector,shape);
Q_static = mapping.Q_static_slice;
delta_static = mapping.delta_static_slice;
k_static = mapping.k_static_slice;
loaded = logical(mapping.loaded_mask_static_slice);
Qmax = Q_static+abs(Qhat);
Qmin = Q_static-abs(Qhat);

r_delta = nan(shape);
r_delta(loaded) = abs(delta_hat(loaded))./max(abs(delta_static(loaded)),1e-12);
linearity_class = repmat({'NOT_EVALUATED_STATICALLY_UNLOADED_SLICE'},shape);
classification_tolerance = 100*eps;
linearity_class(loaded & r_delta <= 0.10+classification_tolerance) = {'STRONG_LOCAL_LINEARITY'};
linearity_class(loaded & r_delta > 0.10+classification_tolerance & ...
    r_delta <= 0.20+classification_tolerance) = ...
    {'ACCEPTABLE_WITH_CAUTION'};
linearity_class(loaded & r_delta > 0.20+classification_tolerance) = ...
    {'LOCAL_LINEARITY_LIMIT_EXCEEDED'};
contact_loss = loaded & Qmin <= 0;
contact_loss_evaluated = loaded;
contact_loss_reason = repmat({'STATICALLY_UNLOADED_ELEMENT'},shape);
contact_loss_reason(loaded & ~contact_loss) = {'NO_LINEAR_CONTACT_LOSS'};
contact_loss_reason(contact_loss) = {'POTENTIAL_CONTACT_LOSS'};

slice_level = struct('level_label','SLICE_LEVEL', ...
    'Q_static_slice',Q_static,'loaded_mask_static_slice',loaded, ...
    'delta_static_slice',delta_static,'k_static_slice',k_static, ...
    'delta_hat_slice',delta_hat,'delta_hat_real_slice',real(delta_hat), ...
    'delta_hat_imag_slice',imag(delta_hat), ...
    'delta_hat_magnitude_slice',abs(delta_hat), ...
    'delta_hat_phase_rad_slice',angle(delta_hat), ...
    'Qhat_slice',Qhat,'Qhat_real_slice',real(Qhat), ...
    'Qhat_imag_slice',imag(Qhat),'Qhat_magnitude_slice',abs(Qhat), ...
    'Qhat_phase_rad_slice',angle(Qhat), ...
    'Qmax_linear_slice',Qmax,'Qmin_linear_slice',Qmin, ...
    'r_delta_slice',r_delta,'linearity_class_slice',{linearity_class}, ...
    'potential_contact_loss_slice',contact_loss, ...
    'contact_loss_evaluated_slice',contact_loss_evaluated, ...
    'contact_loss_reason_slice',{contact_loss_reason});

Q_static_roller = sum(Q_static,2);
Qhat_roller = sum(Qhat,2);
loaded_roller = any(loaded,2);
Qmax_roller = Q_static_roller+abs(Qhat_roller);
Qmin_roller = Q_static_roller-abs(Qhat_roller);
r_delta_roller = nan(mapping.element_count,1);
for roller_index = 1:mapping.element_count
    values = r_delta(roller_index,loaded(roller_index,:));
    if ~isempty(values), r_delta_roller(roller_index) = max(values); end
end
roller_class = repmat({'NOT_EVALUATED_STATICALLY_UNLOADED_ROLLER'}, ...
    mapping.element_count,1);
roller_class(loaded_roller & r_delta_roller <= 0.10+classification_tolerance) = ...
    {'STRONG_LOCAL_LINEARITY'};
roller_class(loaded_roller & r_delta_roller > 0.10+classification_tolerance & ...
    r_delta_roller <= 0.20+classification_tolerance) = ...
    {'ACCEPTABLE_WITH_CAUTION'};
roller_class(loaded_roller & r_delta_roller > 0.20+classification_tolerance) = ...
    {'LOCAL_LINEARITY_LIMIT_EXCEEDED'};
roller_loss = loaded_roller & Qmin_roller <= 0;
roller_level = struct('level_label','ROLLER_LEVEL', ...
    'Q_static_roller',Q_static_roller, ...
    'loaded_mask_static_roller',loaded_roller, ...
    'Qhat_roller',Qhat_roller,'Qhat_real_roller',real(Qhat_roller), ...
    'Qhat_imag_roller',imag(Qhat_roller), ...
    'Qhat_magnitude_roller',abs(Qhat_roller), ...
    'Qhat_phase_rad_roller',angle(Qhat_roller), ...
    'Qmax_linear_roller',Qmax_roller,'Qmin_linear_roller',Qmin_roller, ...
    'r_delta_roller',r_delta_roller,'linearity_class_roller',{roller_class}, ...
    'potential_contact_loss_roller',roller_loss, ...
    'contact_loss_evaluated_roller',loaded_roller);

analytic_constructed = mapping.force_assembly_local* ...
    diag(mapping.k_static_slice(:))*mapping.contact_jacobian_local;
analytic_definition_error = relative_error( ...
    analytic_constructed,mapping.K_b_local_analytic);
contact_load_local = mapping.force_assembly_local*Qhat_vector;
analytic_force = mapping.K_b_local_analytic*u_relative;
saved_force = mapping.K_b_local*u_relative;
element_error = relative_error(contact_load_local,analytic_force);
if ~isfinite(element_error) || element_error > 1e-10 || ...
        analytic_definition_error > 1e-10
    error('StageF:RollingElementForceAssemblyMismatch', ...
        'ROLLING_ELEMENT_FORCE_ASSEMBLY_MISMATCH: slice force assembly disagrees with A*diag(k)*J*u.');
end
tangent_error = relative_error(analytic_constructed,mapping.K_b_local);
if ~isfinite(tangent_error) || tangent_error > 1e-8
    error('StageF:AnalyticVsFDTangentAuditFailed', ...
        'ANALYTIC_VS_FD_TANGENT_AUDIT_FAILED: analytic and saved local tangents disagree.');
end
assembly = struct( ...
    'element_vs_analytic_tangent_relative_error',element_error, ...
    'element_vs_analytic_tangent_threshold',1e-10, ...
    'element_vs_analytic_tangent_gate_status','ROLLING_ELEMENT_FORCE_ASSEMBLY_MATCHED', ...
    'analytic_vs_saved_tangent_relative_error',tangent_error, ...
    'analytic_vs_saved_tangent_threshold',1e-8, ...
    'analytic_vs_saved_tangent_gate_status','ANALYTIC_VS_FD_TANGENT_AUDIT_PASSED', ...
    'analytic_definition_relative_error',analytic_definition_error, ...
    'analytic_local_complex',analytic_force,'saved_tangent_local_complex',saved_force);
radial_components = contact_load_local(1:2);
radial_phase_map = [real(radial_components) -imag(radial_components)];
radial_peak = norm(radial_phase_map,2);
radial_rms = norm(radial_components,2)/sqrt(2);
contact_load_resultant = struct('local_complex',contact_load_local, ...
    'global_complex',mapping.interface_transform.'*contact_load_local, ...
    'Fx_hat',contact_load_local(1),'Fy_hat',contact_load_local(2), ...
    'radial_force_peak',radial_peak,'radial_force_rms',radial_rms, ...
    'component_phase_rad',angle(contact_load_local), ...
    'force_semantics','CONTACT_LOAD_PLUS_AQ');
bearing_force_local = -contact_load_local;
bearing_force_on_rotor = struct('local_complex',bearing_force_local, ...
    'global_complex',mapping.interface_transform.'*bearing_force_local, ...
    'Fx_hat',bearing_force_local(1),'Fy_hat',bearing_force_local(2), ...
    'radial_force_peak',radial_peak,'radial_force_rms',radial_rms, ...
    'component_phase_rad',angle(bearing_force_local), ...
    'force_semantics','FORCE_ON_ROTOR_MINUS_AQ');
dynamic_resultant = contact_load_resultant;

loaded_r = r_delta(loaded);
if isempty(loaded_r), maximum_r_delta = NaN; else, maximum_r_delta = max(loaded_r); end
limit_exceeded = any(r_delta(loaded) > 0.20+classification_tolerance);
hard_failure = any(contact_loss(:)) || limit_exceeded;
if hard_failure
    status = 'REPRESENTATIVE_NONLINEAR_VALIDATION_REQUIRED';
elseif isempty(loaded_r) || maximum_r_delta <= 0.10
    status = 'FREQUENCY_DOMAIN_LINEARIZATION_ACCEPTED';
else
    status = 'FREQUENCY_DOMAIN_LINEARIZATION_CAUTION';
end
hard_gate = struct('loaded_slice_contact_loss',any(contact_loss(:)), ...
    'loaded_slice_linearity_limit_exceeded',limit_exceeded, ...
    'maximum_loaded_slice_r_delta',maximum_r_delta,'status',status);

stage_e_response_source_commit = '';
if isfield(mapping.mapping_provenance,'stage_e_source_commit')
    stage_e_response_source_commit = mapping.mapping_provenance.stage_e_source_commit;
elseif isfield(mapping.mapping_provenance,'accepted_stage_e_commit')
    stage_e_response_source_commit = mapping.mapping_provenance.accepted_stage_e_commit;
end
stage_f_source_commit = '';
if isfield(mapping.mapping_provenance,'stage_f_source_commit')
    stage_f_source_commit = mapping.mapping_provenance.stage_f_source_commit;
end
recovered = struct('slice_level',slice_level,'roller_level',roller_level, ...
    'dynamic_resultant',dynamic_resultant, ...
    'contact_load_resultant',contact_load_resultant, ...
    'bearing_force_on_rotor',bearing_force_on_rotor, ...
    'force_assembly_validation',assembly,'hard_gate',hard_gate, ...
    'mapping_snapshot',mapping, ...
    'stage_e_response_source_commit',stage_e_response_source_commit, ...
    'stage_f_source_commit',stage_f_source_commit, ...
    'interface_relative_motion_hat',u_relative);
end

function value = relative_error(actual,expected)
value = norm(actual(:)-expected(:))/max(norm(expected(:)),eps);
end
