function results = run_stage_f_recover_loads_and_evaluate_nonlinearity
%RUN_STAGE_F_RECOVER_LOADS_AND_EVALUATE_NONLINEARITY One formal Stage F run.

repository_root = fileparts(mfilename('fullpath'));
identity = require_stage_f_source(repository_root);
require_independent_validation_contract(repository_root);
canonical_path = fullfile(repository_root,'results', ...
    'thermal_equivalent_damping_frequency_domain', ...
    'thermal_4T_frequency_domain_results.mat');
expected_canonical_sha256 = ...
    '3f0e6e3b379cda670ef173682c58d17a19fc6b30f761ed59a00f3c203793abfd';
if ~isfile(canonical_path) || ...
        ~strcmp(stage_f_file_sha256(canonical_path),expected_canonical_sha256) || ...
        ~stage_f_canonical_transaction('audit',canonical_path).passed
    error('StageF:BaselineMismatch', ...
        'STAGE_F_BASELINE_MISMATCH: exact canonical Stage E artifact is required.');
end
artifact = load(canonical_path); baseline = artifact.results;
if ~stage_e_baseline_valid(baseline)
    error('StageF:BaselineMismatch', ...
        'STAGE_F_BASELINE_MISMATCH: accepted Stage E inputs are incomplete.');
end

started_at = datetime('now'); candidate = baseline;
temperatures = [20 50 80 100]; scenarios = {'LOW','NOMINAL','HIGH'};
bearings = {'front','rear'};
manifest = repmat(struct('temperature_case_C',0,'bearing','', ...
    'scenario','NOMINAL','phase_count',32,'thermal_state_frozen',true, ...
    'evaluator_function','nonlinear_bearing_force'),1,8);
manifest_index = 0; first_trigger = struct([]); global_hard = false;
global_strong = true;
for temperature = temperatures
    tf = sprintf('T%d',temperature); static_state = baseline.static.(tf);
    params = formal_frozen_parameters(baseline,static_state);
    mappings = struct();
    for bearing_index = 1:numel(bearings)
        bearing = bearings{bearing_index};
        mappings.(bearing) = build_stage_f_rolling_element_linearization_mapping( ...
            baseline,temperature,bearing);
    end
    for scenario_index = 1:numel(scenarios)
        scenario = scenarios{scenario_index};
        qhat = baseline.frequency_response.(tf).(scenario).qhat_full;
        for bearing_index = 1:numel(bearings)
            bearing = bearings{bearing_index};
            recovered = recover_stage_f_rolling_element_1X_loads( ...
                mappings.(bearing),qhat);
            recovered.stage_f_source_commit = identity.source_commit;
            recovered.static_state_source_commit = ...
                baseline.meta.stage_d_source_commit;
            recovered.contact_force_resultant = ...
                recovered.contact_load_resultant;
            candidate.bearing_contact.(tf).(scenario).(bearing) = recovered;
            [global_hard,global_strong,first_trigger] = accumulate_load_gate( ...
                global_hard,global_strong,first_trigger,recovered, ...
                temperature,scenario,bearing);
        end
    end
    for bearing_index = 1:numel(bearings)
        bearing = bearings{bearing_index}; mapping = mappings.(bearing);
        evaluator = formal_evaluator( ...
            repository_root,baseline,static_state,tf,params);
        request = struct( ...
            'evaluation_mode','FORMAL_FROZEN_NONLINEAR_BEARING_FORCE', ...
            'scenario','NOMINAL','phase_count',32, ...
            'temperature_case_C',temperature,'bearing',bearing, ...
            'bearing_index',bearing_index,'q_static',static_state.q_static, ...
            'qhat_full',baseline.frequency_response.(tf).NOMINAL.qhat_full, ...
            'mapping_snapshot',mapping,'formal_parameters',params, ...
            'frozen_thermal_state',static_state.thermal_state, ...
            'contact_state_snapshot',static_state.(['bearing_state_' bearing]), ...
            'static_state_source',['results.static.' tf], ...
            'response_source',['results.frequency_response.' tf '.NOMINAL.qhat_full'], ...
            'thermal_state_source',['results.static.' tf '.thermal_state'], ...
            'canonical_sha256',expected_canonical_sha256, ...
            'thermal_state_frozen',true,'thermal_update_allowed',false, ...
            'static_resolve_allowed',false,'frequency_resolve_allowed',false);
        thermal_before = stage_f_frozen_summary(static_state,bearing);
        scan = evaluate_stage_f_nonlinear_bearing_force_scan(request,evaluator);
        thermal_after = stage_f_frozen_summary(static_state,bearing);
        harmonics = compute_stage_f_bearing_force_harmonics( ...
            scan.exact_dynamic_force_history,scan.phase_values_rad);
        gate = merge_scan_and_gate(scan,harmonics, ...
            candidate.bearing_contact.(tf).NOMINAL.(bearing));
        gate.thermal_frozen_summary = struct( ...
            'before',thermal_before,'after',thermal_after);
        candidate.nonlinearity_gate.(tf).(bearing) = gate;
        manifest_index = manifest_index+1;
        manifest(manifest_index) = struct('temperature_case_C',temperature, ...
            'bearing',bearing,'scenario','NOMINAL','phase_count',32, ...
            'thermal_state_frozen',true, ...
            'evaluator_function','nonlinear_bearing_force');
        [global_hard,global_strong,first_trigger] = accumulate_scan_gate( ...
            global_hard,global_strong,first_trigger,gate,temperature,bearing);
    end
end

if global_hard
    final_gate = 'REPRESENTATIVE_NONLINEAR_VALIDATION_REQUIRED';
    allow_stage_g = false;
elseif global_strong
    final_gate = 'FREQUENCY_DOMAIN_LINEARIZATION_ACCEPTED';
    allow_stage_g = true;
else
    final_gate = 'FREQUENCY_DOMAIN_LINEARIZATION_CAUTION';
    allow_stage_g = true;
end
candidate.stage_f_execution_audit = struct('scan_requests',manifest, ...
    'scan_request_count',numel(manifest), ...
    'evaluator_function','nonlinear_bearing_force', ...
    'evaluator_source_sha256', ...
        'd82ae8cc92a1f1fb55d9d0c14da3efa196e9f085ce22abc5cdd2b345f93af5c8', ...
    'thermal_state_frozen',true,'LOW_scans',0,'HIGH_scans',0, ...
    'source_commit',identity.source_commit, ...
    'elapsed_seconds',seconds(datetime('now')-started_at));
candidate.progress.stage_f_load_recovery_complete = true;
candidate.progress.stage_f_nonlinear_scan_complete = true;
candidate.progress.stage_f_complete = true;
candidate.progress.stage_f_gate_status = final_gate;
candidate.progress.stage_f_first_trigger = first_trigger;
candidate.progress.allow_stage_g = allow_stage_g;
candidate.progress.last_completed_gate = final_gate;
candidate.decision.status = final_gate;
candidate.decision.allow_stage_g = allow_stage_g;
candidate.validation.stage_f = struct('passed',true,'gate_status',final_gate);
validation = validate_stage_f_results(candidate,baseline);
if ~validation.passed
    error('StageF:DiagnosticMismatch', ...
        'STAGE_F_DIAGNOSTIC_MISMATCH: %s',strjoin(validation.diagnostics,','));
end
candidate.validation.stage_f = validation;
if ~validate_stage_f_results(candidate,baseline).passed
    error('StageF:DiagnosticMismatch', ...
        'STAGE_F_DIAGNOSTIC_MISMATCH: saved validation record is inconsistent.');
end
stage_f_canonical_transaction('save',canonical_path,candidate, ...
    expected_canonical_sha256);
results = candidate;
end

function require_independent_validation_contract(repository_root)
transaction_source = fileread(fullfile(repository_root, ...
    'stage_f_canonical_transaction.m'));
stage_f_independent_readonly_validation = ...
    'stage_f_independent_readonly_validation';
matlab_batch_switch = '-batch';
if ~contains(transaction_source,stage_f_independent_readonly_validation) || ...
        ~contains(transaction_source,matlab_batch_switch)
    error('StageF:BaselineMismatch', ...
        ['STAGE_F_BASELINE_MISMATCH: transaction must validate its temporary ', ...
        'candidate in an independent read-only MATLAB process before commit.']);
end
end

function identity = require_stage_f_source(repository_root)
original = pwd; cleanup = onCleanup(@() cd(original)); cd(repository_root);
stage_f_change_scope_expected_files = { ...
    'bearing_microphysics/validation/test_stage_f_rolling_element_loads_and_nonlinearity_gate.m', ...
    'build_stage_f_rolling_element_linearization_mapping.m', ...
    'recover_stage_f_rolling_element_1X_loads.m', ...
    'evaluate_stage_f_nonlinear_bearing_force_scan.m', ...
    'compute_stage_f_bearing_force_harmonics.m', ...
    'validate_stage_f_results.m', ...
    'stage_f_canonical_transaction.m', ...
    'run_stage_f_recover_loads_and_evaluate_nonlinearity.m'};
parent_commit = '7be725a500f4ae3960d5af8e076b98e150fb1dce';
expected_subject = 'feat: add rolling-element load recovery and nonlinear validity gate';
[status_status,status_output] = system('git status --porcelain=v1');
[parent_status,parent_output] = system('git log -1 --format=%P HEAD');
[subject_status,subject_output] = system('git log -1 --format=%s HEAD');
[diff_status,diff_output] = system( ...
    'git diff --name-only 7be725a500f4ae3960d5af8e076b98e150fb1dce..HEAD');
[branch_status,branch_output] = system('git branch --show-current');
[commit_status,commit_output] = system('git rev-parse HEAD');
changed = strsplit(strtrim(diff_output),newline);
if isscalar(changed) && isempty(changed{1}), changed = {}; end
valid = all([status_status parent_status subject_status diff_status ...
    branch_status commit_status] == 0) && isempty(strtrim(status_output)) && ...
    strcmp(strtrim(parent_output),parent_commit) && ...
    strcmp(strtrim(subject_output),expected_subject) && ...
    strcmp(strtrim(branch_output),'thermal-equivalent-damping-frequency-domain-v1') && ...
    isequal(sort(changed),sort(stage_f_change_scope_expected_files));
if ~valid
    error('StageF:BaselineMismatch', ...
        'STAGE_F_BASELINE_MISMATCH: exact clean reviewed Stage F source is required.');
end
identity = struct('source_commit',strtrim(commit_output));
end

function pass = stage_e_baseline_valid(results)
pass = isstruct(results) && isfield(results,'meta') && ...
    isfield(results.meta,'stage_e_source_commit') && ...
    strcmp(results.meta.stage_e_source_commit, ...
        '0cab3dc49dfffc4192066402cb70302f084cb45d') && ...
    isfield(results,'progress') && isfield(results.progress,'stage_e_complete') && ...
    isequal(results.progress.stage_e_complete,true) && ...
    isfield(results,'decision') && strcmp(results.decision.status, ...
        'FOUR_TEMPERATURE_1X_RESPONSES_ACCEPTED') && ...
    isfield(results,'validation') && isfield(results.validation,'stage_e') && ...
    isequal(results.validation.stage_e.passed,true);
if ~pass, return; end
for temperature = [20 50 80 100]
    tf = sprintf('T%d',temperature);
    pass = pass && isfield(results.static,tf) && ...
        all(isfield(results.static.(tf),{'q_static','thermal_state', ...
        'bearing_state_front','bearing_state_rear'}));
    for scenario = {'LOW','NOMINAL','HIGH'}
        pass = pass && isfield(results.frequency_response.(tf),scenario{1}) && ...
            isequal(size(results.frequency_response.(tf).(scenario{1}).qhat_full),[192 1]) && ...
            all(isfinite(results.frequency_response.(tf).(scenario{1}).qhat_full));
    end
end
end

function params = formal_frozen_parameters(results,static_state)
params = initial_conditions();
[~,~,~,model_info] = build_rotor_case_model(params);
params.modelInfo = model_info;
params.num_rotor_dof = model_info.num_rotor_dof;
params.num_case_dof = model_info.num_case_dof;
params.omega = results.configuration.rotational_speed_rad_s;
params.microphysics = microphysics_config(struct('thermal', ...
    struct('enabled',true,'mode','frozen_external'), ...
    'thermal_state',static_state.thermal_state));
end

function evaluator = formal_evaluator(root,results,static_state,tf,parameters)
evaluator = struct('function_handle',@nonlinear_bearing_force, ...
    'function_name','nonlinear_bearing_force', ...
    'source_file',fullfile(root,'nonlinear_bearing_force.m'), ...
    'source_sha256','d82ae8cc92a1f1fb55d9d0c14da3efa196e9f085ce22abc5cdd2b345f93af5c8', ...
    'formal_static_geometry_source','nonlinear_bearing_force/stage4a_bearing_force', ...
    'frozen_thermal_state',static_state.thermal_state, ...
    'frozen_bearing_configuration',parameters.bearing, ...
    'thermal_state_source',['results.static.' tf '.thermal_state'], ...
    'stage_d_source_commit',results.meta.stage_d_source_commit, ...
    'stage_e_source_commit',results.meta.stage_e_source_commit, ...
    'thermal_state_frozen',true,'thermal_update_allowed',false, ...
    'canonical_write_allowed',false);
end

function output = merge_scan_and_gate(scan,harmonics,recovered)
output = scan;
for name = fieldnames(harmonics).'
    output.(name{1}) = harmonics.(name{1});
end
values = recovered.slice_level.r_delta_slice( ...
    recovered.slice_level.loaded_mask_static_slice);
if isempty(values), maximum = NaN; else, maximum = max(values); end
loss = any(recovered.slice_level.potential_contact_loss_slice(:));
hard = loss || (isfinite(maximum) && maximum > 0.20) || ...
    output.active_set_changed || output.epsilon_NL > 0.10 || ...
    output.H2_H1 > 0.10 || output.H3_H1 > 0.10;
strong = ~hard && (~isfinite(maximum) || maximum <= 0.10) && ...
    output.epsilon_NL <= 0.05 && output.H2_H1 <= 0.05 && output.H3_H1 <= 0.05;
if hard
    status = 'REPRESENTATIVE_NONLINEAR_VALIDATION_REQUIRED';
elseif strong
    status = 'FREQUENCY_DOMAIN_LINEARIZATION_ACCEPTED';
else
    status = 'FREQUENCY_DOMAIN_LINEARIZATION_CAUTION';
end
output.maximum_r_delta_nominal = maximum;
output.potential_contact_loss_nominal = loss;
output.gate_status = status;
end

function [hard,strong,trigger] = accumulate_load_gate( ...
        hard,strong,trigger,recovered,temperature,scenario,bearing)
loss = find(recovered.slice_level.potential_contact_loss_slice,1);
limit = find(recovered.slice_level.r_delta_slice > 0.20 & ...
    recovered.slice_level.loaded_mask_static_slice,1);
value = recovered.hard_gate.maximum_loaded_slice_r_delta;
strong = strong && (~isfinite(value) || value <= 0.10);
if ~isempty(loss) || ~isempty(limit)
    hard = true;
    if isempty(trigger)
        if ~isempty(loss)
            index = loss; metric = 'POTENTIAL_CONTACT_LOSS';
            trigger_value = recovered.slice_level.Qmin_linear_slice(index);
            threshold = 0;
        else
            index = limit; metric = 'LOCAL_LINEARITY_LIMIT_EXCEEDED';
            trigger_value = recovered.slice_level.r_delta_slice(index);
            threshold = 0.20;
        end
        [roller_index,slice_index] = ind2sub( ...
            size(recovered.slice_level.loaded_mask_static_slice),index);
        trigger = struct('temperature_case_C',temperature,'scenario',scenario, ...
            'bearing',bearing,'roller_index',roller_index, ...
            'slice_index',slice_index,'metric',metric, ...
            'phase_index',NaN,'phase_rad',NaN, ...
            'slice_indices',slice_index,'trigger_value',trigger_value, ...
            'threshold',threshold,'temperature',temperature,'phase',NaN, ...
            'roller_id',roller_index,'slice_id',slice_index);
    end
end
end

function [hard,strong,trigger] = accumulate_scan_gate( ...
        hard,strong,trigger,gate,temperature,bearing)
failed = strcmp(gate.gate_status,'REPRESENTATIVE_NONLINEAR_VALIDATION_REQUIRED');
strong = strong && strcmp(gate.gate_status,'FREQUENCY_DOMAIN_LINEARIZATION_ACCEPTED');
if failed
    hard = true;
    if isempty(trigger)
        if gate.active_set_changed
            metric = 'ACTIVE_CONTACT_SET_CHANGED';
            change = gate.first_active_set_change;
            phase_index = change.phase_index; phase_rad = change.phase_rad;
            slice_indices = change.slice_indices; trigger_value = 1; threshold = 0;
            [roller_ids,slice_ids] = decode_active_contact_indices( ...
                bearing,slice_indices);
            roller_index = roller_ids(1); slice_index = slice_ids(1);
        elseif gate.epsilon_NL > 0.10
            metric = 'EPSILON_NL';
            phase_index = NaN; phase_rad = NaN; slice_indices = [];
            trigger_value = gate.epsilon_NL; threshold = 0.10;
            roller_ids = []; slice_ids = [];
            roller_index = NaN; slice_index = NaN;
        elseif gate.H2_H1 > 0.10
            metric = 'H2_H1';
            phase_index = NaN; phase_rad = NaN; slice_indices = [];
            trigger_value = gate.H2_H1; threshold = 0.10;
            roller_ids = []; slice_ids = [];
            roller_index = NaN; slice_index = NaN;
        else
            metric = 'H3_H1';
            phase_index = NaN; phase_rad = NaN; slice_indices = [];
            trigger_value = gate.H3_H1; threshold = 0.10;
            roller_ids = []; slice_ids = [];
            roller_index = NaN; slice_index = NaN;
        end
        trigger = struct('temperature_case_C',temperature,'scenario','NOMINAL', ...
            'bearing',bearing,'roller_index',roller_index, ...
            'slice_index',slice_index,'metric',metric, ...
            'phase_index',phase_index,'phase_rad',phase_rad, ...
            'slice_indices',slice_indices,'trigger_value',trigger_value, ...
            'threshold',threshold,'temperature',temperature, ...
            'phase',phase_rad,'roller_id',roller_ids,'slice_id',slice_ids);
    end
end
end

function [roller_ids,slice_ids] = decode_active_contact_indices(bearing,linear_indices)
if strcmp(bearing,'front')
    contact_shape = [22 1];
elseif strcmp(bearing,'rear')
    contact_shape = [30 9];
else
    error('StageF:ActiveContactIndex', ...
        'STAGE_F_COMPUTATION_FAILED: unknown bearing for active-contact index.');
end
linear_indices = reshape(linear_indices,1,[]);
if isempty(linear_indices) || any(linear_indices < 1) || ...
        any(linear_indices > prod(contact_shape)) || ...
        any(linear_indices ~= floor(linear_indices))
    error('StageF:ActiveContactIndex', ...
        'STAGE_F_COMPUTATION_FAILED: invalid active-contact linear index.');
end
[roller_ids,slice_ids] = ind2sub(contact_shape,linear_indices);
roller_ids = reshape(roller_ids,1,[]);
slice_ids = reshape(slice_ids,1,[]);
end

function summary = stage_f_frozen_summary(static_state,bearing)
if strcmp(bearing,'front')
    thermal = static_state.thermal_state.ball;
elseif strcmp(bearing,'rear')
    thermal = static_state.thermal_state.roller;
else
    error('StageF:FrozenThermalSummary', ...
        'STAGE_F_COMPUTATION_FAILED: unknown bearing thermal state.');
end
contact_state = static_state.(['bearing_state_' bearing]);
summary = struct('temperature_C',thermal.T_final, ...
    'viscosity_Pa_s',thermal.eta,'clearance_m',thermal.working_clearance, ...
    'contact_state_sha256',stage_f_value_sha256(contact_state));
end

function hash = stage_f_value_sha256(value)
encoded = jsonencode(value,'ConvertInfAndNaN',true);
bytes = unicode2native(encoded,'UTF-8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(typecast(uint8(bytes),'int8'));
raw = typecast(digest.digest(),'uint8');
hash = lower(reshape(dec2hex(raw,2).',1,[]));
end

function hash = stage_f_file_sha256(path)
fid = fopen(path,'rb');
if fid < 0, hash = ''; return; end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid,Inf,'*uint8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(typecast(bytes,'int8'));
raw = typecast(digest.digest(),'uint8');
hash = lower(reshape(dec2hex(raw,2).',1,[]));
end
