function results = run_stage_e_build_four_temperature_1X_responses(mode)
%RUN_STAGE_E_BUILD_FOUR_TEMPERATURE_1X_RESPONSES One formal Stage E run.

repository_root = fileparts(mfilename('fullpath'));
if nargin == 1 && strcmp(mode,'READ_ONLY_SINGLE_CASE_SOLVE_QUALITY_PROBE')
    canonical_path = fullfile(repository_root,'results', ...
        'thermal_equivalent_damping_frequency_domain', ...
        'thermal_4T_frequency_domain_results.mat');
    artifact = load(canonical_path);
    r = artifact.results; cfg = r.configuration;
    quality_config = build_equivalent_damping_frequency_domain_config();
    spin_rate = cfg.('rotational_speed_rad_s');
    excitation_rate = cfg.('omega_1X_rad_s');
    validator_Fhat = reconstruct_probe_force(cfg,r.meta.model_dof_count, ...
        spin_rate,excitation_rate);
    solver_Fhat = validator_Fhat;
    response = solve_stage_e_full_order_1X_case(r.static.T20.M, ...
        r.static.T20.G,r.static.T50.K_tangent, ...
        r.damping.C_formal_NOMINAL,solver_Fhat,spin_rate,excitation_rate, ...
        struct('temperature_case_C',50,'scenario','NOMINAL'));
    response = audit_read_only_probe_response(r.static.T20.M, ...
        r.static.T20.G,r.static.T50.K_tangent, ...
        r.damping.C_formal_NOMINAL,validator_Fhat,solver_Fhat, ...
        spin_rate,excitation_rate,response,quality_config.stage_e.solve_quality);
    response.Fhat = solver_Fhat;
    results = struct('probe_mode', ...
        'READ_ONLY_SINGLE_CASE_SOLVE_QUALITY_PROBE','read_only',true, ...
        'input_source','CANONICAL_READ_ONLY_T50_NOMINAL', ...
        'source_canonical_sha256',stage_e_file_sha256(canonical_path), ...
        'response',response);
    print_probe_diagnostics(response);
    if any(strcmp(response.solve_quality_gate,{ ...
            'STAGE_E_DYNAMIC_STIFFNESS_RECONSTRUCTION_MISMATCH', ...
            'STAGE_E_DIAGNOSTIC_MISMATCH'}))
        error('StageE:ReadOnlyProbeMismatch','%s',response.solve_quality_gate);
    end
    return;
elseif nargin ~= 0
    error('StageE:ProbeMode','Unsupported Stage E runner mode.');
end
identity = require_stage_e_source(repository_root);
canonical_path = fullfile(repository_root,'results', ...
    'thermal_equivalent_damping_frequency_domain', ...
    'thermal_4T_frequency_domain_results.mat');
pre_audit = stage_e_canonical_transaction('audit',canonical_path);
if ~pre_audit.passed
    error('StageE:CanonicalResultArtifactConflict', ...
        'CANONICAL_RESULT_ARTIFACT_CONFLICT: canonical directory is not clean.');
end
artifact = load(canonical_path);
stage_d = validate_stage_d_four_temperature_results(artifact);
if ~stage_d.passed || ~stage_d.stage_d_complete || ...
        ~artifact.results.decision.allow_stage_e
    error('StageE:BaselineMismatch', ...
        'STAGE_E_BASELINE_MISMATCH: independently accepted Stage D is required.');
end
results = artifact.results;
snapshot_before = stage_e_frozen_input_snapshot(results);

cfg = results.configuration;
if cfg.rotational_speed_rpm ~= 9900 || cfg.frequency_1X_Hz ~= 165 || ...
        abs(cfg.rotational_speed_rad_s-2*pi*165) > eps(2*pi*165) || ...
        abs(cfg.omega_1X_rad_s-2*pi*165) > eps(2*pi*165) || ...
        cfg.unbalance.rotor_node ~= 16 || cfg.unbalance.mass_kg ~= 1e-3 || ...
        cfg.unbalance.eccentricity_m ~= 1e-3 || ...
        cfg.unbalance.unbalance_kg_m ~= 1e-6 || cfg.unbalance.phase_rad ~= 0
    error('StageE:ForceDefinition','Formal 9900 rpm R16 unbalance definition changed.');
end
Omega = cfg.rotational_speed_rad_s;
omega = cfg.omega_1X_rad_s;
n = results.meta.model_dof_count;
params = initial_conditions();
params.omega = Omega;
params.unbalance.nodes = cfg.unbalance.rotor_node;
params.unbalance.mass_g = cfg.unbalance.mass_kg*1e3;
params.unbalance.ecc_mm = cfg.unbalance.eccentricity_m*1e3;
params.unbalance.phase = cfg.unbalance.phase_rad;
formal_force = @(t) unbalance_force(t,params,n);
quarter_force = formal_force(pi/(2*omega));
declared_force_dofs = reshape(find(formal_force(0) ~= 0 | quarter_force ~= 0),1,[]);
force_context = struct('model_dof_count',n,'Omega_rotor_rad_s',Omega, ...
    'omega_exc_rad_s',omega,'unbalance_mass_kg',cfg.unbalance.mass_kg, ...
    'eccentricity_m',cfg.unbalance.eccentricity_m, ...
    'phase_rad',cfg.unbalance.phase_rad,'unbalance_node',cfg.unbalance.rotor_node, ...
    'radial_dofs',declared_force_dofs,'mapping_source','FORMAL_UNBALANCE_FORCE_SUPPORT', ...
    'formal_force_at_time',formal_force);
complex_force = build_stage_e_complex_unbalance_force(force_context);
if ~complex_force.force_amplitude_gate_passed
    error('StageE:ForceDefinition','Formal unbalance force amplitude gate failed.');
end
mapping = build_stage_e_observation_mapping( ...
    results.static.T20,cfg,complex_force.nonzero_dofs);
force_definition = struct('rotational_speed_rpm',9900,'frequency_exc_Hz',165, ...
    'Omega_rotor_rad_s',Omega,'omega_exc_rad_s',omega, ...
    'requested_label','R16','actual_node',mapping.actual_node, ...
    'unbalance_node',cfg.unbalance.rotor_node, ...
    'actual_global_dofs',mapping.actual_global_dofs, ...
    'unbalance_mass_kg',cfg.unbalance.mass_kg, ...
    'eccentricity_m',cfg.unbalance.eccentricity_m, ...
    'unbalance_U_kg_m',cfg.unbalance.unbalance_kg_m, ...
    'phase_rad',cfg.unbalance.phase_rad,'mapping_source',complex_force.mapping_source);
if ~strcmp(mapping.requested_label,force_definition.requested_label) || ...
        mapping.actual_node ~= force_definition.actual_node || ...
        ~isequal(mapping.actual_global_dofs,force_definition.actual_global_dofs)
    error('StageE:ForceDefinition','Formal force and R16 observation provenance differ.');
end

damping = struct('LOW',results.damping.C_formal_LOW, ...
    'NOMINAL',results.damping.C_formal_NOMINAL, ...
    'HIGH',results.damping.C_formal_HIGH);
observation_dofs = unique([mapping.rotor.R2 mapping.rotor.R10 ...
    mapping.casing.C2 mapping.casing.C8]);
modal_audit_fn = @(M,K,C,f,d) compute_stage_e_temperature_modal_audit(M,K,C,f,d);
temperatures = [20 50 80 100];
modal_audits = struct(); modal = struct('T20',results.modal.T20);
actual_zeta_4T = struct();
for temperature = temperatures
    field = sprintf('T%d',temperature);
    if temperature == 20
        K_modal = results.damping.K_ref_20C;
    else
        K_modal = results.static.(field).K_tangent;
    end
    audit = modal_audit_fn(results.static.T20.M,K_modal,damping, ...
        cfg.frequency_1X_Hz,observation_dofs);
    audit.temperature_case_C = temperature;
    audit.schema_version = 'stage-e-modal-audit-v1';
    modal_audits.(field) = audit;
    actual_zeta_4T.(field) = audit.actual_zeta;
    if temperature ~= 20, modal.(field) = audit; end
end
assert_T20_regression(modal_audits.T20,results.modal.T20);

schedule = build_stage_e_case_schedule( ...
    cfg.temperature_cases_C,cfg.damping_scenarios.names);
frequency_response = struct();
allowed_failure_gates = {'FREQUENCY_RESPONSE_BACKWARD_ERROR_FAILED', ...
    'FREQUENCY_RESPONSE_RANK_FAILED','FREQUENCY_RESPONSE_NONFINITE_FAILED', ...
    'FREQUENCY_RESPONSE_NEAR_ZERO_FAILED', ...
    'SEVERELY_ILL_CONDITIONED_DYNAMIC_STIFFNESS'};
for k = 1:numel(schedule)
    solver_fn = @(M,G,K,C,F,O,w,c) solve_stage_e_full_order_1X_case(M,G,K,C,F,O,w,c);
    metric_fn = @(q,w,m) extract_stage_e_frequency_response_metrics(q,w,m);
    item = schedule(k); field = sprintf('T%d',item.temperature_case_C);
    if item.temperature_case_C == 20
        K = results.static.T20.K_tangent_original;
    else
        K = results.static.(field).K_tangent;
    end
    response = solver_fn(results.static.T20.M,results.static.T20.G,K, ...
        damping.(item.scenario),complex_force.Fhat,Omega,omega,item);
    if ~response.accepted
        if ~any(strcmp(response.failure_gate,allowed_failure_gates))
            response.failure_gate = 'FREQUENCY_RESPONSE_NONFINITE_FAILED';
        end
        error('StageE:FormalResponseFailed', ...
            'FIRST_FAILED_CASE=%s; FIRST_FAILED_GATE=%s; canonical unchanged.', ...
            item.case_id,response.solve_quality_gate);
    end
    response.metrics = metric_fn(response.qhat_full,omega,mapping);
    response.dynamic_contact_used = false;
    response.newmark_used = false;
    response.nonlinear_bearing_used = false;
    response.frequency_exc_Hz = 165;
    response.force_definition = force_definition;
    response.Fhat = complex_force.Fhat;
    response.mapping_snapshot = mapping;
    response.source_commit = identity.source_commit;
    metric_names = {'bearing_interface_metrics','rotor_metrics','casing_metrics', ...
        'orbit_metrics','transfer_metrics','phase_metrics'};
    for metric_index = 1:numel(metric_names)
        name = metric_names{metric_index};
        response.(name) = response.metrics.(name);
    end
    response.schema_version = 'stage-e-response-v1';
    frequency_response.(field).(item.scenario) = response;
end

snapshot_after = stage_e_frozen_input_snapshot(results);
if ~isequaln(snapshot_before,snapshot_after)
    error('StageE:FrozenInputChanged', ...
        'FROZEN_STAGE_A_TO_D_INPUT_CHANGED: canonical unchanged.');
end
force_audit = struct('passed',complex_force.four_phase_reconstruction_error <= 1e-12, ...
    'R16_actual_dofs',complex_force.nonzero_dofs, ...
    'force_amplitude_N',complex_force.force_amplitude_N, ...
    'force_support_matches_mapping', ...
    isequal(complex_force.nonzero_dofs,mapping.rotor.R16), ...
    'source','FORMAL_FOUR_PHASE_UNBALANCE_FORCE_AUDIT');
mapping_audit = struct('passed',mapping.validated && ...
    isequal(mapping.rotor.R16,complex_force.nonzero_dofs), ...
    'R16_actual_supported',true, ...
    'force_nonzero_dofs',complex_force.nonzero_dofs, ...
    'source','FORMAL_STAGE_E_OBSERVATION_MAPPING_AUDIT');
payload = struct('frequency_response',frequency_response,'modal',modal, ...
    'modal_audits',modal_audits,'actual_zeta_4T',actual_zeta_4T, ...
    'complex_force',complex_force,'mapping_snapshot',mapping, ...
    'force_definition',force_definition, ...
    'mapping_audit',mapping_audit,'force_audit',force_audit, ...
    'source_commit',identity.source_commit,'dynamic_contact_used',false, ...
    'newmark_used',false,'nonlinear_bearing_used',false, ...
    'schema_version','stage-e-payload-v1', ...
    'additional_results_check',pre_audit);
[candidate,~] = update_stage_e_canonical_results( ...
    results,payload,identity.source_commit);
candidate_validation = validate_stage_e_four_temperature_1X_results( ...
    struct('results',candidate));
if ~candidate_validation.passed
    error('StageE:CanonicalResultArtifactConflict', ...
        'CANONICAL_RESULT_ARTIFACT_CONFLICT: in-memory candidate failed validation.');
end
stage_e_canonical_transaction('save',canonical_path,candidate);
results = candidate;
disp('STAGE_E_CANONICAL_MAT_UPDATED_ONCE_PENDING_INDEPENDENT_RELOAD');
disp('PENDING_INDEPENDENT_RELOAD');
end

function identity = require_stage_e_source(repository_root)
original = pwd; cleanup = onCleanup(@() cd(original));
cd(repository_root);
expected = sort({'bearing_microphysics/validation/test_stage_e_full_order_1X_frequency_responses.m', ...
    'solve_stage_e_full_order_1X_case.m', ...
    'validate_stage_e_four_temperature_1X_results.m', ...
    'run_stage_e_build_four_temperature_1X_responses.m', ...
    'build_equivalent_damping_frequency_domain_config.m', ...
    'evaluate_stage_e_linear_solve_quality.m', ...
    'update_stage_e_canonical_results.m'});
[status_status,status_output] = system('git status --porcelain=v1');
[parent_status,parent_output] = system('git log -1 --format=%P HEAD');
[subject_status,subject_output] = system('git log -1 --format=%s HEAD');
[diff_status,diff_output] = system('git diff --name-only 1c77b45b7da04057167e79061308fe2d96477101..HEAD');
[branch_status,branch_output] = system('git branch --show-current');
[commit_status,commit_output] = system('git rev-parse HEAD');
changed = strsplit(strtrim(diff_output),newline);
if isscalar(changed) && isempty(changed{1}), changed = {}; end
changed = sort(changed);
command_failed = status_status ~= 0 || parent_status ~= 0 || ...
    subject_status ~= 0 || diff_status ~= 0 || ...
    branch_status ~= 0 || commit_status ~= 0;
valid = ~command_failed && ...
    isempty(strtrim(status_output)) && ...
    strcmp(strtrim(parent_output),'1c77b45b7da04057167e79061308fe2d96477101') && ...
    strcmp(strtrim(subject_output),'fix: use backward-error gate for Stage E linear solves') && ...
    strcmp(strtrim(branch_output),'thermal-equivalent-damping-frequency-domain-v1') && ...
    isequal(changed,expected);
if ~valid
    error('StageE:BaselineMismatch', ...
        'STAGE_E_BASELINE_MISMATCH: exact clean reviewed Stage E source is required.');
end
identity = struct('source_commit',strtrim(commit_output));
end

function hash = stage_e_file_sha256(path)
fid = fopen(path,'rb');
if fid < 0, error('StageE:ProbeRead','Cannot read canonical MAT.'); end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid,Inf,'*uint8');
engine = java.security.MessageDigest.getInstance('SHA-256');
engine.update(bytes);
hash = lower(reshape(dec2hex(typecast(engine.digest(),'uint8'),2).',1,[]));
end

function Fhat = reconstruct_probe_force(cfg,n,Omega,omega)
Fhat = complex(zeros(n,1));
radial_dofs = 6*cfg.unbalance.rotor_node+[-5 -4];
amplitude = cfg.unbalance.unbalance_kg_m*Omega^2;
phases = [0 pi/2 pi 3*pi/2];
samples = zeros(2,4);
for sample_index = 1:4
    rotor_phase = Omega*(phases(sample_index)/omega)+cfg.unbalance.phase_rad;
    samples(:,sample_index) = amplitude*[cos(rotor_phase);sin(rotor_phase)];
end
Fhat(radial_dofs) = 0.5*(samples(:,1)-samples(:,3))+ ...
    1i*0.5*(samples(:,4)-samples(:,2));
end

function response = audit_read_only_probe_response( ...
        M,G,K,C,validator_Fhat,solver_Fhat,Omega,omega,response,options)
validator_Z = K-omega^2*M+1i*omega*(C+Omega*G);
solver_semantic_Z = K-response.omega_exc_rad_s^2*M+ ...
    1i*response.omega_exc_rad_s*(C+response.Omega_rotor_rad_s*G);
validator_Z_scale = max(norm(validator_Z,'fro'),realmin('double'));
validator_F_scale = max(norm(validator_Fhat,2),realmin('double'));
validator_Z_relative_difference = ...
    norm(solver_semantic_Z-validator_Z,'fro')/validator_Z_scale;
validator_F_relative_difference = ...
    norm(solver_Fhat-validator_Fhat,2)/validator_F_scale;
validator_residual = validator_Z*response.qhat_full-validator_Fhat;
validator_rhs_relative_residual = norm(validator_residual,2)/ ...
    max(norm(validator_Fhat,2),realmin('double'));
validator_eta_denominator = norm(validator_Z,inf)* ...
    norm(response.qhat_full,inf)+norm(validator_Fhat,inf);
validator_normwise_backward_error_inf = norm(validator_residual,inf)/ ...
    max(validator_eta_denominator,realmin('double'));
validator_rcond_Z = rcond(validator_Z);
validator_finite_solution = all(isfinite(response.qhat_full)) && ...
    all(isfinite(validator_Z),'all') && all(isfinite(validator_Fhat));

response.omega_source_match = isequal(response.omega_exc_rad_s,omega);
response.Omega_source_match = isequal(response.Omega_rotor_rad_s,Omega);
response.solver_validator_Z_relative_difference = ...
    validator_Z_relative_difference;
diagnostic_differences = [ ...
    probe_relative_difference(response.rcond_Z,validator_rcond_Z), ...
    probe_relative_difference(response.rhs_relative_residual, ...
        validator_rhs_relative_residual), ...
    probe_relative_difference(response.normwise_backward_error_inf, ...
        validator_normwise_backward_error_inf)];
if ~isequal(response.finite_solution,validator_finite_solution)
    diagnostic_differences(end+1) = Inf;
end
response.solver_validator_diagnostic_relative_difference = ...
    max(diagnostic_differences);

if ~response.omega_source_match || ~response.Omega_source_match || ...
        validator_Z_relative_difference > 1e-15 || ...
        validator_F_relative_difference > 1e-15
    response.accepted = false;
    response.solve_quality_gate = ...
        'STAGE_E_DYNAMIC_STIFFNESS_RECONSTRUCTION_MISMATCH';
    response.failure_gate = response.solve_quality_gate;
elseif response.solver_validator_diagnostic_relative_difference > ...
        options.diagnostic_relative_match_tolerance
    response.accepted = false;
    response.solve_quality_gate = 'STAGE_E_DIAGNOSTIC_MISMATCH';
    response.failure_gate = response.solve_quality_gate;
end
end

function difference = probe_relative_difference(actual,expected)
if ~(isscalar(actual) && isfinite(actual) && isscalar(expected) && isfinite(expected))
    difference = Inf;
else
    difference = abs(actual-expected)/max(abs(expected),realmin('double'));
end
end

function print_probe_diagnostics(response)
fprintf('rcond_Z=%.17g\n',response.rcond_Z);
fprintf('rhs_relative_residual=%.17g\n',response.rhs_relative_residual);
fprintf('normwise_backward_error_inf=%.17g\n',response.normwise_backward_error_inf);
fprintf('solver_warning_id=%s\n',response.solver_warning_id);
message = regexprep(response.solver_warning_message,'[\r\n]+',' ');
fprintf('solver_warning_message=%s\n',message);
fprintf('refinement_step_count=%d\n',response.refinement_step_count);
if isempty(response.refinement_history)
    before = []; after = []; corrections = [];
else
    before = [response.refinement_history.backward_error_before];
    after = [response.refinement_history.backward_error_after];
    corrections = [response.refinement_history.correction_relative_norm];
end
fprintf('backward_error_before=%s\n',format_probe_vector(before));
fprintf('backward_error_after=%s\n',format_probe_vector(after));
fprintf('correction_relative_norm=%s\n',format_probe_vector(corrections));
fprintf('solver_validator_Z_relative_difference=%.17g\n', ...
    response.solver_validator_Z_relative_difference);
fprintf('solver_validator_diagnostic_relative_difference=%.17g\n', ...
    response.solver_validator_diagnostic_relative_difference);
fprintf('solve_quality_gate=%s\n',response.solve_quality_gate);
end

function text = format_probe_vector(values)
values = reshape(values,1,[]);
if isempty(values), text = '[]'; return; end
parts = arrayfun(@(value) sprintf('%.17g',value),values,'UniformOutput',false);
text = ['[' strjoin(parts,',') ']'];
end

function assert_T20_regression(audit,stored)
frequency_scale = max(norm(stored.natural_frequencies_Hz(1:6)),1);
frequency_pass = norm(audit.first_six_frequency_Hz- ...
    stored.natural_frequencies_Hz(1:6)) <= 1e-10*frequency_scale;
anchor_pass = isequal(stored.anchor_modes,[9 10]) && ...
    norm(audit.natural_frequencies_Hz([9 10])-stored.anchor_frequencies_Hz) <= ...
    1e-10*max(norm(stored.anchor_frequencies_Hz),1);
mass_pass = audit.mass_normalization_error <= 1e-8 && ...
    abs(audit.mass_normalization_error-stored.mass_normalization_error) <= 1e-10;
if ~(frequency_pass && anchor_pass && mass_pass)
    error('StageE:T20ModalRegressionFailed', ...
        'T20_MODAL_REGRESSION_FAILED: canonical unchanged.');
end
end
