function results = run_stage_e_build_four_temperature_1X_responses
%RUN_STAGE_E_BUILD_FOUR_TEMPERATURE_1X_RESPONSES One formal Stage E run.

repository_root = fileparts(mfilename('fullpath'));
identity = require_stage_e_source(repository_root);
canonical_path = fullfile(repository_root,'results', ...
    'thermal_equivalent_damping_frequency_domain', ...
    'thermal_4T_frequency_domain_results.mat');
pre_audit = stage_e_canonical_transaction('audit',canonical_path);
if ~pre_audit.passed
    error('StageE:CanonicalResultArtifactConflict', ...
        'CANONICAL_RESULT_ARTIFACT_CONFLICT: canonical directory is not clean.');
end
artifact = load(canonical_path);
stage_d = validate_stage_d_four_temperature_results(artifact);
if ~stage_d.passed || ~stage_d.stage_d_complete || ...
        ~artifact.results.decision.allow_stage_e
    error('StageE:BaselineMismatch', ...
        'STAGE_E_BASELINE_MISMATCH: independently accepted Stage D is required.');
end
results = artifact.results;
snapshot_before = stage_e_frozen_input_snapshot(results);

cfg = results.configuration;
if cfg.rotational_speed_rpm ~= 9900 || cfg.frequency_1X_Hz ~= 165 || ...
        abs(cfg.rotational_speed_rad_s-2*pi*165) > eps(2*pi*165) || ...
        abs(cfg.omega_1X_rad_s-2*pi*165) > eps(2*pi*165) || ...
        cfg.unbalance.rotor_node ~= 16 || cfg.unbalance.mass_kg ~= 1e-3 || ...
        cfg.unbalance.eccentricity_m ~= 1e-3 || ...
        cfg.unbalance.unbalance_kg_m ~= 1e-6 || cfg.unbalance.phase_rad ~= 0
    error('StageE:ForceDefinition','Formal 9900 rpm R16 unbalance definition changed.');
end
omega = 2*pi*165;
n = results.meta.model_dof_count;
params = initial_conditions();
params.omega = omega;
params.unbalance.nodes = cfg.unbalance.rotor_node;
params.unbalance.mass_g = cfg.unbalance.mass_kg*1e3;
params.unbalance.ecc_mm = cfg.unbalance.eccentricity_m*1e3;
params.unbalance.phase = cfg.unbalance.phase_rad;
formal_force = @(t) unbalance_force(t,params,n);
quarter_force = formal_force(pi/(2*omega));
declared_force_dofs = reshape(find(formal_force(0) ~= 0 | quarter_force ~= 0),1,[]);
force_context = struct('model_dof_count',n,'Omega_rotor_rad_s',omega, ...
    'omega_exc_rad_s',omega,'unbalance_mass_kg',cfg.unbalance.mass_kg, ...
    'eccentricity_m',cfg.unbalance.eccentricity_m, ...
    'phase_rad',cfg.unbalance.phase_rad,'unbalance_node',cfg.unbalance.rotor_node, ...
    'radial_dofs',declared_force_dofs,'mapping_source','FORMAL_UNBALANCE_FORCE_SUPPORT', ...
    'formal_force_at_time',formal_force);
complex_force = build_stage_e_complex_unbalance_force(force_context);
if ~complex_force.force_amplitude_gate_passed
    error('StageE:ForceDefinition','Formal unbalance force amplitude gate failed.');
end
mapping = build_stage_e_observation_mapping( ...
    results.static.T20,cfg,complex_force.nonzero_dofs);
force_definition = struct('rotational_speed_rpm',9900,'frequency_exc_Hz',165, ...
    'Omega_rotor_rad_s',omega,'omega_exc_rad_s',omega, ...
    'requested_label','R16','actual_node',mapping.actual_node, ...
    'unbalance_node',cfg.unbalance.rotor_node, ...
    'actual_global_dofs',mapping.actual_global_dofs, ...
    'unbalance_mass_kg',cfg.unbalance.mass_kg, ...
    'eccentricity_m',cfg.unbalance.eccentricity_m, ...
    'unbalance_U_kg_m',cfg.unbalance.unbalance_kg_m, ...
    'phase_rad',cfg.unbalance.phase_rad,'mapping_source',complex_force.mapping_source);
if ~strcmp(mapping.requested_label,force_definition.requested_label) || ...
        mapping.actual_node ~= force_definition.actual_node || ...
        ~isequal(mapping.actual_global_dofs,force_definition.actual_global_dofs)
    error('StageE:ForceDefinition','Formal force and R16 observation provenance differ.');
end

damping = struct('LOW',results.damping.C_formal_LOW, ...
    'NOMINAL',results.damping.C_formal_NOMINAL, ...
    'HIGH',results.damping.C_formal_HIGH);
observation_dofs = unique([mapping.rotor.R2 mapping.rotor.R10 ...
    mapping.casing.C2 mapping.casing.C8]);
modal_audit_fn = @(M,K,C,f,d) compute_stage_e_temperature_modal_audit(M,K,C,f,d);
temperatures = [20 50 80 100];
modal_audits = struct(); modal = struct('T20',results.modal.T20);
actual_zeta_4T = struct();
for temperature = temperatures
    field = sprintf('T%d',temperature);
    if temperature == 20
        K_modal = results.damping.K_ref_20C;
    else
        K_modal = results.static.(field).K_tangent;
    end
    audit = modal_audit_fn(results.static.T20.M,K_modal,damping, ...
        cfg.frequency_1X_Hz,observation_dofs);
    audit.temperature_case_C = temperature;
    audit.schema_version = 'stage-e-modal-audit-v1';
    modal_audits.(field) = audit;
    actual_zeta_4T.(field) = audit.actual_zeta;
    if temperature ~= 20, modal.(field) = audit; end
end
assert_T20_regression(modal_audits.T20,results.modal.T20);

schedule = build_stage_e_case_schedule( ...
    cfg.temperature_cases_C,cfg.damping_scenarios.names);
frequency_response = struct();
allowed_failure_gates = {'FREQUENCY_RESPONSE_RESIDUAL_FAILED', ...
    'FREQUENCY_RESPONSE_NONFINITE_FAILED','FREQUENCY_RESPONSE_NEAR_ZERO_FAILED', ...
    'SEVERELY_ILL_CONDITIONED_DYNAMIC_STIFFNESS'};
for k = 1:numel(schedule)
    solver_fn = @(M,G,K,C,F,O,w,c) solve_stage_e_full_order_1X_case(M,G,K,C,F,O,w,c);
    metric_fn = @(q,w,m) extract_stage_e_frequency_response_metrics(q,w,m);
    item = schedule(k); field = sprintf('T%d',item.temperature_case_C);
    if item.temperature_case_C == 20
        K = results.static.T20.K_tangent_original;
    else
        K = results.static.(field).K_tangent;
    end
    response = solver_fn(results.static.T20.M,results.static.T20.G,K, ...
        damping.(item.scenario),complex_force.Fhat,omega,omega,item);
    if ~response.accepted
        if ~any(strcmp(response.failure_gate,allowed_failure_gates))
            response.failure_gate = 'FREQUENCY_RESPONSE_NONFINITE_FAILED';
        end
        error('StageE:FormalResponseFailed', ...
            'FIRST_FAILED_CASE=%s; FIRST_FAILED_GATE=%s; canonical unchanged.', ...
            item.case_id,response.failure_gate);
    end
    response.metrics = metric_fn(response.qhat_full,omega,mapping);
    response.dynamic_contact_used = false;
    response.newmark_used = false;
    response.nonlinear_bearing_used = false;
    response.frequency_exc_Hz = 165;
    response.force_definition = force_definition;
    response.Fhat = complex_force.Fhat;
    response.mapping_snapshot = mapping;
    response.source_commit = identity.source_commit;
    metric_names = {'bearing_interface_metrics','rotor_metrics','casing_metrics', ...
        'orbit_metrics','transfer_metrics','phase_metrics'};
    for metric_index = 1:numel(metric_names)
        name = metric_names{metric_index};
        response.(name) = response.metrics.(name);
    end
    response.schema_version = 'stage-e-response-v1';
    frequency_response.(field).(item.scenario) = response;
end

snapshot_after = stage_e_frozen_input_snapshot(results);
if ~isequaln(snapshot_before,snapshot_after)
    error('StageE:FrozenInputChanged', ...
        'FROZEN_STAGE_A_TO_D_INPUT_CHANGED: canonical unchanged.');
end
force_audit = struct('passed',complex_force.four_phase_reconstruction_error <= 1e-12, ...
    'R16_actual_dofs',complex_force.nonzero_dofs, ...
    'force_amplitude_N',complex_force.force_amplitude_N, ...
    'force_support_matches_mapping', ...
    isequal(complex_force.nonzero_dofs,mapping.rotor.R16), ...
    'source','FORMAL_FOUR_PHASE_UNBALANCE_FORCE_AUDIT');
mapping_audit = struct('passed',mapping.validated && ...
    isequal(mapping.rotor.R16,complex_force.nonzero_dofs), ...
    'R16_actual_supported',true, ...
    'force_nonzero_dofs',complex_force.nonzero_dofs, ...
    'source','FORMAL_STAGE_E_OBSERVATION_MAPPING_AUDIT');
payload = struct('frequency_response',frequency_response,'modal',modal, ...
    'modal_audits',modal_audits,'actual_zeta_4T',actual_zeta_4T, ...
    'complex_force',complex_force,'mapping_snapshot',mapping, ...
    'force_definition',force_definition, ...
    'mapping_audit',mapping_audit,'force_audit',force_audit, ...
    'source_commit',identity.source_commit,'dynamic_contact_used',false, ...
    'newmark_used',false,'nonlinear_bearing_used',false, ...
    'schema_version','stage-e-payload-v1', ...
    'additional_results_check',pre_audit);
[candidate,~] = update_stage_e_canonical_results( ...
    results,payload,identity.source_commit);
candidate_validation = validate_stage_e_four_temperature_1X_results( ...
    struct('results',candidate));
if ~candidate_validation.passed
    error('StageE:CanonicalResultArtifactConflict', ...
        'CANONICAL_RESULT_ARTIFACT_CONFLICT: in-memory candidate failed validation.');
end
stage_e_canonical_transaction('save',canonical_path,candidate);
results = candidate;
disp('STAGE_E_CANONICAL_MAT_UPDATED_ONCE_PENDING_INDEPENDENT_RELOAD');
disp('PENDING_INDEPENDENT_RELOAD');
end

function identity = require_stage_e_source(repository_root)
original = pwd; cleanup = onCleanup(@() cd(original));
cd(repository_root);
expected = sort({'bearing_microphysics/validation/test_stage_d_four_temperature_static_states.m', ...
    'bearing_microphysics/validation/test_stage_e_full_order_1X_frequency_responses.m', ...
    'build_stage_e_complex_unbalance_force.m','build_stage_e_case_schedule.m', ...
    'solve_stage_e_full_order_1X_case.m','extract_stage_e_frequency_response_metrics.m', ...
    'compute_stage_e_temperature_modal_audit.m','build_stage_e_observation_mapping.m', ...
    'stage_e_frozen_input_snapshot.m','update_stage_e_canonical_results.m', ...
    'validate_stage_e_four_temperature_1X_results.m','stage_e_canonical_transaction.m', ...
    'run_stage_e_build_four_temperature_1X_responses.m'});
[status_status,status_output] = system('git status --porcelain=v1');
[parent_status,parent_output] = system('git log -1 --format=%P HEAD');
[subject_status,subject_output] = system('git log -1 --format=%s HEAD');
[diff_status,diff_output] = system('git diff --name-only 23a975c2c762504dc4ae62f07379737582fd783f..HEAD');
[branch_status,branch_output] = system('git branch --show-current');
[commit_status,commit_output] = system('git rev-parse HEAD');
changed = strsplit(strtrim(diff_output),newline);
if isscalar(changed) && isempty(changed{1}), changed = {}; end
changed = sort(changed);
command_failed = status_status ~= 0 || parent_status ~= 0 || ...
    subject_status ~= 0 || diff_status ~= 0 || ...
    branch_status ~= 0 || commit_status ~= 0;
valid = ~command_failed && ...
    isempty(strtrim(status_output)) && ...
    strcmp(strtrim(parent_output),'23a975c2c762504dc4ae62f07379737582fd783f') && ...
    strcmp(strtrim(subject_output),'feat: add full-order 1X thermal frequency responses') && ...
    strcmp(strtrim(branch_output),'thermal-equivalent-damping-frequency-domain-v1') && ...
    isequal(changed,expected);
if ~valid
    error('StageE:BaselineMismatch', ...
        'STAGE_E_BASELINE_MISMATCH: exact clean reviewed Stage E source is required.');
end
identity = struct('source_commit',strtrim(commit_output));
end

function assert_T20_regression(audit,stored)
frequency_scale = max(norm(stored.natural_frequencies_Hz(1:6)),1);
frequency_pass = norm(audit.first_six_frequency_Hz- ...
    stored.natural_frequencies_Hz(1:6)) <= 1e-10*frequency_scale;
anchor_pass = isequal(stored.anchor_modes,[9 10]) && ...
    norm(audit.natural_frequencies_Hz([9 10])-stored.anchor_frequencies_Hz) <= ...
    1e-10*max(norm(stored.anchor_frequencies_Hz),1);
mass_pass = audit.mass_normalization_error <= 1e-8 && ...
    abs(audit.mass_normalization_error-stored.mass_normalization_error) <= 1e-10;
if ~(frequency_pass && anchor_pass && mass_pass)
    error('StageE:T20ModalRegressionFailed', ...
        'T20_MODAL_REGRESSION_FAILED: canonical unchanged.');
end
end
