function results = run_stage_c_build_20C_fixed_damping_envelope
%RUN_STAGE_C_BUILD_20C_FIXED_DAMPING_ENVELOPE One formal 20 C Stage C run.

repository_root = fileparts(mfilename('fullpath'));
identity = require_formal_source_state(repository_root);
cfg = build_equivalent_damping_frequency_domain_config();
canonical_directory = fullfile(repository_root,cfg.result_directory);
canonical_path = fullfile(canonical_directory,cfg.result_mat_name);
assert_canonical_target_available(canonical_directory,canonical_path,identity,cfg);

params = initial_conditions();
[M,~,K_structure,modelInfo] = build_rotor_case_model(params);
n = size(M,1);
[B_front,B_rear,observation_mapping,dof_mapping,bearing_mapping] = ...
    model_mappings(params,modelInfo,n);
model_cache = struct('M',M,'K_structure',K_structure, ...
    'C_foundation',modelInfo.C_foundation,'G_unit',modelInfo.GG, ...
    'modelInfo',modelInfo,'transverse_dofs',transverse_dofs(modelInfo), ...
    'B_ball',B_front,'B_roller',B_rear);

% This is the only formal thermal-mechanical workpoint solve in Stage C.
thermal = solve_thermal_mechanical_outer_loop(params,params.bearing,20,[]);
acceptance = formal_acceptance(thermal,20);
if ~acceptance.passed
    error('StageC:Static20CWorkpointNotAccepted', ...
        '20C_STATIC_WORKPOINT_NOT_ACCEPTED: the formal workpoint was not accepted.');
end

params_frozen = frozen_parameters(params,modelInfo,thermal.thermal_state);
stiffness(1) = linearize_bearing_workpoint(thermal.q_static,params_frozen,1,struct());
stiffness(2) = linearize_bearing_workpoint(thermal.q_static,params_frozen,2,struct());
contacts = thermal.contact_state.bearings;
damping(1) = build_ehl_damping_matrix(contacts(1),contacts(1), ...
    contacts(1).microphysics_state.temperature.contact_geometry,params_frozen.bearing(1));
damping(2) = build_ehl_damping_matrix(contacts(2),contacts(2), ...
    contacts(2).microphysics_state.temperature.contact_geometry,params_frozen.bearing(2));
linearization = validate_workpoint_linearization( ...
    thermal.q_static,params_frozen,stiffness,struct());
if ~all([stiffness.pass]) || ~all([damping.pass]) || ~linearization.pass
    error('StageC:Static20CWorkpointNotAccepted', ...
        ['20C_STATIC_WORKPOINT_NOT_ACCEPTED: the workpoint failed its ', ...
        'stiffness, damping or linearization gate.']);
end

K_bearing = B_front.'*stiffness(1).K_local*B_front + ...
    B_rear.'*stiffness(2).K_local*B_rear;
K_tangent_original = K_structure+K_bearing;
C_ehl_old_full = B_front.'*damping(1).C_local*B_front + ...
    B_rear.'*damping(2).C_local*B_rear;
C_ehl_old_full = 0.5*(C_ehl_old_full+C_ehl_old_full.');

legacy_reference = compute_reference_rayleigh_damping( ...
    params_frozen,stiffness,damping,struct());
if ~legacy_reference.pass
    error('StageC:RUNTIME_LEGACY_DAMPING_EQUIVALENCE_FAILED', ...
        'The actual Baseline 20 C reference state did not pass.');
end
runtime_equivalence = actual_runtime_legacy_gate( ...
    model_cache,stiffness,damping,legacy_reference);
if ~runtime_equivalence.passed
    error('StageC:RUNTIME_LEGACY_DAMPING_EQUIVALENCE_FAILED', ...
        'The actual reduced Baseline damping matrices failed equivalence.');
end

K_ref = 0.5*(K_tangent_original+K_tangent_original.');
C_rayleigh_legacy_full = legacy_reference.alpha_R*M + ...
    legacy_reference.beta_R*K_ref;
envelope = build_fixed_equivalent_damping_envelope_20C( ...
    M,K_tangent_original,modelInfo.C_foundation, ...
    observation_mapping.dof_indices,cfg.frequency_1X_Hz, ...
    cfg.damping_scenarios.target_zeta,C_rayleigh_legacy_full,C_ehl_old_full);

results = assemble_results(identity,cfg,params,modelInfo,thermal,acceptance, ...
    stiffness,damping,linearization,envelope,runtime_equivalence, ...
    dof_mapping,bearing_mapping,observation_mapping);
artifact = struct('results',results);
canonical_validation = validate_stage_c_fixed_damping_envelope(artifact);
if ~canonical_validation.passed
    error('StageC:STAGE_C_RESULT_RELOAD_FAILED', ...
        'The in-memory canonical Stage C structure failed validation.');
end
results.validation.stage_c.canonical_structure_pre_save_passed = true;

if ~isfolder(canonical_directory), mkdir(canonical_directory); end
save(canonical_path,'results');
fprintf('STAGE_C_CANONICAL_MAT_SAVED_PENDING_INDEPENDENT_RELOAD\n');
end

function identity = require_formal_source_state(repository_root)
original = pwd; cleanup = onCleanup(@() cd(original)); cd(repository_root);
[s1,branch] = system('git branch --show-current');
[s2,commit] = system('git rev-parse HEAD');
[s3,dirty] = system('git status --porcelain=v1');
[s4,~] = system('git merge-base --is-ancestor d059b5684eefee63fbc2dda57ea9c8b3342afc32 HEAD');
if any([s1 s2 s3 s4] ~= 0) || ~isempty(strtrim(dirty)) || ...
        ~strcmp(strtrim(branch),'thermal-equivalent-damping-frequency-domain-v1')
    error('StageC:STAGE_C_BASELINE_MISMATCH', ...
        'Stage C requires the clean formal branch descended from Stage B.');
end
identity = struct('branch',strtrim(branch),'source_commit',strtrim(commit), ...
    'baseline_branch','thermal-damping-contribution-audit-v1', ...
    'baseline_commit','2a135aeb99ab4751154f18051b473cc6a7e463fb', ...
    'stage_a_commit','794fb5534af8bdcbf971363e8a7e3df0e6fb9653', ...
    'stage_b_commit','d059b5684eefee63fbc2dda57ea9c8b3342afc32');
end

function assert_canonical_target_available(directory,path,identity,cfg)
if isfolder(directory)
    entries = dir(directory); entries = entries(~[entries.isdir]);
    if any(~strcmp({entries.name},'thermal_4T_frequency_domain_results.mat'))
        error('StageC:CANONICAL_RESULT_ARTIFACT_CONFLICT', ...
            'The canonical result directory contains an unexpected file.');
    end
end
if ~isfile(path), return; end
loaded = load(path); compatible_incomplete = false;
if isequal(fieldnames(loaded),{'results'}) && isstruct(loaded.results) && ...
        all(isfield(loaded.results,{'meta','configuration','progress','static'}))
    meta = loaded.results.meta; progress = loaded.results.progress;
    required_meta = {'branch','baseline_commit','stage_a_commit','stage_b_commit', ...
        'source_commit','analysis_type','damping_model'};
    compatible_incomplete = all(isfield(meta,required_meta)) && ...
        strcmp(char(meta.branch),identity.branch) && ...
        strcmp(char(meta.baseline_commit),identity.baseline_commit) && ...
        strcmp(char(meta.stage_a_commit),identity.stage_a_commit) && ...
        strcmp(char(meta.stage_b_commit),identity.stage_b_commit) && ...
        strcmp(char(meta.source_commit),identity.source_commit) && ...
        strcmp(char(meta.analysis_type),cfg.analysis_type) && ...
        strcmp(char(meta.damping_model),cfg.damping_model) && ...
        isequaln(loaded.results.configuration,cfg) && ...
        isfield(progress,'stage_c_damping_envelope_complete') && ...
        ~progress.stage_c_damping_envelope_complete && ...
        isfield(loaded.results.static,'T20') && ...
        isfield(loaded.results.static.T20,'source_commit') && ...
        strcmp(char(loaded.results.static.T20.source_commit),identity.source_commit);
end
if ~compatible_incomplete
    error('StageC:CANONICAL_RESULT_ARTIFACT_CONFLICT', ...
        'An existing canonical result is incompatible or already complete.');
end
end

function [B_front,B_rear,observation,dofs,bearings] = model_mappings(params,modelInfo,n)
B_front = bearing_map(params.bearing(1),modelInfo,n);
B_rear = bearing_map(params.bearing(2),modelInfo,n);
front_rotor = 6*params.bearing(1).rotor_node+(-5:-4);
rear_rotor = 6*params.bearing(2).rotor_node+(-5:-4);
front_case = modelInfo.num_rotor_dof+6*params.bearing(1).case_node+(-5:-4);
rear_case = modelInfo.num_rotor_dof+6*params.bearing(2).case_node+(-5:-4);
indices = [front_rotor rear_rotor front_case rear_case];
if numel(unique(indices)) ~= 8 || any(indices < 1 | indices > n)
    error('StageC:STAGE_C_CHANGE_SCOPE_EXCEEDED', ...
        'The required front/rear rotor/casing radial mapping is invalid.');
end
observation = struct('dof_indices',indices, ...
    'labels',{{'front_rotor_ux','front_rotor_uy','rear_rotor_ux', ...
    'rear_rotor_uy','front_case_ux','front_case_uy', ...
    'rear_case_ux','rear_case_uy'}},'validated',true);
dofs = struct('model_dof_count',n,'num_rotor_dof',modelInfo.num_rotor_dof, ...
    'num_case_dof',modelInfo.num_case_dof, ...
    'num_rotor_nodes',modelInfo.num_rotor_nodes, ...
    'num_case_nodes',modelInfo.num_case_nodes, ...
    'transverse_dofs',transverse_dofs(modelInfo));
bearings = struct('front_B',B_front,'rear_B',B_rear, ...
    'front_rotor_node',params.bearing(1).rotor_node, ...
    'front_case_node',params.bearing(1).case_node, ...
    'rear_rotor_node',params.bearing(2).rotor_node, ...
    'rear_case_node',params.bearing(2).case_node,'validated',true);
end

function B = bearing_map(bearing,modelInfo,n)
ir = 6*bearing.rotor_node+(-5:-1);
ic = modelInfo.num_rotor_dof+6*bearing.case_node+(-5:-1);
if any([ir ic] < 1 | [ir ic] > n)
    error('StageC:STAGE_C_CHANGE_SCOPE_EXCEEDED','A bearing mapping is outside the model.');
end
B = sparse([1:5 1:5],[ir ic],[ones(1,5) -ones(1,5)],5,n);
end

function indices = transverse_dofs(modelInfo)
indices = [reshape(6*(1:modelInfo.num_rotor_nodes)+[-5;-4;-2;-1],[],1); ...
    modelInfo.num_rotor_dof+reshape( ...
    6*(1:modelInfo.num_case_nodes)+[-5;-4;-2;-1],[],1)];
end

function params = frozen_parameters(params,modelInfo,thermal_state)
params.modelInfo = modelInfo;
params.num_rotor_dof = modelInfo.num_rotor_dof;
params.num_case_dof = modelInfo.num_case_dof;
params.microphysics = microphysics_config(struct('thermal', ...
    struct('enabled',true,'mode','frozen_external'), ...
    'thermal_state',thermal_state));
end

function acceptance = formal_acceptance(thermal,T_oil_C)
static = thermal.static_result;
front_temperature_residual_C = abs(T_oil_C+thermal.Qfric_ball_W/120- ...
    thermal.thermal_state.ball.T_final);
rear_temperature_residual_C = abs(T_oil_C+thermal.Qfric_roller_W/120- ...
    thermal.thermal_state.roller.T_final);
constraint_vector = static.constraint.matrix*static.q;
kkt_residual = [static.residual;constraint_vector];
front_active = isequal(thermal.film_state.ball.loaded_mask, ...
    thermal.contact_state.bearings(1).Q > 0);
rear_active = isequal(thermal.film_state.roller.loaded_mask, ...
    thermal.contact_state.bearings(2).Q > 0);
acceptance = struct('passed',logical(thermal.converged && static.converged && ...
    front_active && rear_active),'mechanical_residual',thermal.mechanical_residual, ...
    'thermal_residual_front_C',front_temperature_residual_C, ...
    'thermal_residual_rear_C',rear_temperature_residual_C, ...
    'thermal_residual_max_C',thermal.temperature_residual_C, ...
    'power_residual_W',thermal.power_residual_W, ...
    'KKT_residual_norm',norm(kkt_residual), ...
    'KKT_normalized_residual',static.normalized_residual, ...
    'constraint_residual_m',norm(constraint_vector,inf), ...
    'complementarity_residual',struct('available',false,'value',NaN, ...
    'status','NOT_PROVIDED_BY_FORMAL_SOLVER'), ...
    'active_set_consistent',front_active && rear_active, ...
    'thermal_outer_iterations',thermal.outer_iterations, ...
    'static_Newton_iterations',static.iterations, ...
    'final_consistency_recompute_count',thermal.final_consistency_recompute_count);
end

function runtime = actual_runtime_legacy_gate(cache,stiffness,damping,reference)
cfg = thermal_outer_loop_config();
shared = struct('reference20',reference, ...
    'Phi_reference30',reference.mode_shapes_full(:,1:cfg.modal.certified_reference_count), ...
    'C_rayleigh_reference_t',reference.C_rayleigh_reference_t, ...
    'current_temperature_C',20);
modal = build_temperature_modal_basis(cache,stiffness,damping,shared,cfg);
if ~modal.pass
    error('StageC:RUNTIME_LEGACY_DAMPING_EQUIVALENCE_FAILED', ...
        'The actual Baseline reduced audit space did not pass.');
end
CR = 0.5*(modal.C_rayleigh_r+modal.C_rayleigh_r.');
CF = 0.5*(modal.C_foundation_r+modal.C_foundation_r.');
CE = 0.5*(modal.C_ehl_r+modal.C_ehl_r.');
CT = 0.5*(modal.C_dissipative_r+modal.C_dissipative_r.');
before = {CR,CF,CE,CT};
runtime = validate_runtime_legacy_damping_equivalence(CR,CF,CE,CT);
if ~isequaln(before,{CR,CF,CE,CT})
    runtime.passed = false;
end
runtime.space = 'REDUCED_AUDIT_SPACE';
runtime.source_fields = {'C_rayleigh_r','C_foundation_r','C_ehl_r','C_dissipative_r'};
runtime.C_rayleigh_r = CR;
runtime.C_foundation_r = CF;
runtime.C_ehl_total_r = CE;
runtime.C_total_r = CT;
runtime.gyroscopic_term_excluded = true;
runtime.runtime_equivalence_pending = false;
end

function results = assemble_results(identity,cfg,params,modelInfo,thermal,acceptance, ...
    stiffness,damping,linearization,envelope,runtime,dofs,bearings,observation)
results = struct();
results.meta = struct('branch',identity.branch, ...
    'baseline_branch',identity.baseline_branch, ...
    'baseline_commit',identity.baseline_commit, ...
    'stage_a_commit',identity.stage_a_commit, ...
    'stage_b_commit',identity.stage_b_commit, ...
    'source_commit',identity.source_commit, ...
    'creation_time',datetime('now'), ...
    'model_dof_count',modelInfo.num_rotor_dof+modelInfo.num_case_dof, ...
    'rotational_speed_rpm',cfg.rotational_speed_rpm, ...
    'analysis_type',cfg.analysis_type,'damping_model',cfg.damping_model, ...
    'dynamic_ehl_used',false,'old_ehl_used_in_formal_response',false, ...
    'newmark_used',false);
results.configuration = cfg;
results.progress = struct('stage_a_complete',true,'stage_b_complete',true, ...
    'stage_c_static_20C_complete',true, ...
    'stage_c_runtime_equivalence_complete',true, ...
    'stage_c_modal_complete',true, ...
    'stage_c_damping_envelope_complete',true, ...
    'last_completed_gate','STAGE_C_DAMPING_ENVELOPE', ...
    'stage_d_complete',false,'stage_e_complete',false, ...
    'stage_f_complete',false,'stage_g_complete',false,'stage_h_complete',false);
results.static.T20 = struct('q_static',thermal.q_static, ...
    'source_commit',identity.source_commit, ...
    'thermal_state',thermal.thermal_state, ...
    'bearing_state_front',thermal.contact_state.bearings(1), ...
    'bearing_state_rear',thermal.contact_state.bearings(2), ...
    'M',envelope.static.M, ...
    'K_tangent_original',envelope.static.K_tangent_original, ...
    'K_ref_symmetric',envelope.static.K_ref_symmetric, ...
    'G',modelInfo.GG,'C_foundation_full',modelInfo.C_foundation, ...
    'dof_mapping',dofs,'bearing_mapping',bearings, ...
    'observation_mapping',observation,'formal_acceptance',acceptance.passed, ...
    'acceptance_residuals',acceptance, ...
    'bearing_stiffness_front',stiffness(1), ...
    'bearing_stiffness_rear',stiffness(2), ...
    'old_ehl_damping_front',damping(1), ...
    'old_ehl_damping_rear',damping(2), ...
    'linearization_validation',linearization, ...
    'rotational_speed_rad_s',params.omega);
results.modal.T20 = envelope.modal;
results.damping = envelope.damping;
runtime.source_commit = identity.source_commit;
results.validation.runtime_legacy_equivalence = runtime;
results.validation.stage_c = envelope.validation;
results.decision = struct( ...
    'status','FIXED_EQUIVALENT_DAMPING_ENVELOPE_ACCEPTED', ...
    'allow_stage_d',true,'stage_d_executed',false);
end
