function state = solve_stage_d_static_temperature_case( ...
    requested_temperature_C,initial_state,params,source_commit)
%SOLVE_STAGE_D_STATIC_TEMPERATURE_CASE One formal static solve at 50/80/100 C.

allowed = [50 80 100]; sources = [20 50 80];
index = find(allowed == requested_temperature_C,1);
if isempty(index) || ~isstruct(initial_state) || ...
        ~isfield(initial_state,'requested_case_temperature_C') || ...
        initial_state.requested_case_temperature_C ~= sources(index) || ...
        ~isfield(initial_state,'q_static') || ...
        ~isequal(size(initial_state.q_static),[192 1]) || ...
        any(~isfinite(initial_state.q_static))
    error('StageD:ContinuationState', ...
        'Stage D requires the immediately preceding accepted q_static as initial guess.');
end

[M,~,K_structure,modelInfo] = build_rotor_case_model(params);
n = size(M,1);
B_front = bearing_map(params.bearing(1),modelInfo,n);
B_rear = bearing_map(params.bearing(2),modelInfo,n);
thermal = solve_thermal_mechanical_outer_loop( ...
    params,params.bearing,requested_temperature_C,initial_state.q_static);
thermal.stage_d_acceptance = formal_acceptance(thermal,requested_temperature_C);
if ~thermal.stage_d_acceptance.formal_acceptance_flag
    error('StageD:FourTemperatureStaticStateFailed', ...
        'FOUR_TEMPERATURE_STATIC_STATE_FAILED: formal static acceptance failed.');
end

params_frozen = frozen_parameters(params,modelInfo,thermal.thermal_state);
stiffness(1) = linearize_bearing_workpoint( ...
    thermal.q_static,params_frozen,1,struct());
stiffness(2) = linearize_bearing_workpoint( ...
    thermal.q_static,params_frozen,2,struct());
linearization = validate_workpoint_linearization( ...
    thermal.q_static,params_frozen,stiffness,struct());
if ~all([stiffness.pass]) || ~linearization.pass
    error('StageD:FourTemperatureStaticStateFailed', ...
        ['FOUR_TEMPERATURE_STATIC_STATE_FAILED: bearing tangent or ', ...
        'workpoint linearization failed.']);
end

model = struct('M',M,'G',modelInfo.GG,'K_structure',K_structure, ...
    'modelInfo',modelInfo,'B_front',B_front,'B_rear',B_rear, ...
    'M_reference',initial_state.M_reference, ...
    'G_reference',initial_state.G_reference);
state = extract_stage_d_static_state(requested_temperature_C, ...
    sources(index),thermal,stiffness,params,model,source_commit);
state.linearization_validation = linearization;
if ~state.validation.passed
    if state.validation.tangent_symmetry_error > 1e-10
        error('StageD:TemperatureTangentStiffnessNotSymmetric', ...
            ['TEMPERATURE_TANGENT_STIFFNESS_NOT_SYMMETRIC: accepted workpoint ', ...
            'tangent exceeds the Stage C tolerance.']);
    end
    error('StageD:FourTemperatureStaticStateFailed', ...
        'FOUR_TEMPERATURE_STATIC_STATE_FAILED: extracted state validation failed.');
end
end

function B = bearing_map(bearing,modelInfo,n)
ir = 6*bearing.rotor_node+(-5:-1);
ic = modelInfo.num_rotor_dof+6*bearing.case_node+(-5:-1);
B = sparse([1:5 1:5],[ir ic],[ones(1,5) -ones(1,5)],5,n);
end

function params = frozen_parameters(params,modelInfo,thermal_state)
params.modelInfo = modelInfo;
params.num_rotor_dof = modelInfo.num_rotor_dof;
params.num_case_dof = modelInfo.num_case_dof;
params.microphysics = microphysics_config(struct('thermal', ...
    struct('enabled',true,'mode','frozen_external'), ...
    'thermal_state',thermal_state));
end

function acceptance = formal_acceptance(thermal,T_oil_C)
static = thermal.static_result;
front_temperature_residual_C = abs(T_oil_C+thermal.Qfric_ball_W/120- ...
    thermal.thermal_state.ball.T_final);
rear_temperature_residual_C = abs(T_oil_C+thermal.Qfric_roller_W/120- ...
    thermal.thermal_state.roller.T_final);
constraint_vector = static.constraint.matrix*static.q;
kkt_residual = [static.residual;constraint_vector];
front_active = isequal(thermal.film_state.ball.loaded_mask, ...
    thermal.contact_state.bearings(1).Q > 0);
rear_active = isequal(thermal.film_state.roller.loaded_mask, ...
    thermal.contact_state.bearings(2).Q > 0);
acceptance = struct('mechanical_residual',thermal.mechanical_residual, ...
    'thermal_residual_front_C',front_temperature_residual_C, ...
    'thermal_residual_rear_C',rear_temperature_residual_C, ...
    'thermal_residual_max_C',thermal.temperature_residual_C, ...
    'power_residual_W',thermal.power_residual_W, ...
    'axial_constraint_error_m',thermal.axial_constraint_error_m, ...
    'relative_Q_change',thermal.relative_Q_change, ...
    'relative_film_change',thermal.relative_film_change, ...
    'kkt_residual_raw',norm(kkt_residual), ...
    'kkt_residual_normalized',static.normalized_residual, ...
    'constraint_residual',norm(constraint_vector,inf), ...
    'complementarity_residual',struct('available',false, ...
    'status','FIELD_NOT_AVAILABLE_IN_FORMAL_SOLVER'), ...
    'active_set_consistency',front_active && rear_active, ...
    'thermal_outer_iterations',thermal.outer_iterations, ...
    'static_newton_iterations',static.iterations, ...
    'final_consistency_recompute_count',thermal.final_consistency_recompute_count, ...
    'thermal_converged',logical(thermal.converged), ...
    'static_converged',logical(static.converged), ...
    'formal_tolerances',struct('temperature_C',1e-3,'power_W',0.12, ...
    'mechanical',1e-6,'axial_m',1e-8,'relative_Q',1e-4, ...
    'relative_film',1e-3), ...
    'formal_acceptance_flag',logical(thermal.converged && static.converged && ...
    front_active && rear_active));
end
