function validation = validate_stage_c_fixed_damping_envelope(artifact)
%VALIDATE_STAGE_C_FIXED_DAMPING_ENVELOPE Recompute canonical artifact gates.

checks = struct();
checks.only_results_top_level = isstruct(artifact) && ...
    isequal(fieldnames(artifact),{'results'});
if ~checks.only_results_top_level
    validation = finish(checks); return;
end
r = artifact.results;
required = {'meta','configuration','progress','static','modal', ...
    'damping','validation','decision'};
checks.required_top_level_fields = isstruct(r) && all(isfield(r,required));
if ~checks.required_top_level_fields || ~isfield(r.static,'T20') || ...
        ~isfield(r.modal,'T20') || ...
        ~isfield(r.validation,'runtime_legacy_equivalence') || ...
        ~isfield(r.validation,'stage_c')
    validation = finish(checks); return;
end

s = r.static.T20; m = r.modal.T20; d = r.damping;
runtime = r.validation.runtime_legacy_equivalence;
checks.meta = required_meta(r.meta);
checks.configuration = isfield(r.configuration,'damping_model') && ...
    strcmp(char(r.configuration.damping_model),'fixed_equivalent_system') && ...
    isfield(r.configuration,'mapping_validation_required') && ...
    logical(r.configuration.mapping_validation_required);
checks.static_schema = required_fields(s,{'q_static','thermal_state', ...
    'bearing_state_front','bearing_state_rear','M','K_tangent_original', ...
    'K_ref_symmetric','G','C_foundation_full','dof_mapping', ...
    'bearing_mapping','observation_mapping','formal_acceptance', ...
    'acceptance_residuals'}) && logical_scalar_field(s,'formal_acceptance',true);
if ~checks.static_schema
    validation = finish(checks); return;
end

n = size(s.M,1);
checks.static_matrices = n >= 6 && valid_square(s.M,n) && ...
    valid_square(s.K_tangent_original,n) && valid_square(s.K_ref_symmetric,n) && ...
    valid_square(s.G,n) && valid_square(s.C_foundation_full,n) && ...
    symmetry_error(s.M) <= 1e-12 && symmetry_error(s.K_ref_symmetric) <= 1e-12 && ...
    symmetry_error(s.C_foundation_full) <= 1e-12 && ...
    relative_error(s.K_ref_symmetric, ...
    0.5*(s.K_tangent_original+s.K_tangent_original.')) <= 1e-12;
checks.mapping = isstruct(s.observation_mapping) && ...
    isfield(s.observation_mapping,'validated') && s.observation_mapping.validated && ...
    isfield(s.observation_mapping,'dof_indices') && ...
    numel(unique(s.observation_mapping.dof_indices)) >= 4 && ...
    all(s.observation_mapping.dof_indices >= 1 & ...
    s.observation_mapping.dof_indices <= n) && ...
    isstruct(s.bearing_mapping) && isfield(s.bearing_mapping,'validated') && ...
    s.bearing_mapping.validated;

modal_required = {'natural_frequencies_Hz','physical_mode_indices', ...
    'mass_normalized_modes','mass_normalization_error','anchor_modes', ...
    'anchor_frequencies_Hz','anchor_participation','bracketing_flag', ...
    'participation_filter_relaxed','first_six_mode_indices'};
checks.modal_schema = required_fields(m,modal_required);
if ~checks.static_matrices || ~checks.modal_schema
    validation = finish(checks); return;
end
Phi = m.mass_normalized_modes; frequency = reshape(m.natural_frequencies_Hz,1,[]);
checks.modal_dimensions = isnumeric(Phi) && isreal(Phi) && size(Phi,1) == n && ...
    size(Phi,2) == numel(frequency) && numel(frequency) >= 6 && ...
    all(isfinite(Phi),'all') && all(isfinite(frequency)) && ...
    all(frequency > 0) && all(diff(frequency) >= 0) && ...
    isequal(reshape(m.first_six_mode_indices,1,[]),1:6) && ...
    numel(m.anchor_modes) == 2 && all(m.anchor_modes >= 1 & ...
    m.anchor_modes <= numel(frequency));
mass_error_recomputed = Inf;
if checks.modal_dimensions
    mass_error_recomputed = norm(Phi.'*s.M*Phi-eye(size(Phi,2)),inf);
end
checks.mass_normalization = isfinite(mass_error_recomputed) && ...
    mass_error_recomputed <= 1e-8 && isfinite(m.mass_normalization_error) && ...
    abs(m.mass_normalization_error-mass_error_recomputed) <= 1e-10;

checks.damping_schema = required_fields(d,{'scenarios','target_zeta', ...
    'C_foundation_full','K_ref_20C','alpha','beta','zeta_base_1to6', ...
    'zeta_rayleigh_1to6','zeta_total_1to6','anchor_actual_zeta', ...
    'anchor_target_errors','base_exceeds_target_flags','solution_method', ...
    'matrix_validation', ...
    'old_ehl_excluded','legacy_rayleigh_excluded', ...
    'gyroscopic_term_is_separate','frozen_across_temperatures'});
checks.damping_identity = checks.damping_schema && ...
    isequal(d.scenarios,{'LOW','NOMINAL','HIGH'}) && ...
    isequal(d.target_zeta,[0.005 0.010 0.020]) && ...
    relative_error(d.C_foundation_full,s.C_foundation_full) <= 1e-12 && ...
    relative_error(d.K_ref_20C,s.K_ref_symmetric) <= 1e-12 && ...
    isequal(size(d.alpha),[1 3]) && isequal(size(d.beta),[1 3]) && ...
    all(isfinite([d.alpha d.beta])) && all(d.alpha >= 0) && all(d.beta >= 0);

scenario_names = {'LOW','NOMINAL','HIGH'};
checks.formal_matrices = checks.damping_identity;
checks.zeta_vectors = checks.damping_identity && ...
    isequal(size(d.zeta_base_1to6),[1 6]);
zeta_total_recomputed = zeros(3,6); anchor_actual_recomputed = zeros(3,2);
if checks.damping_identity && checks.modal_dimensions
    omega = 2*pi*frequency;
    zeta_base = modal_zeta(Phi,s.C_foundation_full,omega);
    checks.zeta_vectors = checks.zeta_vectors && ...
        relative_error(d.zeta_base_1to6,zeta_base(1:6)) <= 1e-12;
    for k = 1:3
        name = scenario_names{k};
        rayleigh_field = ['C_rayleigh_ref_' name];
        formal_field = ['C_formal_' name];
        if ~isfield(d,rayleigh_field) || ~isfield(d,formal_field) || ...
                ~isfield(d.zeta_rayleigh_1to6,name) || ...
                ~isfield(d.zeta_total_1to6,name)
            checks.formal_matrices = false; checks.zeta_vectors = false; break;
        end
        expected_rayleigh = d.alpha(k)*s.M+d.beta(k)*s.K_ref_symmetric;
        expected_formal = s.C_foundation_full+expected_rayleigh;
        checks.formal_matrices = checks.formal_matrices && ...
            relative_error(d.(rayleigh_field),expected_rayleigh) <= 1e-12 && ...
            relative_error(d.(formal_field),expected_formal) <= 1e-12 && ...
            valid_psd_matrix(d.(formal_field),s.M);
        zeta_R = modal_zeta(Phi,d.(rayleigh_field),omega);
        zeta_T = modal_zeta(Phi,d.(formal_field),omega);
        zeta_total_recomputed(k,:) = zeta_T(1:6);
        anchor_actual_recomputed(k,:) = zeta_T(m.anchor_modes);
        checks.zeta_vectors = checks.zeta_vectors && ...
            isequal(size(d.zeta_rayleigh_1to6.(name)),[1 6]) && ...
            isequal(size(d.zeta_total_1to6.(name)),[1 6]) && ...
            relative_error(d.zeta_rayleigh_1to6.(name),zeta_R(1:6)) <= 1e-12 && ...
            relative_error(d.zeta_total_1to6.(name),zeta_T(1:6)) <= 1e-12;
    end
else
    checks.formal_matrices = false; checks.zeta_vectors = false;
end
checks.anchor_audit = checks.zeta_vectors && ...
    isequal(size(d.anchor_actual_zeta),[3 2]) && ...
    isequal(size(d.anchor_target_errors),[3 2]) && ...
    relative_error(d.anchor_actual_zeta,anchor_actual_recomputed) <= 1e-12 && ...
    relative_error(d.anchor_target_errors, ...
    anchor_actual_recomputed-d.target_zeta(:)) <= 1e-12;
checks.calibration_tolerances = checks.anchor_audit && ...
    isequal(size(d.base_exceeds_target_flags),[3 2]) && ...
    iscell(d.solution_method) && isequal(size(d.solution_method),[1 3]);
if checks.calibration_tolerances
    anchor_base = modal_zeta(Phi,s.C_foundation_full,2*pi*frequency);
    anchor_base = anchor_base(m.anchor_modes);
    expected_saturation = anchor_base > d.target_zeta(:);
    checks.calibration_tolerances = ...
        isequal(d.base_exceeds_target_flags,expected_saturation) && ...
        all(anchor_base <= d.target_zeta(3));
    for k = 1:3
        method = d.solution_method{k};
        checks.calibration_tolerances = checks.calibration_tolerances && ...
            (strcmp(method,'DIRECT') || strcmp(method,'NNLS'));
        for j = 1:2
            if expected_saturation(k,j)
                checks.calibration_tolerances = checks.calibration_tolerances && ...
                    anchor_actual_recomputed(k,j) >= anchor_base(j)-1e-12;
            else
                if strcmp(method,'NNLS')
                    tolerance = max(1e-3,0.25*d.target_zeta(k));
                else
                    tolerance = max(1e-4,0.05*d.target_zeta(k));
                end
                checks.calibration_tolerances = checks.calibration_tolerances && ...
                    abs(anchor_actual_recomputed(k,j)-d.target_zeta(k)) <= tolerance;
            end
        end
    end
end
checks.ordering = checks.zeta_vectors && ...
    all(diff(zeta_total_recomputed,1,1) >= -1e-12,'all') && ...
    all(diff(anchor_actual_recomputed,1,1) >= -1e-12,'all');

checks.runtime_legacy_equivalence = runtime_gate(runtime);
checks.legacy_terms_excluded = logical_scalar_field(d,'old_ehl_excluded',true) && ...
    logical_scalar_field(d,'legacy_rayleigh_excluded',true) && ...
    logical_scalar_field(d,'gyroscopic_term_is_separate',true) && ...
    isfield(r.validation.stage_c,'old_ehl_sensitivity_error') && ...
    r.validation.stage_c.old_ehl_sensitivity_error <= 1e-12 && ...
    isfield(r.validation.stage_c,'legacy_rayleigh_sensitivity_error') && ...
    r.validation.stage_c.legacy_rayleigh_sensitivity_error <= 1e-12;
checks.frozen = logical_scalar_field(d,'frozen_across_temperatures',true) && ...
    logical_scalar_field(r.validation.stage_c,'formal_matrices_frozen',true);
checks.progress = progress_gate(r.progress);
checks.decision = isfield(r.decision,'status') && ...
    strcmp(char(r.decision.status),'FIXED_EQUIVALENT_DAMPING_ENVELOPE_ACCEPTED') && ...
    logical_scalar_field(r.decision,'allow_stage_d',true) && ...
    logical_scalar_field(r.decision,'stage_d_executed',false);

validation = finish(checks);
validation.mass_normalization_error_recomputed = mass_error_recomputed;
end

function pass = required_meta(meta)
fields = {'branch','baseline_branch','baseline_commit','stage_a_commit', ...
    'stage_b_commit','source_commit','creation_time','model_dof_count', ...
    'rotational_speed_rpm','analysis_type','damping_model', ...
    'dynamic_ehl_used','old_ehl_used_in_formal_response','newmark_used'};
pass = required_fields(meta,fields) && ...
    logical_scalar_field(meta,'dynamic_ehl_used',false) && ...
    logical_scalar_field(meta,'old_ehl_used_in_formal_response',false) && ...
    logical_scalar_field(meta,'newmark_used',false);
end

function pass = runtime_gate(runtime)
fields = {'space','relative_error','size_match','all_finite','symmetry_errors', ...
    'passed','source_commit','runtime_equivalence_pending','C_rayleigh_r', ...
    'C_foundation_r','C_ehl_total_r','C_total_r','gyroscopic_term_excluded'};
pass = required_fields(runtime,fields) && ...
    strcmp(char(runtime.space),'REDUCED_AUDIT_SPACE') && ...
    logical_scalar_field(runtime,'passed',true) && ...
    logical_scalar_field(runtime,'runtime_equivalence_pending',false) && ...
    logical_scalar_field(runtime,'size_match',true) && ...
    logical_scalar_field(runtime,'all_finite',true) && ...
    logical_scalar_field(runtime,'gyroscopic_term_excluded',true) && ...
    ~isfield(runtime,'G');
if ~pass, return; end
matrices = {runtime.C_rayleigh_r,runtime.C_foundation_r, ...
    runtime.C_ehl_total_r,runtime.C_total_r};
n = size(matrices{1},1);
pass = all(cellfun(@(A) valid_square(A,n) && symmetry_error(A) <= 1e-12,matrices));
if ~pass, return; end
recomputed = relative_error(matrices{1}+matrices{2}+matrices{3},matrices{4});
pass = recomputed <= 1e-12 && runtime.relative_error <= 1e-12 && ...
    abs(recomputed-runtime.relative_error) <= 1e-12;
end

function pass = progress_gate(progress)
true_fields = {'stage_a_complete','stage_b_complete','stage_c_static_20C_complete', ...
    'stage_c_runtime_equivalence_complete','stage_c_modal_complete', ...
    'stage_c_damping_envelope_complete'};
false_fields = {'stage_d_complete','stage_e_complete','stage_f_complete', ...
    'stage_g_complete','stage_h_complete'};
pass = required_fields(progress,[true_fields false_fields {'last_completed_gate'}]);
for k = 1:numel(true_fields), pass = pass && logical_scalar_field(progress,true_fields{k},true); end
for k = 1:numel(false_fields), pass = pass && logical_scalar_field(progress,false_fields{k},false); end
end

function validation = finish(checks)
values = struct2cell(checks);
validation = struct('passed',all(cellfun(@(v) islogical(v) && isscalar(v) && v,values)), ...
    'checks',checks);
end

function pass = required_fields(value,names)
pass = isstruct(value) && all(isfield(value,names));
end

function pass = logical_scalar_field(value,name,expected)
pass = isstruct(value) && isfield(value,name) && ...
    (islogical(value.(name)) || isnumeric(value.(name))) && ...
    isscalar(value.(name)) && isfinite(value.(name)) && ...
    logical(value.(name)) == expected;
end

function pass = valid_square(A,n)
pass = isnumeric(A) && isreal(A) && isequal(size(A),[n n]) && ...
    all(isfinite(A),'all');
end

function pass = valid_psd_matrix(C,M)
pass = valid_square(C,size(M,1));
if ~pass, return; end
symmetry = symmetry_error(C);
tolerance = 1e-10*max(norm(C,2),1);
[~,flag] = chol(full(0.5*(C+C.')+tolerance*eye(size(C))),'lower');
pass = symmetry <= 1e-12 && flag == 0;
end

function zeta = modal_zeta(Phi,C,omega)
zeta = reshape(diag(Phi.'*C*Phi),1,[])./(2*reshape(omega,1,[]));
end

function value = symmetry_error(A)
value = norm(A-A.','fro')/max(norm(A,'fro'),eps);
end

function value = relative_error(A,B)
value = norm(A-B,'fro')/max(norm(B,'fro'),eps);
end
