function validation = validate_stage_d_static_temperature_case(state,model_dof_count)
%VALIDATE_STAGE_D_STATIC_TEMPERATURE_CASE Pure accepted-state validation.

checks = struct();
required = {'requested_case_temperature_C','initial_guess_source_temperature_C', ...
    'initial_guess_only','initial_guess_fields_used','q_static','thermal_state', ...
    'lubricant_state','film_thickness','clearance_state', ...
    'bearing_state_front','bearing_state_rear', ...
    'rolling_element_loads_front','rolling_element_loads_rear', ...
    'loaded_mask_front','loaded_mask_rear','contact_deflection_front', ...
    'contact_deflection_rear','contact_stiffness_front', ...
    'contact_stiffness_rear','contact_stiffness_source_front', ...
    'contact_stiffness_source_rear','bearing_resultant_consistency', ...
    'K_b_front','K_b_rear','K_tangent','acceptance','statistics', ...
    'final_front_bearing_temperature_C','final_rear_bearing_temperature_C', ...
    'invariant_references','source_commit'};
checks.schema = isstruct(state) && all(isfield(state,required));
if ~checks.schema, validation = finish(checks); return; end

T = state.requested_case_temperature_C;
expected_source = [20 50 80];
case_index = find([50 80 100] == T,1);
checks.temperature_and_continuation = ~isempty(case_index) && ...
    state.initial_guess_source_temperature_C == expected_source(case_index) && ...
    islogical(state.initial_guess_only) && isscalar(state.initial_guess_only) && ...
    state.initial_guess_only && iscell(state.initial_guess_fields_used) && ...
    isequal(state.initial_guess_fields_used,{'q_static'});
checks.state = isnumeric(state.q_static) && isreal(state.q_static) && ...
    isequal(size(state.q_static),[model_dof_count 1]) && ...
    all(isfinite(state.q_static));
checks.thermal = thermal_pair_valid(state.thermal_state,T, ...
    state.final_front_bearing_temperature_C, ...
    state.final_rear_bearing_temperature_C);
checks.bearing_states = bearing_state_valid(state.bearing_state_front) && ...
    bearing_state_valid(state.bearing_state_rear);
checks.lubricant = lubricant_valid(state.lubricant_state,state.thermal_state);
checks.film = film_valid(state.film_thickness,state.bearing_state_front, ...
    state.bearing_state_rear);
checks.clearance = clearance_valid(state.clearance_state,state.thermal_state);
checks.contact = contact_valid(state);
checks.resultant = resultant_valid(state.bearing_resultant_consistency);
checks.bearing_tangent = valid_matrix(state.K_b_front,[5 5]) && ...
    valid_matrix(state.K_b_rear,[5 5]) && ...
    symmetry_error(state.K_b_front) <= 1e-10 && ...
    symmetry_error(state.K_b_rear) <= 1e-10;
checks.system_tangent = valid_matrix(state.K_tangent, ...
    [model_dof_count model_dof_count]) && symmetry_error(state.K_tangent) <= 1e-10;
checks.acceptance = acceptance_valid(state.acceptance);
checks.statistics = statistics_valid(state.statistics,state);
checks.invariants = invariant_valid(state.invariant_references);
checks.source = (ischar(state.source_commit) || ...
    (isstring(state.source_commit) && isscalar(state.source_commit))) && ...
    ~isempty(char(state.source_commit));
validation = finish(checks);
validation.tangent_symmetry_error = symmetry_error(state.K_tangent);
end

function pass = thermal_pair_valid(value,requested,front_final,rear_final)
pass = isstruct(value) && all(isfield(value,{'ball','roller'})) && ...
    thermal_entry_valid(value.ball,requested,front_final) && ...
    thermal_entry_valid(value.roller,requested,rear_final);
end

function pass = thermal_entry_valid(value,requested,final_temperature)
fields = {'T_oil','T_final','T_film','T_inner','T_outer','T_element', ...
    'eta','alpha_p','working_clearance','film_thickness','thermal_preload'};
pass = isstruct(value) && all(isfield(value,fields));
if ~pass, return; end
numeric_fields = fields(1:10);
numbers = cellfun(@(name) value.(name),numeric_fields,'UniformOutput',false);
pass = all(cellfun(@(number) isnumeric(number) && isscalar(number) && ...
    isreal(number) && isfinite(number),numbers)) && ...
    value.T_oil == requested && value.T_final == final_temperature && ...
    value.eta > 0 && value.alpha_p > 0 && value.film_thickness > 0;
end

function pass = bearing_state_valid(value)
fields = {'theta','Q','delta','delta_raw','loaded_count','loaded_index', ...
    'film','Fx','Fy','Fz','Mx','My','r','rotor_node','case_node'};
pass = isstruct(value) && all(isfield(value,fields)) && ...
    isnumeric(value.theta) && isvector(value.theta) && all(isfinite(value.theta)) && ...
    isnumeric(value.Q) && isnumeric(value.delta) && ...
    isequal(size(value.Q),size(value.delta)) && ...
    all(isfinite(value.Q),'all') && all(value.Q >= 0,'all') && ...
    all(isfinite(value.delta),'all') && all(value.delta >= 0,'all') && ...
    all(isfinite([value.Fx value.Fy value.Fz value.Mx value.My])) && ...
    isstruct(value.film) && all(isfield(value.film, ...
    {'h_m','loaded_mask','hmin_m'})) && ...
    isequal(size(value.film.h_m),size(value.Q)) && ...
    isequal(value.film.loaded_mask,value.Q > 0);
end

function pass = lubricant_valid(value,thermal)
pass = isstruct(value) && all(isfield(value,{'front','rear'})) && ...
    isstruct(thermal) && all(isfield(thermal,{'ball','roller'}));
if ~pass, return; end
names = {'front','rear'}; thermal_names = {'ball','roller'};
for k = 1:2
    if ~pass, break; end
    entry = value.(names{k}); reference = thermal.(thermal_names{k});
    pass = isstruct(entry) && all(isfield(entry, ...
        {'viscosity_Pa_s','pressure_viscosity_Pa_inv','film_temperature_C','source'})) && ...
        all(isfinite([entry.viscosity_Pa_s entry.pressure_viscosity_Pa_inv, ...
        entry.film_temperature_C])) && entry.viscosity_Pa_s > 0 && ...
        entry.pressure_viscosity_Pa_inv > 0 && ...
        entry.viscosity_Pa_s == reference.eta && ...
        entry.pressure_viscosity_Pa_inv == reference.alpha_p && ...
        entry.film_temperature_C == reference.T_film && ...
        strcmp(entry.source,'FORMAL_FROZEN_THERMAL_STATE');
end
end

function pass = film_valid(value,front_state,rear_state)
pass = isstruct(value) && all(isfield(value,{'front','rear'}));
names = {'front','rear'}; states = {front_state,rear_state};
for k = 1:2
    if ~pass, break; end
    entry = value.(names{k}); contact = states{k};
    required = {'central_by_contact_m','central_loaded_m', ...
        'central_min_loaded_m','minimum_m','unit','source','floor_active'};
    loaded = contact.Q > 0;
    pass = isstruct(entry) && all(isfield(entry,required)) && ...
        isequal(size(entry.central_by_contact_m),size(contact.Q)) && ...
        isequaln(entry.central_by_contact_m,contact.film.h_m) && ...
        isequal(entry.central_loaded_m,reshape(contact.film.h_m(loaded),1,[])) && ...
        ~isempty(entry.central_loaded_m) && all(isfinite(entry.central_loaded_m)) && ...
        all(entry.central_loaded_m > 0) && ...
        entry.central_min_loaded_m == min(entry.central_loaded_m) && ...
        entry.minimum_m == contact.film.hmin_m && entry.minimum_m > 0 && ...
        strcmp(entry.unit,'m') && strcmp(entry.source,'FORMAL_CONTACT_FILM_STATE') && ...
        islogical(entry.floor_active) && isscalar(entry.floor_active);
end
end

function pass = clearance_valid(value,thermal)
pass = isstruct(value) && all(isfield(value,{'front','rear'})) && ...
    isstruct(thermal) && all(isfield(thermal,{'ball','roller'}));
if ~pass, return; end
names = {'front','rear'}; thermal_names = {'ball','roller'};
required = {'cold_clearance_m','thermal_expansion_correction_m', ...
    'film_or_contact_correction_m','working_clearance_m', ...
    'film_or_contact_correction_available'};
for k = 1:2
    if ~pass, break; end
    entry = value.(names{k}); reference = thermal.(thermal_names{k});
    pass = isstruct(entry) && all(isfield(entry,required)) && ...
        all(isfinite([entry.cold_clearance_m, ...
        entry.thermal_expansion_correction_m, ...
        entry.film_or_contact_correction_m,entry.working_clearance_m])) && ...
        near_equal(entry.working_clearance_m,entry.cold_clearance_m + ...
        entry.thermal_expansion_correction_m + entry.film_or_contact_correction_m) && ...
        entry.working_clearance_m == reference.working_clearance;
end
end

function pass = contact_valid(state)
front_Q = state.bearing_state_front.Q;
rear_Q = state.bearing_state_rear.Q;
pass = contact_array_valid(front_Q,state.contact_deflection_front, ...
    state.contact_stiffness_front,3/2) && ...
    contact_array_valid(rear_Q,state.contact_deflection_rear, ...
    state.contact_stiffness_rear,10/9) && ...
    strcmp(state.contact_stiffness_source_front, ...
    'FORMAL_BALL_HERTZ_DERIVATIVE') && ...
    strcmp(state.contact_stiffness_source_rear, ...
    'FORMAL_ROLLER_SLICE_LAW_DERIVATIVE');
end

function pass = contact_array_valid(Q,delta,stiffness,exponent)
pass = isnumeric(Q) && isnumeric(delta) && isnumeric(stiffness) && ...
    isreal(Q) && isreal(delta) && isreal(stiffness) && ...
    isequal(size(Q),size(delta)) && isequal(size(Q),size(stiffness)) && ...
    all(isfinite(Q),'all') && all(isfinite(delta),'all') && ...
    all(isfinite(stiffness),'all') && all(Q >= 0,'all') && ...
    all(delta >= 0,'all') && all(stiffness >= 0,'all');
if ~pass, return; end
loaded = Q > 0;
pass = any(loaded,'all') && isequal(loaded,delta > 0) && ...
    all(stiffness(~loaded) == 0);
if ~pass, return; end
expected = exponent*Q(loaded)./delta(loaded);
relative_error = norm(stiffness(loaded)-expected)/max(norm(expected),eps);
pass = isfinite(relative_error) && relative_error <= 1e-12;
end

function pass = resultant_valid(value)
required = {'front_linearization_repeatability_error', ...
    'rear_linearization_repeatability_error','front_global_assembly_error', ...
    'rear_global_assembly_error','front_action_reaction_error', ...
    'rear_action_reaction_error','formal_static_action_reaction_error', ...
    'units','source','passed'};
pass = isstruct(value) && all(isfield(value,required)) && ...
    all(isfinite([value.front_linearization_repeatability_error, ...
    value.rear_linearization_repeatability_error,value.front_global_assembly_error, ...
    value.rear_global_assembly_error,value.front_action_reaction_error, ...
    value.rear_action_reaction_error,value.formal_static_action_reaction_error])) && ...
    value.front_linearization_repeatability_error <= 1e-10 && ...
    value.rear_linearization_repeatability_error <= 1e-10 && ...
    value.front_global_assembly_error <= 1e-10 && ...
    value.rear_global_assembly_error <= 1e-10 && ...
    value.front_action_reaction_error <= 1e-10 && ...
    value.rear_action_reaction_error <= 1e-10 && ...
    value.formal_static_action_reaction_error <= 1e-10 && value.passed;
end

function pass = acceptance_valid(value)
required = {'mechanical_residual','thermal_residual_front_C', ...
    'thermal_residual_rear_C','thermal_residual_max_C','power_residual_W', ...
    'axial_constraint_error_m','relative_Q_change','relative_film_change', ...
    'kkt_residual_raw','kkt_residual_normalized','constraint_residual', ...
    'complementarity_residual','active_set_consistency', ...
    'thermal_outer_iterations','static_newton_iterations', ...
    'final_consistency_recompute_count','thermal_converged', ...
    'static_converged','formal_tolerances','formal_acceptance_flag'};
pass = isstruct(value) && all(isfield(value,required));
if ~pass, return; end
finite_values = [value.mechanical_residual,value.thermal_residual_front_C, ...
    value.thermal_residual_rear_C,value.thermal_residual_max_C, ...
    value.power_residual_W,value.axial_constraint_error_m, ...
    value.relative_Q_change,value.relative_film_change,value.kkt_residual_raw, ...
    value.kkt_residual_normalized,value.constraint_residual, ...
    value.thermal_outer_iterations,value.static_newton_iterations, ...
    value.final_consistency_recompute_count];
complementarity = value.complementarity_residual;
tol = value.formal_tolerances;
pass = all(isfinite(finite_values)) && all(finite_values >= 0) && ...
    value.mechanical_residual <= 1e-6 && value.thermal_residual_max_C <= 1e-3 && ...
    value.power_residual_W <= 0.12 && value.axial_constraint_error_m <= 1e-8 && ...
    value.relative_Q_change <= 1e-4 && value.relative_film_change <= 1e-3 && ...
    value.kkt_residual_normalized <= 1e-6 && value.constraint_residual <= 1e-8 && ...
    isstruct(complementarity) && all(isfield(complementarity,{'available','status'})) && ...
    ~complementarity.available && ...
    strcmp(complementarity.status,'FIELD_NOT_AVAILABLE_IN_FORMAL_SOLVER') && ...
    isstruct(tol) && all(isfield(tol,{'temperature_C','power_W','mechanical', ...
    'axial_m','relative_Q','relative_film'})) && ...
    isequal([tol.temperature_C tol.power_W tol.mechanical tol.axial_m, ...
    tol.relative_Q tol.relative_film],[1e-3 0.12 1e-6 1e-8 1e-4 1e-3]) && ...
    near_equal(value.thermal_residual_max_C,max( ...
    value.thermal_residual_front_C,value.thermal_residual_rear_C)) && ...
    positive_integer(value.thermal_outer_iterations) && ...
    positive_integer(value.static_newton_iterations) && ...
    value.thermal_outer_iterations <= 20 && ...
    value.final_consistency_recompute_count == 1 && ...
    value.active_set_consistency && value.thermal_converged && ...
    value.static_converged && value.formal_acceptance_flag;
end

function pass = statistics_valid(value,state)
pass = isstruct(value) && all(isfield(value,{'front','rear'}));
if ~pass, return; end
front = value.front; rear = value.rear;
required = {'rolling_element_loads_N','loaded_mask','loaded_indices', ...
    'loaded_count','load_zone_angle_rad','max_load_element_index', ...
    'Q_max_N','Q_mean_loaded_N','Q_sum_N','Q_std_loaded_N','CV_Q'};
pass = all(isfield(front,required)) && all(isfield(rear,required)) && ...
    isequal(front.rolling_element_loads_N,state.rolling_element_loads_front) && ...
    isequal(rear.rolling_element_loads_N,state.rolling_element_loads_rear) && ...
    isequal(front.loaded_mask,state.loaded_mask_front) && ...
    isequal(rear.loaded_mask,state.loaded_mask_rear) && ...
    isequaln(front,compute_stage_d_bearing_statistics( ...
    state.bearing_state_front.Q,state.bearing_state_front.theta)) && ...
    isequaln(rear,compute_stage_d_bearing_statistics( ...
    state.bearing_state_rear.Q,state.bearing_state_rear.theta));
end

function pass = invariant_valid(value)
required = {'M','G','dof_mapping','M_max_abs_difference', ...
    'G_max_abs_difference','consistent'};
pass = isstruct(value) && all(isfield(value,required)) && ...
    strcmp(value.M,'results.static.T20.M') && ...
    strcmp(value.G,'results.static.T20.G') && ...
    strcmp(value.dof_mapping,'results.static.T20.dof_mapping') && ...
    value.consistent && value.M_max_abs_difference == 0 && ...
    value.G_max_abs_difference == 0;
end

function pass = valid_matrix(value,expected_size)
pass = isnumeric(value) && isreal(value) && isequal(size(value),expected_size) && ...
    all(isfinite(value),'all');
end

function value = symmetry_error(matrix)
if ~isnumeric(matrix) || isempty(matrix), value = Inf; return; end
value = norm(matrix-matrix.','fro')/max(norm(matrix,'fro'),eps);
end

function pass = positive_integer(value)
pass = isnumeric(value) && isscalar(value) && isfinite(value) && ...
    value >= 1 && value == floor(value);
end

function pass = near_equal(left,right)
scale = max([abs(left),abs(right),1]);
pass = isfinite(left) && isfinite(right) && abs(left-right) <= 10*eps(scale);
end

function validation = finish(checks)
values = struct2cell(checks);
validation = struct('passed',all(cellfun(@(v) islogical(v) && isscalar(v) && v,values)), ...
    'checks',checks,'tangent_symmetry_error',Inf);
end
