function test_stage_a_equivalent_frequency_mainline_contract
%TEST_STAGE_A_EQUIVALENT_FREQUENCY_MAINLINE_CONTRACT Stage A configuration contract.

repository_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
original_path = path;
path_cleanup = onCleanup(@() path(original_path));
addpath(repository_root);

working_directory_before = pwd;
global_variables_before = global_variable_state();
repository_before = repository_snapshot(repository_root);

cfg = build_equivalent_damping_frequency_domain_config();

assert(strcmp(cfg.mainline_name, 'thermal_equivalent_damping_frequency_domain'));
assert(strcmp(cfg.analysis_type, ...
    'FULL_ORDER_1X_FREQUENCY_DOMAIN_WITH_CONTACT_NONLINEARITY_GATE'));
assert(strcmp(cfg.damping_model, 'fixed_equivalent_system'));
assert(strcmp(cfg.legacy_damping_mode, 'audit_only'));
assert(cfg.dynamic_ehl_used == false);
assert(cfg.old_ehl_used_in_formal_response == false);
assert(cfg.newmark_used == false);
assert(isequal(cfg.temperature_cases_C, [20 50 80 100]));
assert(isequal(cfg.damping_scenarios.names, {'LOW','NOMINAL','HIGH'}));
assert(isequal(cfg.damping_scenarios.target_zeta, [0.005 0.010 0.020]));
assert(cfg.damping_reference_temperature_C == 20);
assert(cfg.freeze_formal_damping_across_temperatures == true);
assert(cfg.rotational_speed_rpm == 9900);
assert(abs(cfg.rotational_speed_rad_s - 2*pi*9900/60) <= eps(2*pi*9900/60));
assert(cfg.frequency_1X_Hz == 165);
assert(abs(cfg.omega_1X_rad_s - 2*pi*165) <= eps(2*pi*165));
assert(cfg.unbalance.rotor_node == 16);
assert(cfg.unbalance.mass_kg == 1e-3);
assert(cfg.unbalance.eccentricity_m == 1e-3);
assert(cfg.unbalance.phase_rad == 0);
assert(cfg.unbalance.unbalance_kg_m == 1e-6);
assert(cfg.nonlinearity_gate.phase_count == 32);
assert(cfg.nonlinearity_gate.strong_ratio == 0.10);
assert(cfg.nonlinearity_gate.caution_ratio == 0.20);
assert(cfg.nonlinearity_gate.error_limit == 0.10);
assert(cfg.nonlinearity_gate.harmonic_ratio_limit == 0.10);
assert(strcmp(cfg.result_directory, fullfile('results', ...
    'thermal_equivalent_damping_frequency_domain')));
assert(strcmp(cfg.result_mat_name, 'thermal_4T_frequency_domain_results.mat'));
assert(strcmp(cfg.result_txt_name, 'thermal_4T_frequency_domain_summary.txt'));
assert(cfg.mapping_validation_required == true);

assert(strcmp(pwd, working_directory_before), ...
    'The configuration function must not modify the working directory.');
assert(isequaln(global_variable_state(), global_variables_before), ...
    'The configuration function must not modify global variables.');
assert(isequal(repository_snapshot(repository_root), repository_before), ...
    'The configuration function must not create or modify repository files.');

source = fileread(fullfile(repository_root, ...
    'build_equivalent_damping_frequency_domain_config.m'));
forbidden_patterns = { ...
    'dynamic_ehl_enabled\s*=\s*true', ...
    'dynamic_ehl_used\s*=\s*true', ...
    'old_ehl_used_in_formal_response\s*=\s*true', ...
    'newmark_used\s*=\s*true', ...
    '(^|\n)\s*global\s+', ...
    '\<(assignin|evalin)\s*\(', ...
    '\<newmark\w*\s*\(', ...
    '\<solve_\w*\s*\(', ...
    '\<eig(s)?\s*\(', ...
    '\<ode[0-9]+[a-z]*\s*\(', ...
    '\<(fsolve|fzero|fmincon|fminunc|lsqnonlin|lsqlin|quadprog|intlinprog|linprog|vpasolve|dsolve|linsolve)\s*\(', ...
    '\<mkdir\s*\(', ...
    '\<save\s*\(', ...
    '\<fopen\s*\(', ...
    '\<2X\>', ...
    '\<3X\>'};
for k = 1:numel(forbidden_patterns)
    assert(isempty(regexpi(source, forbidden_patterns{k}, 'once')), ...
        'The Stage A configuration contains a forbidden implementation token.');
end

configuration_body = regexprep(source, ...
    '^\s*function[^\n]*(\n|$)', '', 'once');
call_tokens = regexp(configuration_body, ...
    '(?<![.\w])([A-Za-z]\w*)\s*\(', 'tokens');
if isempty(call_tokens)
    called_functions = {};
else
    called_functions = unique(cellfun(@(token) token{1}, ...
        call_tokens, 'UniformOutput', false));
end
unexpected_calls = setdiff(called_functions, {'fullfile'});
assert(isempty(unexpected_calls), ...
    'The Stage A configuration may call only fullfile.');

source_without_strings = regexprep(source, '''[^'']*''', '');
source_without_comments = regexprep(source_without_strings, '%[^\n]*', '');
identifiers = unique(regexp(source_without_comments, ...
    '\<[A-Za-z]\w*\>', 'match'));
allowed_identifiers = { ...
    'function', 'cfg', 'build_equivalent_damping_frequency_domain_config', ...
    'mainline_name', 'analysis_type', 'damping_model', ...
    'legacy_damping_mode', 'dynamic_ehl_used', ...
    'old_ehl_used_in_formal_response', 'newmark_used', ...
    'temperature_cases_C', 'rotational_speed_rpm', ...
    'rotational_speed_rad_s', 'frequency_1X_Hz', 'omega_1X_rad_s', ...
    'damping_scenarios', 'names', 'target_zeta', ...
    'damping_reference_temperature_C', ...
    'freeze_formal_damping_across_temperatures', ...
    'unbalance', 'rotor_node', 'mass_kg', 'eccentricity_m', ...
    'phase_rad', 'unbalance_kg_m', 'nonlinearity_gate', ...
    'phase_count', 'strong_ratio', 'caution_ratio', 'error_limit', ...
    'harmonic_ratio_limit', 'result_directory', 'result_mat_name', ...
    'result_txt_name', 'mapping_validation_required', ...
    'damping_modes', 'legacy', 'formal', 'damping_contract', ...
    'legacy_components', 'formal_components', ...
    'legacy_rayleigh_in_formal', 'old_ehl_in_formal', ...
    'gyroscopic_term_is_separate', 'runtime_equivalence_stage', ...
    'runtime_equivalence_pending', 'stage_b_verification_scope', ...
    'legacy_audit_artifact_available', 'runtime_equivalence_gate', ...
    'runtime_equivalence_failure_status', ...
    'pi', 'fullfile', 'true', 'false', 'end'};
unexpected_identifiers = setdiff(identifiers, allowed_identifiers);
assert(isempty(unexpected_identifiers), ...
    'The Stage A configuration contains an unknown executable identifier.');

fprintf('STAGE_A_CONFIG_CONTRACT_PASSED\n');
end

function state = global_variable_state
variables = evalin('base', 'whos');
variables = variables([variables.global]);
[~, order] = sort({variables.name});
variables = variables(order);
values = cell(1, numel(variables));
for k = 1:numel(variables)
    values{k} = evalin('base', variables(k).name);
end
state = struct('names', {{variables.name}}, 'values', {values});
end

function snapshot = repository_snapshot(repository_root)
entries = dir(fullfile(repository_root, '**', '*'));
paths = fullfile({entries.folder}, {entries.name});
git_prefix = [repository_root filesep '.git'];
entries = entries(~startsWith(paths, git_prefix));
paths = paths(~startsWith(paths, git_prefix));
relative_paths = erase(paths, [repository_root filesep]);
[relative_paths, order] = sort(relative_paths);
entries = entries(order);
snapshot = struct('path', relative_paths, ...
    'is_directory', num2cell([entries.isdir]), ...
    'bytes', num2cell([entries.bytes]), ...
    'datenum', num2cell([entries.datenum]));
end
