function test_stage_d_four_temperature_static_states
%TEST_STAGE_D_FOUR_TEMPERATURE_STATIC_STATES Pure Stage D contracts.

repository_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
original_path = path; path_cleanup = onCleanup(@() path(original_path));
addpath(repository_root);
artifact_path = fullfile(repository_root,'results', ...
    'thermal_equivalent_damping_frequency_domain', ...
    'thermal_4T_frequency_domain_results.mat');
artifact = load(artifact_path);
accepted = validate_stage_d_four_temperature_results(artifact);
assert(accepted.passed && accepted.stage_d_complete, ...
    'StageD:AcceptedCanonicalRequired', ...
    'The Stage D fixture requires an accepted, completed canonical artifact.');
baseline = pre_stage_d_fixture(artifact.results);

test_bearing_statistics();
test_case_validation(baseline);
test_strict_continuation_resume_and_finalize(baseline);
test_failure_consumes_attempt(baseline);
test_frozen_stage_c_protection(baseline);
test_canonical_transaction(baseline);
test_source_scope(repository_root);
fprintf('STAGE_D_FOUR_TEMPERATURE_STATIC_STATES_PASSED\n');
end

function test_bearing_statistics
stats = compute_stage_d_bearing_statistics([0 2 4 0],[0 pi/2 pi 3*pi/2]);
assert(isequal(stats.loaded_indices,[2 3]) && stats.loaded_count == 2);
assert(abs(stats.load_zone_angle_rad-pi/2) <= eps(pi));
assert(stats.max_load_element_index == 3);
assert(stats.Q_max_N == 4 && stats.Q_mean_loaded_N == 3 && stats.Q_sum_N == 6);
assert(abs(stats.Q_std_loaded_N-sqrt(2)) <= 10*eps);
assert(abs(stats.CV_Q-sqrt(2)/3) <= 10*eps);
roller = compute_stage_d_bearing_statistics([1 2;0 0;3 1],[0 2*pi/3 4*pi/3]);
assert(isequal(roller.rolling_element_loads_N,[3 0 4]));
assert(isequal(roller.loaded_indices,[1 3]));
end

function test_case_validation(baseline)
state = mock_state(50,20,baseline);
validation = validate_stage_d_static_temperature_case(state,192);
assert(validation.passed);
assert(state.requested_case_temperature_C ~= state.final_front_bearing_temperature_C);
missing_acceptance = rmfield(state,'acceptance');
assert(~validate_stage_d_static_temperature_case(missing_acceptance,192).passed);
empty_thermal = state; empty_thermal.thermal_state = struct();
assert(~validate_stage_d_static_temperature_case(empty_thermal,192).passed);
rejected = state; rejected.acceptance.formal_acceptance_flag = false;
assert(~validate_stage_d_static_temperature_case(rejected,192).passed);
bad_residual = state; bad_residual.acceptance.mechanical_residual = 2e-6;
assert(~validate_stage_d_static_temperature_case(bad_residual,192).passed);
bad_derivative = state; bad_derivative.contact_stiffness_front(2) = 1;
assert(~validate_stage_d_static_temperature_case(bad_derivative,192).passed);
bad_tangent = state;
bad_tangent.K_tangent(1,2) = norm(bad_tangent.K_tangent,'fro');
assert(~validate_stage_d_static_temperature_case(bad_tangent,192).passed);
end

function test_strict_continuation_resume_and_finalize(baseline)
initial = validate_stage_d_four_temperature_results(struct('results',baseline));
assert(initial.passed && initial.next_temperature_C == 50);

assert_error(@() update_stage_d_canonical_results( ...
    baseline,mock_state(80,50,baseline),'stage-d-test'), ...
    'StageD:ContinuationOrder');

after_attempt50 = mark_attempt(baseline,50);
T50 = mock_state(50,20,baseline);
[after50,info50] = update_stage_d_canonical_results( ...
    after_attempt50,T50,'stage-d-test','append');
assert(info50.updated && after50.progress.stage_d_T50_complete);
assert(isequaln(after50.static.T20,baseline.static.T20));
assert(isequaln(after50.damping,baseline.damping));
partial50 = validate_stage_d_four_temperature_results(struct('results',after50));
assert(partial50.passed && partial50.next_temperature_C == 80);
bad_decision = after50; bad_decision.decision.allow_stage_d = true;
assert(~validate_stage_d_four_temperature_results( ...
    struct('results',bad_decision)).passed);

[after50_again,info_again] = update_stage_d_canonical_results( ...
    after50,T50,'stage-d-test','append');
assert(~info_again.updated && info_again.already_accepted);
assert(isequaln(after50_again.static.T50,after50.static.T50));

after_attempt80 = mark_attempt(after50,80);
T80 = mock_state(80,50,baseline);
[after80,~] = update_stage_d_canonical_results( ...
    after_attempt80,T80,'stage-d-test','append');
assert(validate_stage_d_four_temperature_results( ...
    struct('results',after80)).next_temperature_C == 100);
after_attempt100 = mark_attempt(after80,100);
T100 = mock_state(100,80,baseline);
[pending,~] = update_stage_d_canonical_results( ...
    after_attempt100,T100,'stage-d-test','append');
pending_validation = validate_stage_d_four_temperature_results(struct('results',pending));
assert(pending_validation.passed && pending_validation.finalization_pending);
assert(~pending.progress.stage_d_complete && ~pending.decision.allow_stage_e);

assert_error(@() update_stage_d_canonical_results(pending, ...
    struct('additional_results_check',audit(),'process_id',1001, ...
    'session_id','session-100'),'stage-d-test','finalize'), ...
    'StageD:ResultReloadFailed');
[complete,~] = update_stage_d_canonical_results(pending, ...
    struct('additional_results_check',audit(),'process_id',2002, ...
    'session_id','independent-session'),'stage-d-test','finalize');
final_validation = validate_stage_d_four_temperature_results(struct('results',complete));
assert(final_validation.passed && final_validation.stage_d_complete);
assert(complete.progress.stage_d_complete && complete.decision.allow_stage_e);
missing_reload = complete;
missing_reload.validation.stage_d = rmfield( ...
    missing_reload.validation.stage_d,'independent_reload');
assert(~validate_stage_d_four_temperature_results( ...
    struct('results',missing_reload)).passed);
bad_reload = complete;
bad_reload.validation.stage_d.independent_reload.finalize_process_id = 1001;
assert(~validate_stage_d_four_temperature_results( ...
    struct('results',bad_reload)).passed);
end

function test_failure_consumes_attempt(baseline)
attempted = mark_attempt(baseline,50);
bad_attempt = attempted; bad_attempt.progress.current_attempt_temperature_C = 80;
assert(~validate_stage_d_four_temperature_results( ...
    struct('results',bad_attempt)).passed);
failure = struct('temperature_C',50, ...
    'main_status','FOUR_TEMPERATURE_STATIC_STATE_FAILED', ...
    'failure_gate','TEST_FORMAL_GATE','diagnostic_identifier','StageD:Test', ...
    'diagnostic_message','synthetic failure');
[failed,~] = update_stage_d_canonical_results( ...
    attempted,failure,'stage-d-test','record_failure');
validation = validate_stage_d_four_temperature_results(struct('results',failed));
assert(validation.passed && validation.failed_temperature_C == 50);
assert(strcmp(failed.decision.status,'FOUR_TEMPERATURE_STATIC_STATE_FAILED'));
bad_failure = failed; bad_failure.progress.failure_gate = 'DIFFERENT_GATE';
assert(~validate_stage_d_four_temperature_results( ...
    struct('results',bad_failure)).passed);
assert_error(@() mark_attempt(failed,50),'StageD:FormalAttemptAlreadyConsumed');
assert_error(@() update_stage_d_canonical_results( ...
    failed,mock_state(50,20,baseline),'stage-d-test','append'), ...
    'StageD:FormalAttemptAlreadyConsumed');
end

function test_frozen_stage_c_protection(baseline)
attempted = mark_attempt(baseline,50);
tampered = attempted; tampered.damping.alpha(1) = tampered.damping.alpha(1)+1e-6;
validation = validate_stage_d_four_temperature_results(struct('results',tampered));
assert(~validation.passed && ~validation.frozen_damping_unchanged);
tampered_T20 = attempted; tampered_T20.static.T20.q_static(1) = 1;
validation_T20 = validate_stage_d_four_temperature_results(struct('results',tampered_T20));
assert(~validation_T20.passed && ~validation_T20.frozen_damping_unchanged);
end

function test_canonical_transaction(baseline)
temporary_directory = tempname;
mkdir(temporary_directory);
cleanup = onCleanup(@() rmdir(temporary_directory,'s'));
canonical = fullfile(temporary_directory, ...
    'thermal_4T_frequency_domain_results.mat');
results = baseline; save(canonical,'results');
directory_audit = stage_d_canonical_transaction('audit',canonical);
assert(directory_audit.passed);
payload = struct('temperature_C',50, ...
    'additional_results_check',directory_audit, ...
    'process_id',3003,'session_id','transaction-session');
[attempted,~] = update_stage_d_canonical_results( ...
    baseline,payload,'stage-d-test','mark_attempt');
saved = stage_d_canonical_transaction('save',canonical,attempted);
assert(saved.results.progress.stage_d_transaction_sequence == 1);
assert_error(@() stage_d_canonical_transaction('save',canonical,attempted), ...
    'StageD:CanonicalResultArtifactConflict');
gap = attempted; gap.progress.stage_d_transaction_sequence = 3;
assert_error(@() stage_d_canonical_transaction('save',canonical,gap), ...
    'StageD:CanonicalResultArtifactConflict');
failure = struct('temperature_C',50, ...
    'main_status','FOUR_TEMPERATURE_STATIC_STATE_FAILED', ...
    'failure_gate','TRANSACTION_RECOVERY_TEST', ...
    'diagnostic_identifier','StageD:TransactionTest', ...
    'diagnostic_message','synthetic transaction recovery');
[results,~] = update_stage_d_canonical_results( ...
    saved.results,failure,'stage-d-test','record_failure');
source = java.nio.file.Paths.get(canonical,javaArray('java.lang.String',0));
options = javaArray('java.nio.file.OpenOption',1);
options(1) = java.nio.file.StandardOpenOption.WRITE;
channel = java.nio.channels.FileChannel.open(source,options);
file_lock = channel.tryLock();
assert_error(@() stage_d_canonical_transaction('save',canonical,results), ...
    'StageD:CanonicalResultArtifactConflict');
file_lock.release(); channel.close();
transaction = [canonical '.stage_d_transaction.mat'];
save(transaction,'results');
stage_d_canonical_transaction('recover',canonical);
recovered = load(canonical);
assert(recovered.results.progress.stage_d_transaction_sequence == 2);
assert(~isfile(transaction));
results = attempted; save(transaction,'results');
stage_d_canonical_transaction('recover',canonical);
assert(~isfile(transaction));
junk = 1; save(transaction,'junk');
stage_d_canonical_transaction('recover',canonical);
assert(~isfile(transaction));
valid_results = recovered.results;
save(canonical,'junk');
results = valid_results; save(transaction,'results');
stage_d_canonical_transaction('recover',canonical);
assert(validate_stage_d_four_temperature_results(load(canonical)).passed);
invalid_directory = fullfile(temporary_directory,'invalid_pair'); mkdir(invalid_directory);
invalid_canonical = fullfile(invalid_directory,'thermal_4T_frequency_domain_results.mat');
save(invalid_canonical,'junk'); save([invalid_canonical '.stage_d_transaction.mat'],'junk');
assert_error(@() stage_d_canonical_transaction('recover',invalid_canonical), ...
    'StageD:CanonicalResultArtifactConflict');
extra = fullfile(temporary_directory,'unexpected.mat'); save(extra,'junk');
assert(~stage_d_canonical_transaction('audit',canonical).passed);
delete(extra);
assert(stage_d_canonical_transaction('audit',canonical).passed);
end

function test_source_scope(repository_root)
runner = fileread(fullfile(repository_root, ...
    'run_stage_d_build_four_temperature_static_states.m'));
solver = fileread(fullfile(repository_root, ...
    'solve_stage_d_static_temperature_case.m'));
transaction = fileread(fullfile(repository_root,'stage_d_canonical_transaction.m'));
combined = [runner newline solver newline transaction];
assert(isempty(regexpi(combined,'\<newmark\w*\s*\(','once')));
assert(isempty(regexpi(combined, ...
    '\<(frequency_response|frf|run_thermal_outer_loop_4cases)\w*\s*\(','once')));
assert(isscalar(regexp(solver, ...
    'solve_thermal_mechanical_outer_loop\s*\(','match')));
assert(isempty(regexp(solver, ...
    'solve_thermal_mechanical_outer_loop\s*\([^\n]*,\s*20\s*,','once')));
assert(contains(runner,"'git rev-parse HEAD^'"));
assert(contains(runner,"'record_timeout'"));
assert(contains(runner,"stage_d_canonical_transaction('save'"));
assert(contains(transaction,'java.nio.file.StandardCopyOption.ATOMIC_MOVE'));
assert(contains(transaction,"'.stage_d_transaction.mat'"));
end

function results = mark_attempt(results,temperature)
payload = struct('temperature_C',temperature,'additional_results_check',audit(), ...
    'process_id',1001,'session_id','session-100');
[results,~] = update_stage_d_canonical_results( ...
    results,payload,'stage-d-test','mark_attempt');
end

function value = audit
value = struct('passed',true,'allowed_files', ...
    {{'thermal_4T_frequency_domain_results.mat'}},'observed_files', ...
    {{'thermal_4T_frequency_domain_results.mat'}},'checked_at',datetime('now'), ...
    'TXT_count',0,'MAT_count',1,'source','TEST_CANONICAL_RESULT_DIRECTORY_SCAN');
end

function state = mock_state(requested,source,baseline)
n = 192;
front_Q = [0 2 4 0]; front_delta = [0 1 2 0];
rear_Q = [1 2;0 0;3 1]; rear_delta = [1 1;0 0;2 1];
front_theta = [0 pi/2 pi 3*pi/2]; rear_theta = [0 2*pi/3 4*pi/3];
front_film_values = [NaN 2e-7 3e-7 NaN];
rear_film_values = [2e-7 3e-7;NaN NaN;4e-7 2e-7];
front_bearing = bearing_state(front_Q,front_delta,front_theta,front_film_values,1,2);
rear_bearing = bearing_state(rear_Q,rear_delta,rear_theta,rear_film_values,3,4);
front_stats = compute_stage_d_bearing_statistics(front_Q,front_theta);
rear_stats = compute_stage_d_bearing_statistics(rear_Q,rear_theta);
front_thermal = thermal_entry(requested,requested+1,1e-5);
rear_thermal = thermal_entry(requested,requested+2,2e-5);
acceptance = struct('mechanical_residual',1e-7, ...
    'thermal_residual_front_C',1e-4,'thermal_residual_rear_C',2e-4, ...
    'thermal_residual_max_C',2e-4,'power_residual_W',0.01, ...
    'axial_constraint_error_m',0,'relative_Q_change',1e-5, ...
    'relative_film_change',1e-4,'kkt_residual_raw',1e-3, ...
    'kkt_residual_normalized',1e-7,'constraint_residual',0, ...
    'complementarity_residual',struct('available',false, ...
    'status','FIELD_NOT_AVAILABLE_IN_FORMAL_SOLVER'), ...
    'active_set_consistency',true,'thermal_outer_iterations',4, ...
    'static_newton_iterations',2,'final_consistency_recompute_count',1, ...
    'thermal_converged',true,'static_converged',true, ...
    'formal_tolerances',struct('temperature_C',1e-3,'power_W',0.12, ...
    'mechanical',1e-6,'axial_m',1e-8,'relative_Q',1e-4, ...
    'relative_film',1e-3), ...
    'formal_acceptance_flag',true);
state = struct('requested_case_temperature_C',requested, ...
    'initial_guess_source_temperature_C',source,'initial_guess_only',true, ...
    'initial_guess_fields_used',{{'q_static'}},'q_static',zeros(n,1), ...
    'thermal_state',struct('ball',front_thermal,'roller',rear_thermal), ...
    'lubricant_state',struct( ...
    'front',lubricant_entry(front_thermal),'rear',lubricant_entry(rear_thermal)), ...
    'film_thickness',struct( ...
    'front',film_entry(front_bearing),'rear',film_entry(rear_bearing)), ...
    'clearance_state',struct( ...
    'front',clearance_entry(front_thermal),'rear',clearance_entry(rear_thermal)), ...
    'bearing_state_front',front_bearing,'bearing_state_rear',rear_bearing, ...
    'rolling_element_loads_front',front_stats.rolling_element_loads_N, ...
    'rolling_element_loads_rear',rear_stats.rolling_element_loads_N, ...
    'loaded_mask_front',front_stats.loaded_mask,'loaded_mask_rear',rear_stats.loaded_mask, ...
    'contact_deflection_front',front_delta,'contact_deflection_rear',rear_delta, ...
    'contact_stiffness_front',1.5*front_Q./max(front_delta,eps), ...
    'contact_stiffness_rear',(10/9)*rear_Q./max(rear_delta,eps), ...
    'contact_stiffness_source_front','FORMAL_BALL_HERTZ_DERIVATIVE', ...
    'contact_stiffness_source_rear','FORMAL_ROLLER_SLICE_LAW_DERIVATIVE', ...
    'bearing_resultant_consistency',struct( ...
    'front_linearization_repeatability_error',0, ...
    'rear_linearization_repeatability_error',0,'front_global_assembly_error',0, ...
    'rear_global_assembly_error',0,'front_action_reaction_error',0, ...
    'rear_action_reaction_error',0,'formal_static_action_reaction_error',0, ...
    'units','MIXED_LOCAL_GENERALIZED_FORCE_VECTOR', ...
    'source','FORMAL_STATIC_ASSEMBLY_AND_WORKPOINT_LINEARIZATION','passed',true), ...
    'K_b_front',eye(5),'K_b_rear',2*eye(5), ...
    'K_tangent',baseline.static.T20.K_tangent_original,'acceptance',acceptance, ...
    'statistics',struct('front',front_stats,'rear',rear_stats), ...
    'final_front_bearing_temperature_C',requested+1, ...
    'final_rear_bearing_temperature_C',requested+2, ...
    'invariant_references',struct('M','results.static.T20.M', ...
    'G','results.static.T20.G','dof_mapping','results.static.T20.dof_mapping', ...
    'M_max_abs_difference',0,'G_max_abs_difference',0,'consistent',true), ...
    'source_commit','stage-d-test');
end

function value = thermal_entry(requested,final_temperature,clearance)
value = struct('T_oil',requested,'T_final',final_temperature, ...
    'T_film',final_temperature-0.1,'T_inner',final_temperature, ...
    'T_outer',final_temperature,'T_element',final_temperature, ...
    'eta',0.02,'alpha_p',1e-8,'working_clearance',clearance, ...
    'film_thickness',1e-7,'thermal_preload',struct());
end

function value = lubricant_entry(thermal)
value = struct('viscosity_Pa_s',thermal.eta, ...
    'pressure_viscosity_Pa_inv',thermal.alpha_p, ...
    'film_temperature_C',thermal.T_film,'source','FORMAL_FROZEN_THERMAL_STATE');
end

function value = bearing_state(Q,delta,theta,h,rotor_node,case_node)
loaded = Q > 0;
value = struct('theta',theta,'Q',Q,'delta',delta,'delta_raw',delta, ...
    'loaded_count',nnz(any(loaded,2)),'loaded_index',find(any(loaded,2)), ...
    'film',struct('h_m',h,'loaded_mask',loaded,'hmin_m',min(h(loaded))), ...
    'Fx',0,'Fy',0,'Fz',0,'Mx',0,'My',0,'r',zeros(5,1), ...
    'rotor_node',rotor_node,'case_node',case_node);
end

function value = film_entry(bearing)
loaded = bearing.Q > 0; central = reshape(bearing.film.h_m(loaded),1,[]);
value = struct('central_by_contact_m',bearing.film.h_m, ...
    'central_loaded_m',central,'central_min_loaded_m',min(central), ...
    'minimum_m',bearing.film.hmin_m,'unit','m', ...
    'source','FORMAL_CONTACT_FILM_STATE','floor_active',false);
end

function value = clearance_entry(thermal)
cold = thermal.working_clearance+1e-6;
value = struct('cold_clearance_m',cold, ...
    'thermal_expansion_correction_m',-1e-6, ...
    'film_or_contact_correction_m',0, ...
    'working_clearance_m',thermal.working_clearance, ...
    'film_or_contact_correction_available',false);
end

function baseline = pre_stage_d_fixture(completed)
% Derive the test baseline in memory; never rewrite the accepted canonical.
baseline = completed;
baseline.static = rmfield(baseline.static,{'T50','T80','T100'});
baseline.meta = rmfield(baseline.meta,'stage_d_source_commit');
baseline.validation = rmfield(baseline.validation,'stage_d');
baseline.progress = rmfield(baseline.progress,{ ...
    'stage_d_T50_attempted','stage_d_T80_attempted', ...
    'stage_d_T100_attempted','stage_d_T50_complete', ...
    'stage_d_T80_complete','stage_d_T100_complete', ...
    'stage_d_static_states_complete','first_failed_temperature_C', ...
    'failure_reason','failure_gate','current_attempt_temperature_C', ...
    'current_attempt_started_at','current_attempt_process_id', ...
    'current_attempt_session_id','last_solver_process_id', ...
    'last_solver_session_id','stage_d_transaction_sequence'});
baseline.progress.stage_d_complete = false;
baseline.progress.last_completed_gate = 'STAGE_C_DAMPING_ENVELOPE';
baseline.decision = struct('status', ...
    'FIXED_EQUIVALENT_DAMPING_ENVELOPE_ACCEPTED','allow_stage_d',true, ...
    'stage_d_executed',false);
end

function assert_error(callback,identifier)
try
    callback();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'Unexpected identifier: %s',exception.identifier);
    return;
end
error('StageD:ExpectedError','Expected %s.',identifier);
end
