function test_stage_b_formal_damping_isolation
%TEST_STAGE_B_FORMAL_DAMPING_ISOLATION Source and synthetic damping contract.

repository_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
original_path = path;
path_cleanup = onCleanup(@() path(original_path));
addpath(repository_root);

working_directory_before = pwd;
global_variables_before = global_variable_state();
repository_before = repository_snapshot(repository_root);

assert_baseline_source_relationship(repository_root);
assert_pure_function_sources(repository_root);

n = 6;
C_rayleigh_legacy = diag(1:n);
C_foundation = diag(11:16);
C_ehl_old = diag(21:26);
C_rayleigh_ref = diag(31:36);
inputs_before = {C_rayleigh_legacy, C_foundation, C_ehl_old, C_rayleigh_ref};

legacy = assemble_equivalent_frequency_domain_damping( ...
    'legacy_ehl_audit', C_rayleigh_legacy, C_foundation, ...
    C_ehl_old, C_rayleigh_ref);
C_expected_legacy = C_rayleigh_legacy + C_foundation + C_ehl_old;
legacy_synthetic_relative_error = relative_error( ...
    legacy.C_legacy_audit, C_expected_legacy);
assert(legacy_synthetic_relative_error <= 1e-12);
assert(isempty(legacy.C_formal));
assert(isequal(legacy.C_base, C_foundation));
assert(isequal(legacy.C_rayleigh_legacy_audit, C_rayleigh_legacy));
assert(isequal(legacy.C_ehl_old_audit, C_ehl_old));
assert(legacy.old_ehl_in_formal == false);
assert(legacy.legacy_rayleigh_in_formal == false);

formal = assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', C_rayleigh_legacy, C_foundation, ...
    C_ehl_old, C_rayleigh_ref);
C_expected_formal = C_foundation + C_rayleigh_ref;
formal_definition_relative_error = relative_error( ...
    formal.C_formal, C_expected_formal);
assert(formal_definition_relative_error <= 1e-12);
assert(isempty(formal.C_legacy_audit));
assert(isequal(formal.C_base, C_foundation));
assert(isequal(formal.C_rayleigh_ref, C_rayleigh_ref));
assert(isequal(formal.C_rayleigh_legacy_audit, C_rayleigh_legacy));
assert(isequal(formal.C_ehl_old_audit, C_ehl_old));
assert(formal.old_ehl_in_formal == false);
assert(formal.legacy_rayleigh_in_formal == false);

formal_large_ehl = assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', C_rayleigh_legacy, C_foundation, ...
    1e6*C_ehl_old, C_rayleigh_ref);
formal_negative_ehl = assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', C_rayleigh_legacy, C_foundation, ...
    -C_ehl_old, C_rayleigh_ref);
formal_old_ehl_sensitivity_error = max( ...
    relative_error(formal_large_ehl.C_formal, formal.C_formal), ...
    relative_error(formal_negative_ehl.C_formal, formal.C_formal));
assert(formal_old_ehl_sensitivity_error <= 1e-12);

formal_large_legacy_rayleigh = assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', 1e6*C_rayleigh_legacy, C_foundation, ...
    C_ehl_old, C_rayleigh_ref);
formal_negative_legacy_rayleigh = assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', -C_rayleigh_legacy, C_foundation, ...
    C_ehl_old, C_rayleigh_ref);
formal_legacy_rayleigh_sensitivity_error = max( ...
    relative_error(formal_large_legacy_rayleigh.C_formal, formal.C_formal), ...
    relative_error(formal_negative_legacy_rayleigh.C_formal, formal.C_formal));
assert(formal_legacy_rayleigh_sensitivity_error <= 1e-12);

assert(isequaln(inputs_before, ...
    {C_rayleigh_legacy, C_foundation, C_ehl_old, C_rayleigh_ref}));
assert(nargin('assemble_equivalent_frequency_domain_damping') == 5);
assert(formal.gyro_is_separate == true);
assert(~isfield(formal, 'G') && ~isfield(formal, 'OmegaG'));
assert(~any(contains(lower(string(fieldnames(formal.component_norms))), 'gyro')));

physical_state = synthetic_physical_state(n);
physical_state_before = physical_state;
assemble_equivalent_frequency_domain_damping('legacy_ehl_audit', ...
    C_rayleigh_legacy, C_foundation, C_ehl_old, C_rayleigh_ref);
assemble_equivalent_frequency_domain_damping('fixed_equivalent_system', ...
    C_rayleigh_legacy, C_foundation, C_ehl_old, C_rayleigh_ref);
assert(isequaln(physical_state, physical_state_before));

assert_invalid_input_contract(C_rayleigh_legacy, C_foundation, ...
    C_ehl_old, C_rayleigh_ref);

runtime = validate_runtime_legacy_damping_equivalence( ...
    C_rayleigh_legacy, C_foundation, C_ehl_old, C_expected_legacy);
assert(runtime.passed && runtime.all_finite && runtime.size_match);
assert(runtime.relative_error <= 1e-12);
assert(strcmp(runtime.space, 'FULL_ORDER_OR_ACTUAL_RUNTIME_SPACE'));
runtime_mismatch = validate_runtime_legacy_damping_equivalence( ...
    C_rayleigh_legacy, C_foundation, C_ehl_old, ...
    C_expected_legacy + eye(n));
assert(~runtime_mismatch.passed && runtime_mismatch.relative_error > 1e-12);
runtime_size_mismatch = validate_runtime_legacy_damping_equivalence( ...
    C_rayleigh_legacy, C_foundation, C_ehl_old, eye(n + 1));
assert(~runtime_size_mismatch.passed && ~runtime_size_mismatch.size_match);
runtime_nonfinite = validate_runtime_legacy_damping_equivalence( ...
    C_rayleigh_legacy, C_foundation, C_ehl_old, ...
    replace_entry(C_expected_legacy, 1, NaN));
assert(~runtime_nonfinite.passed && ~runtime_nonfinite.all_finite);
runtime_asymmetric = validate_runtime_legacy_damping_equivalence( ...
    C_rayleigh_legacy, replace_entry(C_foundation, [1 2], 1), ...
    C_ehl_old, C_expected_legacy);
assert(~runtime_asymmetric.passed);
assert(runtime_asymmetric.symmetry_errors.C_foundation_r > 1e-12);
runtime_empty = validate_runtime_legacy_damping_equivalence( ...
    [], [], [], []);
assert(~runtime_empty.passed && ~runtime_empty.size_match);
assert_error(@() validate_runtime_legacy_damping_equivalence( ...
    'not numeric', C_foundation, C_ehl_old, C_expected_legacy), ...
    'StageB:RuntimeDampingType');
assert_error(@() validate_runtime_legacy_damping_equivalence( ...
    uint8(C_rayleigh_legacy), uint8(C_foundation), ...
    uint8(C_ehl_old), uint8(C_expected_legacy)), ...
    'StageB:RuntimeDampingType');
runtime_overflow = validate_runtime_legacy_damping_equivalence( ...
    realmax*eye(n), realmax*eye(n), realmax*eye(n), realmax*eye(n));
assert(~runtime_overflow.passed && ~runtime_overflow.all_finite);

cfg = build_equivalent_damping_frequency_domain_config();
assert(strcmp(cfg.damping_modes.legacy, 'legacy_ehl_audit'));
assert(strcmp(cfg.damping_modes.formal, 'fixed_equivalent_system'));
assert(isequal(cfg.damping_contract.legacy_components, ...
    {'C_rayleigh_legacy','C_foundation','C_ehl_old'}));
assert(isequal(cfg.damping_contract.formal_components, ...
    {'C_foundation','C_rayleigh_ref'}));
assert(cfg.damping_contract.legacy_rayleigh_in_formal == false);
assert(cfg.damping_contract.old_ehl_in_formal == false);
assert(cfg.damping_contract.gyroscopic_term_is_separate == true);
assert(strcmp(cfg.damping_contract.runtime_equivalence_stage, 'Stage C'));
assert(cfg.damping_contract.runtime_equivalence_pending == true);
assert(strcmp(cfg.damping_contract.stage_b_verification_scope, ...
    'SOURCE_AND_SYNTHETIC_CONTRACT'));
assert(cfg.damping_contract.legacy_audit_artifact_available == false);
assert(strcmp(cfg.damping_contract.runtime_equivalence_gate, ...
    'RUNTIME_LEGACY_DAMPING_EQUIVALENCE_CONFIRMED'));
assert(strcmp(cfg.damping_contract.runtime_equivalence_failure_status, ...
    'RUNTIME_LEGACY_DAMPING_EQUIVALENCE_FAILED'));

assert(strcmp(pwd, working_directory_before));
assert(isequaln(global_variable_state(), global_variables_before));
assert(isequal(repository_snapshot(repository_root), repository_before));

fprintf('legacy_synthetic_relative_error=%.17g\n', ...
    legacy_synthetic_relative_error);
fprintf('formal_definition_relative_error=%.17g\n', ...
    formal_definition_relative_error);
fprintf('formal_old_ehl_sensitivity_error=%.17g\n', ...
    formal_old_ehl_sensitivity_error);
fprintf('formal_legacy_rayleigh_sensitivity_error=%.17g\n', ...
    formal_legacy_rayleigh_sensitivity_error);
fprintf('STAGE_B_FORMAL_DAMPING_ISOLATION_PASSED\n');
end

function assert_baseline_source_relationship(repository_root)
modal_source = fileread(fullfile(repository_root, ...
    'build_temperature_modal_basis.m'));
audit_source = fileread(fullfile(repository_root, ...
    'solve_thermal_outer_loop_case.m'));
modal_executable = strip_comments(modal_source);
audit_executable = strip_comments(audit_source);
assert(~isempty(regexp(modal_executable, ...
    '(?m)^\s*modal\.C_dissipative_r\s*=\s*modal\.C_rayleigh_r\s*\+\s*modal\.C_foundation_r\s*\+\s*modal\.C_ehl_r\s*;', ...
    'once')));
assert(~isempty(regexp(modal_executable, ...
    '(?m)^\s*modal\.G_r\s*=\s*Phi_t''\s*\*\s*G_t\s*\*\s*Phi_t\s*;', 'once')));
assert(~isempty(regexp(audit_executable, ...
    '(?m)^\s*CT\s*=\s*CR\s*\+\s*CF\s*\+\s*CE\s*;', 'once')));
assert(contains(audit_executable, ...
    "'C_ehl_total_r', CE, 'C_total_r', CT"));
end

function assert_pure_function_sources(repository_root)
files = {'assemble_equivalent_frequency_domain_damping.m', ...
    'validate_runtime_legacy_damping_equivalence.m'};
for k = 1:numel(files)
    source = fileread(fullfile(repository_root, files{k}));
    executable = strip_comments(source);
    forbidden = { ...
        '(^|[;\n])\s*global\s+', '\<(assignin|evalin)\s*\(', ...
        '\<(load|save|matfile|fopen|mkdir|cd|system|unix|dos)\s*\(', ...
        '(^|[;\n])\s*(load|save|mkdir|cd|system|unix|dos)\s+', ...
        '(^|[;\n])\s*!', ...
        '\<newmark\w*\s*\(', '\<solve_\w*\s*\(', ...
        '\<eig(s)?\s*\(', '\<ode[0-9]+[a-z]*\s*\(', ...
        '\<(fsolve|fzero|fmincon|fminunc|lsqnonlin|lsqlin|quadprog|intlinprog|linprog|vpasolve|dsolve|linsolve)\s*\('};
    for j = 1:numel(forbidden)
        assert(isempty(regexpi(executable, forbidden{j}, 'once')), ...
            'A Stage B pure function contains a forbidden executable token.');
    end
end
end

function source = strip_comments(source)
source = regexprep(source, '%[^\n]*', '');
end

function assert_invalid_input_contract(CR, CF, CE, CRref)
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'unknown', CR, CF, CE, CRref), 'StageB:DampingMode');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', CR(:,1:end-1), CF, CE, CRref), ...
    'StageB:DampingShape');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', CR, CF(1:end-1,1:end-1), CE, CRref), ...
    'StageB:DampingSize');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', 'not numeric', CF, CE, CRref), ...
    'StageB:DampingType');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', replace_entry(CR, 1, NaN), CF, CE, CRref), ...
    'StageB:DampingFinite');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', CR, replace_entry(CF, 1, Inf), CE, CRref), ...
    'StageB:DampingFinite');
asymmetric = CF;
asymmetric(1,2) = 1;
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', CR, asymmetric, CE, CRref), ...
    'StageB:DampingSymmetry');
huge_asymmetric = realmax*eye(size(CF));
huge_asymmetric(1,2) = realmax;
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', CR, huge_asymmetric, CE, CRref), ...
    'StageB:DampingSymmetry');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', CR, realmax*eye(size(CF)), CE, ...
    realmax*eye(size(CRref))), 'StageB:DampingOutputFinite');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', uint8(CR), uint8(CF), ...
    uint8(CE), uint8(CRref)), 'StageB:DampingType');
assert_error(@() assemble_equivalent_frequency_domain_damping( ...
    'fixed_equivalent_system', single(CR), CF, single(CE), ...
    single(CRref)), 'StageB:DampingClass');
end

function assert_error(callback, expected_identifier)
try
    callback();
catch exception
    assert(strcmp(exception.identifier, expected_identifier), ...
        'Unexpected error identifier: %s', exception.identifier);
    return;
end
error('StageB:ExpectedError', ...
    'Expected error %s was not raised.', expected_identifier);
end

function value = relative_error(actual, expected)
value = norm(actual - expected, 'fro')/max(norm(expected, 'fro'), eps);
end

function matrix = replace_entry(matrix, index, value)
matrix(index) = value;
end

function state = synthetic_physical_state(n)
state = struct('M',eye(n), 'K',diag(41:46), ...
    'G',diag(ones(1,n-1),1)-diag(ones(1,n-1),-1), ...
    'thermal_state',struct('temperature_C',20,'viscosity_Pa_s',0.02), ...
    'bearing_static_force_N',[10;20], 'contact_loads_N',(1:n).', ...
    'mapping',struct('rotor_node',16,'bearing_nodes',[2 10]));
end

function state = global_variable_state
variables = evalin('base', 'whos');
variables = variables([variables.global]);
[~, order] = sort({variables.name});
variables = variables(order);
values = cell(1, numel(variables));
for k = 1:numel(variables)
    values{k} = evalin('base', variables(k).name);
end
state = struct('names', {{variables.name}}, 'values', {values});
end

function snapshot = repository_snapshot(repository_root)
entries = dir(fullfile(repository_root, '**', '*'));
paths = fullfile({entries.folder}, {entries.name});
git_prefix = [repository_root filesep '.git'];
entries = entries(~startsWith(paths, git_prefix));
paths = paths(~startsWith(paths, git_prefix));
relative_paths = erase(paths, [repository_root filesep]);
[relative_paths, order] = sort(relative_paths);
entries = entries(order);
snapshot = struct('path', relative_paths, ...
    'is_directory', num2cell([entries.isdir]), ...
    'bytes', num2cell([entries.bytes]), ...
    'datenum', num2cell([entries.datenum]));
end
