function cfg = dynamic_ehl_model_config()
%DYNAMIC_EHL_MODEL_CONFIG Frozen physics for the isolated local dynamic-EHL model.
%
% This configuration is not read by the formal bearing, thermal, modal, or
% Newmark chains.  It intentionally contains no solver, sampling, or fitted
% damping data.  Q_reference_N stays NaN until one completed 20 C workpoint
% supplies the physical reference contact load.

E_Pa = 210e9;
nu = 0.30;

cfg = struct();
cfg.schema_version = "dynamic-ehl-local-isothermal-barus-v1";
cfg.material = struct( ...
    'E_Pa', E_Pa, ...
    'nu', nu, ...
    'E_star_Pa', E_Pa/(2*(1-nu^2)));

cfg.pressure_viscosity_model = struct( ...
    'name', "BARUS_ISOTHERMAL", ...
    'equation', "eta(p)=eta0*exp(alpha_p*p)", ...
    'isothermal', true, ...
    'thermal_reynolds_included', false, ...
    'density_pressure_coupling_included', false, ...
    'mixed_lubrication_included', false, ...
    'roughness_asperity_included', false);

cfg.geometry_definition = struct( ...
    'ball_radius_definition', "Rb=Dw/2", ...
    'groove_radius_definition', "Rg=f*Dw", ...
    'groove_conformity_f', 0.5232, ...
    'principal_curvatures', "Rx_m and Ry_m are explicit local inputs", ...
    'use_formal_R_effective', false);

cfg.Q_strategy = struct( ...
    'reference_temperature_K', 293.15, ...
    'reference_source', "ONE_COMPLETED_FORMAL_20C_WORKPOINT", ...
    'Q_reference_N', NaN, ...
    'multipliers', [0.5 1.5], ...
    'require_reference_before_sampling', true);

cfg.boundary_condition = struct( ...
    'name', "REYNOLDS_CAVITATION_ZERO_GAUGE_FAR_FIELD", ...
    'far_field_pressure_Pa', 0, ...
    'nonnegative_pressure_enforced', true, ...
    'domain_boundary_pressure_Pa', 0);

cfg.frequency_range = struct( ...
    'min_Hz', 20, ...
    'max_Hz', 1000, ...
    'units', "Hz");
end
