function cfg = dynamic_ehl_model_config()
%DYNAMIC_EHL_MODEL_CONFIG Frozen physics for the isolated local dynamic-EHL model.
%
% This configuration is not read by the formal bearing, thermal, modal, or
% Newmark chains.  It intentionally contains no solver or fitted damping
% data.  The pilot reference below is offline-development metadata only.

E_Pa = 210e9;
nu = 0.30;

cfg = struct();
cfg.schema_version = "dynamic-ehl-local-isothermal-barus-v1";
cfg.material = struct( ...
    'E_Pa', E_Pa, ...
    'nu', nu, ...
    'E_star_Pa', E_Pa/(2*(1-nu^2)));

cfg.pressure_viscosity_model = struct( ...
    'name', "BARUS_ISOTHERMAL", ...
    'equation', "eta(p)=eta0*exp(alpha_p*p)", ...
    'isothermal', true, ...
    'thermal_reynolds_included', false, ...
    'density_pressure_coupling_included', false, ...
    'mixed_lubrication_included', false, ...
    'roughness_asperity_included', false);

cfg.geometry_definition = struct( ...
    'ball_radius_definition', "Rb=Dw/2", ...
    'groove_radius_definition', "Rg=f*Dw", ...
    'groove_conformity_f', 0.5232, ...
    'principal_curvatures', "Rx_m and Ry_m are explicit local inputs", ...
    'use_formal_R_effective', false);

cfg.Q_strategy = struct( ...
    'reference_temperature_K', 293.15, ...
    'reference_source', "ONE_COMPLETED_FORMAL_20C_WORKPOINT", ...
    'Q_reference_N', NaN, ...
    'multipliers', [0.5 1.5], ...
    'require_reference_before_sampling', true);

cfg.pilot_reference_20C = struct( ...
    'available', true, ...
    'reference_level', "PILOT_STATIC_WORKPOINT", ...
    'final_calibration', false, ...
    'temperature_case_C', 20, ...
    'Q_reference_N', 603.4482, ...
    'T_K', 293.15, ...
    'U_m_s', 98.4889, ...
    'Rx_m', 0.0134, ...
    'Ry_m', 0.2685, ...
    'eta_Pa_s', 0.0486, ...
    'alpha_p_Pa_inv', 1.28e-8, ...
    'E_star_Pa', 115.384615e9, ...
    'ball_id', 18, ...
    'contact_type', "FRONT_BALL_OUTER_RACE_MAX_LOADED_BALL", ...
    'source_method', "VALIDATED_RUNTIME_CAPTURE_FROM_LIGHTWEIGHT_20C_STATIC_PATH", ...
    'source_status', "STAGE_D2P1R_REFERENCE_STATE_READY", ...
    'allowed_use', "D2_SAMPLE_DOMAIN_AND_SINGLE_CONTACT_PILOT_ONLY", ...
    'prohibited_use', "FINAL_FOUR_CASE_CALIBRATION_OR_DIRECT_BEARING_DAMPING", ...
    'source_note', "This reference state was returned by a real 20 C lightweight static-equilibrium run and is frozen only to define the local D2 pilot input domain. It is not a final thermal-consistent four-case calibration point. Formal D4/D5 calculations must use the actual runtime contact state.");

cfg.boundary_condition = struct( ...
    'name', "REYNOLDS_CAVITATION_ZERO_GAUGE_FAR_FIELD", ...
    'far_field_pressure_Pa', 0, ...
    'nonnegative_pressure_enforced', true, ...
    'domain_boundary_pressure_Pa', 0);

cfg.frequency_range = struct( ...
    'min_Hz', 20, ...
    'max_Hz', 1000, ...
    'units', "Hz");
end
