function generation = generate_dynamic_ehl_samples_20C()
%GENERATE_DYNAMIC_EHL_SAMPLES_20C Prepare local 20 C dynamic-EHL samples.
%
% The function creates a 15-point, load-only pilot design around the frozen
% cfg.pilot_reference_20C state.  It does not call the retained formal
% extraction diagnostic, or any formal thermal, static, linearization, modal,
% Newmark, or output workflow.  This pilot domain is not a final four-case
% calibration range.  Until a validated dynamic-EHL source becomes available,
% it returns NaN labels rather than manufacturing C_dynamic values.

cfg = dynamic_ehl_model_config();
if ~isfield(cfg, 'pilot_reference_20C')
    error('DynamicEHLSampleGeneration:PilotReference', 'PILOT_REFERENCE_STATE_REQUIRED');
end
reference_state = cfg.pilot_reference_20C;
validate_pilot_reference(reference_state);

sample_count = 15;
load_scale = linspace(0.5, 1.5, sample_count).';
input_design = repmat(empty_input(), sample_count, 1);
for k = 1:sample_count
    input_design(k) = struct( ...
        'Q_N', load_scale(k)*reference_state.Q_reference_N, ...
        'T_K', reference_state.T_K, ...
        'U_m_s', reference_state.U_m_s, ...
        'Rx_m', reference_state.Rx_m, ...
        'Ry_m', reference_state.Ry_m, ...
        'eta_Pa_s', reference_state.eta_Pa_s, ...
        'alpha_p_Pa_inv', reference_state.alpha_p_Pa_inv, ...
        'reference_level', reference_state.reference_level, ...
        'source_note', reference_state.source_note);
end

generation = struct( ...
    'input_points_available', true, ...
    'label_data_available', false, ...
    'input_points', input_design, ...
    'C_dynamic_Ns_m', NaN(sample_count, 1), ...
    'status', "DYNAMIC_EHL_LABEL_SOURCE_REQUIRED", ...
    'source', "NO_VALIDATED_DYNAMIC_EHL_LABEL_SOURCE", ...
    'validation', struct('units', "SI", 'finite_inputs', true, 'positive_loads', true, ...
        'finite_positive_C_dynamic', false, 'labelled_samples_available', false), ...
    'main_program_integration', false);
end

function value = empty_input()
value = struct('Q_N',NaN,'T_K',NaN,'U_m_s',NaN,'Rx_m',NaN,'Ry_m',NaN, ...
    'eta_Pa_s',NaN,'alpha_p_Pa_inv',NaN,'reference_level',"",'source_note',"");
end

function validate_pilot_reference(reference_state)
validateattributes(reference_state, {'struct'}, {'scalar'}, mfilename, 'reference_state', 1);
required = {'available','reference_level','final_calibration','temperature_case_C', ...
    'Q_reference_N','T_K','U_m_s','Rx_m','Ry_m','eta_Pa_s','alpha_p_Pa_inv', ...
    'E_star_Pa','ball_id','contact_type','source_method','source_status', ...
    'allowed_use','prohibited_use','source_note'};
if ~all(isfield(reference_state, required))
    error('DynamicEHLSampleGeneration:PilotReference', 'PILOT_REFERENCE_STATE_INCOMPLETE');
end
if ~reference_state.available || reference_state.final_calibration || reference_state.temperature_case_C ~= 20
    error('DynamicEHLSampleGeneration:PilotReference', 'PILOT_REFERENCE_STATE_INVALID');
end
positive = {'Q_reference_N','T_K','U_m_s','Rx_m','Ry_m','eta_Pa_s','alpha_p_Pa_inv','E_star_Pa','ball_id'};
for k = 1:numel(positive)
    validateattributes(reference_state.(positive{k}), {'numeric'}, ...
        {'scalar','real','finite','positive'}, mfilename, positive{k});
end
if strlength(string(reference_state.reference_level)) == 0 || strlength(string(reference_state.source_note)) == 0
    error('DynamicEHLSampleGeneration:PilotReference', 'PILOT_REFERENCE_STATE_INVALID');
end
end
